### ISSUE TITLE
i3 fails to perform for_window commands with class="arandr" but works with class="Arandr"

### ISSUE THREAD

**Issue by LeoTindall** [i3/i3#3332] opened 2018-07-21 16:41 UTC
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
ARandR has `WM_CLASS(STRING) = "arandr", "Arandr"`
The configuration directive `for_window [class="Arandr"] floating enable` correctly sets it to floating, but the configuration directive `for_window [class="arandr"] floating enable`

## Expected Behavior
Both directives should operate on the window, since its class matches both strings

## Reproduction Instructions
Add `for_window [class="arandr"] floating enable` to your i3 configuration file and start ARandR. It will not be floating.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.15.0.1 (03-13-2018) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15.0.1 (03-13-2018) (pid 32385)rt…)
Loaded i3 config: /home/leo/.config/i3/config (Last modified: Sat 21 Jul 2018 11:38:36 AM CDT, 87 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3\
</pre>

Simply adding the given config directive to the default config file will allow you to reproduce this issue.

<pre>
- Linux Distribution & Version: Manjaro (rolling, updated yesterday)
- Are you using a compositor (e.g., xcompmgr or compton): compton
</pre>

**Comment by Airblader** [comment] 2018-07-21 17:18
There's a misunderstanding here. Both strings aren't the window class, but rather one is the window instance (matched in i3 by "instance"), you can read more on that in the userguide of you search for WM_CLASS.

Since matches are regular expressions you can also make it a case insensitive match by changing the expression.

Closing since it works as intended.

**Closed by Airblader** 2018-07-21 17:18 UTC
Labels: enhancement
