### ISSUE TITLE
video doesn't show anymore after suspend and resume

### ISSUE THREAD

**Issue by yanhick** [i3/i3#1753] opened 2015-06-14 19:25 UTC
Running i3 version: 4.10.2-193-g801b795 (2015-06-12, branch "next")
Ubuntu 15.04
Dell xps 13
Playing video with VLC
http://logs.i3wm.org/logs/5737664527466496.bz2

i3 works well after a fresh start of the laptop but after suspend/resume with pm-suspend or closing/opening lid, the video in vlc doesn't show anymore. The sound still works.

Step to reproduce:
- Start i3
- Suspend
- Resume
- Start vlc, play a video

Suspend/resume works with unity.

Thanks

**Comment by Airblader** [comment] 2015-06-14 19:29
I have no idea how this would relate to the window manager, to be honest.

**Comment by yanhick** [comment] 2015-06-14 19:37
I understand,
I was hesitant to post the issue here as it doesn't seem obviously related to i3. I mentioned video as it was the most obvious issue but I'm experiencing other issues, like the one mentioned here:
http://askubuntu.com/questions/634544/screen-garbled-after-suspend-when-not-using-unity

This might well be due to other unrelated issues which I'm not qualified to identify, unfortunately so far the Linux support for this laptop has been pretty flaky.

**Comment by stapelberg** [comment] 2015-06-14 21:20
There’s no evidence that this is related to i3, hence closing this issue. If you cannot reproduce this in any other window manager (try at least awesome, twm, openbox), please reopen.

**Closed by stapelberg** 2015-06-14 21:20 UTC
Labels: 4.10, bug
