### ISSUE TITLE
Enhancement: More Layouts

### ISSUE THREAD

**Issue by abrahamparayil** [i3/i3#4271] opened 2020-11-24 03:23 UTC
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

Implementing layouts such as fibonacci and master-stack would save the users a lot of time fiddling with their windows as that is what they eventually end up using if they have more than 2 windows on their screen. This would 

### Fibonacci Layout
The windows spawn in the fashion the fibonacci the swirl forms.

![Fibonacci Example](http://xahlee.info/linux/i/tiling_windows_dwm-spiral.png)

### Master-stack or V-stack Layout
Master area in left half, other windows stack up vertically in the right half. The master area may be resizable. May be inverted left-right (wmfs). Aka: tile (dwm, monsterwm).

![v-stack](https://fedoramagazine.org/wp-content/uploads/2019/03/Screenshot-2019-03-15-at-11.12.32-1024x592.png)

**Comment by Airblader** [comment] 2020-11-24 07:07
Duplicate of #4253 and others

i3 is a dynamic tiling wm, it does not aim to predefine layouts. Have a look at things like append_layout, swap and the IPC.

**Closed as completed by Airblader** 2020-11-24 07:07 UTC
Labels: enhancement
