### ISSUE TITLE
i3 causes system hangup and 100% CPU usage when nesting several tabbed layouts

### ISSUE THREAD

**Issue by oddlama** [i3/i3#5712] opened 2023-10-03 11:45 UTC
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Nesting tabbed layouts quickly makes i3 unresponsive and increases CPU usage to a permanent `100%` load. At around 12 nested tab layouts, you see noticable lag, at 15 nested layouts i3 is completely unresponsive on my system.

## Expected Behavior

Nesting layouts should not cause such a severe system hangup. If there's a technical reason for this that cannot be solved easily, I would advocate for i3 to disallow creating that many tabbed layouts. One could say that this is a constructed situation that the user is responsible for creating, but nesting 20 splitv/splith layouts does not cause such a severe hangup.

## Reproduction Instructions

Create a nested tree of tabbed layouts like this one:
```
// vim:ts=4:sw=4:et
{
    // tabbed split container with 1 children
    "border": "pixel",
    "floating": "auto_off",
    "layout": "tabbed",
    "marks": [],
    "percent": null,
    "type": "con",
    "nodes": [
        {
            // tabbed split container with 1 children
            "border": "pixel",
            "floating": "auto_off",
            "layout": "tabbed",
            "marks": [],
            "percent": null,
            "type": "con",
            "nodes": [
                {
                    // tabbed split container with 1 children
                    "border": "pixel",
                    "floating": "auto_off",
                    "layout": "tabbed",
                    "marks": [],
                    "percent": null,
                    "type": "con",
                    "nodes": [
                        {
                            // tabbed split container with 1 children
                            "border": "pixel",
                            "floating": "auto_off",
                            "layout": "tabbed",
                            "marks": [],
                            "percent": null,
                            "type": "con",
                            "nodes": [
                                {
                                    // tabbed split container with 1 children
                                    "border": "pixel",
                                    "floating": "auto_off",
                                    "layout": "tabbed",
                                    "marks": [],
                                    "percent": null,
                                    "type": "con",
                                    "nodes": [
                                        {
                                            // tabbed split container with 1 children
                                            "border": "pixel",
                                            "floating": "auto_off",
                                            "layout": "tabbed",
                                            "marks": [],
                                            "percent": null,
                                            "type": "con",
                                            "nodes": [
                                                {
                                                    // tabbed split container with 1 children
                                                    "border": "pixel",
                                                    "floating": "auto_off",
                                                    "layout": "tabbed",
                                                    "marks": [],
                                                    "percent": null,
                                                    "type": "con",
                                                    "nodes": [
                                                        {
                                                            // tabbed split container with 1 children
                                                            "border": "pixel",
                                                            "floating": "auto_off",
                                                            "layout": "tabbed",
                                                            "marks": [],
                                                            "percent": null,
                                                            "type": "con",
                                                            "nodes": [
                                                                {
                                                                    // tabbed split container with 1 children
                                                                    "border": "pixel",
                                                                    "floating": "auto_off",
                                                                    "layout": "tabbed",
                                                                    "marks": [],
                                                                    "percent": null,
                                                                    "type": "con",
                                                                    "nodes": [
                                                                        {
                                                                            // tabbed split container with 1 children
                                                                            "border": "pixel",
                                                                            "floating": "auto_off",
                                                                            "layout": "tabbed",
                                                                            "marks": [],
                                                                            "percent": null,
                                                                            "type": "con",
                                                                            "nodes": [
                                                                                {
                                                                                    // tabbed split container with 1 children
                                                                                    "border": "pixel",
                                                                                    "floating": "auto_off",
                                                                                    "layout": "tabbed",
                                                                                    "marks": [],
                                                                                    "percent": null,
                                                                                    "type": "con",
                                                                                    "nodes": [
                                                                                        {
                                                                                            // tabbed split container with 2 children
                                                                                            "border": "pixel",
                                                                                            "floating": "auto_off",
                                                                                            "layout": "tabbed",
                                                                                            "marks": [],
                                                                                            "percent": 1,
                                                                                            "type": "con",
                                                                                            "nodes": [
                                                                                                {
                                                                                                    "border": "pixel",
                                                                                                    "current_border_width": 2,
                                                                                                    "floating": "auto_off",
                                                                                                    "geometry": {
                                                                                                       "height": 2135,
                                                                                                       "width": 1916,
                                                                                                       "x": 0,
                                                                                                       "y": 0
                                                                                                    },
                                                                                                    "marks": [],
                                                                                                    "name": "~",
                                                                                                    "percent": 0.5,
                                                                                                    "swallows": [
                                                                                                       {
                                                                                                       // "class": "^kitty$",
                                                                                                       // "instance": "^kitty$",
                                                                                                       // "machine": "^kroma$",
                                                                                                       // "title": "^\\~$"
                                                                                                       }
                                                                                                    ],
                                                                                                    "type": "con"
                                                                                                },
                                                                                                {
                                                                                                    "border": "pixel",
                                                                                                    "current_border_width": 2,
                                                                                                    "floating": "auto_off",
                                                                                                    "geometry": {
                                                                                                       "height": 2135,
                                                                                                       "width": 1916,
                                                                                                       "x": 0,
                                                                                                       "y": 0
                                                                                                    },
                                                                                                    "marks": [],
                                                                                                    "name": "~",
                                                                                                    "percent": 0.5,
                                                                                                    "swallows": [
                                                                                                       {
                                                                                                       // "class": "^kitty$",
                                                                                                       // "instance": "^kitty$",
                                                                                                       // "machine": "^kroma$",
                                                                                                       // "title": "^\\~$"
                                                                                                       }
                                                                                                    ],
                                                                                                    "type": "con"
                                                                                                }
                                                                                            ]
                                                                                        }
                                                                                    ]
                                                                                }
                                                                            ]
                                                                        }
                                                                    ]
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}
```

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.22 (2023-01-02) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.22 (2023-01-02) (pid 215468)
Loaded i3 config:
  /home/malte/.config/i3/config (main) (last modified: Tue Oct  3 13:25:23 2023, 1049 seconds ago)

The i3 binary you just called: /nix/store/a5vrscfp2f507as4bkpmxbhsph1rz7sf-i3-4.22/bin/i3
The i3 binary you are running: i3
</pre>

<details><summary>Config file</summary><pre>
# The default i3 config suffices to reproduce this.
</pre>
</details>

<pre>
Logfile URL: https://logs.i3wm.org/logs/6276601994018816.bz2
</pre>

<pre>
- Linux Distribution & Version: NixOS (bleeding edge)
- Are you using a compositor (e.g., xcompmgr or compton): No
</pre>

**Comment by orestisfl** [comment] 2023-10-03 11:51
Duplicate of https://github.com/i3/i3/issues/3001

**Closed as not planned by orestisfl** 2023-10-03 11:51 UTC
Labels: bug, 4.22
