### ISSUE TITLE
[feature request] Add a default action for unused keysyms

### ISSUE THREAD

**Issue by jvalencia80** [i3/i3#2029] opened 2015-10-23 15:22 UTC
For example:

    mode "mymode" {
        bindsym   $mod+a        command1
        bindsym   $mod+b        command2
        bindsym   $mod+Any      mode "default"
    }

The special keyword "Any" (just an example) would catch any key not used with $mod.

It's also independent for each mod combination like $mod, $mod+Control, $mod+Alt, and so on.

What is this solving? I find I'm sending keystrokes to my open applications if I forget to exit that mode or hit a wrong key combination. This is specially problematic when using text editors.

It also could be useful also for the general configuration file:

    <list of bindsyms>
    bindsym    $mod+Any    nop

That will stop sending undefined/wrong keystrokes to focused apps for example.

**Comment by Airblader** [comment] 2015-10-23 15:24
So you want to effectively disallow any application other than i3 to define key bindings? I don't think that's a good idea.

**Comment by DavidMikeSimon** [comment] 2015-10-23 16:56
@Airblader I think the idea is to prevent any other application from defining key bindings with the mod key. That would be helpful for me; I don't know of any mappings in my apps that use my modkey, so if i3 doesn't handle a modkey+foo then that means it was a mistype.

**Comment by Airblader** [comment] 2015-10-23 17:19
I don't really see a need for this. We already have something in place to help you be aware of being in a binding mode, which is the bindings mode indicator.

In the past we've decided against features that are basically just fixing something caused by not being careful, this seems to fall into the same category for me.

(This could even be implemented outside of i3 as a little tool watching for `mode` events)

**Comment by jvalencia80** [comment] 2015-10-23 17:47
They idea is to not send unmatched $mod keystrokes to focused apps. This can happen easily in a binding mode where you forget to exit or in general, if you hit an incorrect keysim.

I don't know the order of precedence between app keystrokes and i3. Who takes precedence???

If it's App -> i3, then it works.
If it's i3 -> App, then it can make conflicts by not allowing the app to define key combinations with $mod.

What happens if you use Alt as $mod and then an App has the same keystroke defined as i3?

**Comment by stapelberg** [comment] 2015-10-23 20:38
This is a duplicate of #662.

**Closed by stapelberg** 2015-10-23 20:38 UTC
Labels: enhancement
