### ISSUE TITLE
2 floating windows on top of each other

### ISSUE THREAD

**Issue by wdlaszlo** [i3/i3#3338] opened 2018-07-27 20:32 UTC
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

I want to set my workspace with 2 floating windows - one of them Skype and another Sky. I want to resize each of them and align them nicely. Currently both windows are on top of each other.

## Expected Behavior

I want Skype to be on left of screen and Sky on right.

## Reproduction Instructions

for_window [class="Skype"] floating enable resize set 1300px 1050px, move absolute position 50px 50px
for_window [class="Sky"] floating enable resize set 400px 1060px, move absolute position 1450px 50px

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
Binary i3 version:  4.15 (2018-03-10) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15 (2018-03-10) (pid 4443)o abort…)
Loaded i3 config: /home/wlaszlo/.config/i3/config (Last modified: Fri 27 Jul 2018 11:22:27 PM EEST, 26 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
https://pastebin.com/eXaxDDmA
</pre>

<pre>
Logfile URL:
</pre>

<pre>
- Linux Distribution & Version: Fedora 28
- Are you using a compositor (e.g., xcompmgr or compton): no
</pre>

**Comment by Airblader** [comment] 2018-07-27 20:34
Match criteria are regular expressions, so your line for Sky is also matching that for Skype. You can use `"^Sky$"` to be specific about it. 

Closing as works as intended.

**Closed by Airblader** 2018-07-27 20:34 UTC
Labels: enhancement
