### ISSUE TITLE
i3 crashs when rename workspace

### ISSUE THREAD

**Issue by colinvidal** [i3/i3#1616] opened 2015-03-31 15:59 UTC
Since i3 4.10.1, i3 crashes every time (with the message "i3 just crashed") when I rename a workspace with this command : 
i3-msg rename workspace to "new name"

My version of i3 (packaged by ArchLinux)
i3 version 4.10.1 (2015-03-29, branch "4.10.1") © 2009-2014 Michael Stapelberg and contributors

/usr/bin/i3: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=e354f77925113f5c89cf5f07d2e3ace4840a9738, not stripped

Logfile: http://logs.i3wm.org/logs/5717271485874176.bz2 (I use i3-dump-log juste before renaming workspace)
I don't have backtrace, the backtrace file just tell "No stack.".

**Comment by Airblader** [comment] 2015-03-31 16:01
Duplicate of #1607

**Closed** 2015-03-31 16:02 UTC
Labels: 4.10.1
