### ISSUE TITLE
Unexpected from tiling to float mode

### ISSUE THREAD

**Issue by nvanggaard** [i3/i3#1923] opened 2015-09-15 19:12 UTC
From time to time i3 changes a window from tiling to floating mode, i'm not sure but i think it only happens when i'm using firefox. 

A link for my log file:
http://logs.i3wm.org/logs/5734183724908544.bz2

My Version:
Binary i3 version:  4.10.4 (2015-09-08, branch "4.10.4") © 2009-2014 Michael Stapelberg and contributors
Running i3 version: 4.10.4 (2015-09-08, branch "4.10.4") (pid 481)

**Comment by Airblader** [comment] 2015-09-15 20:49
Can you please use `xprop` or `xwininfo` on a window that did this after it happened to figure out the window id and provide us both a log file from that incident and said window id? And also the exact time it happened. This will help us locate the incident in the log file.

Your config contains a few rules to make certain windows floating. Are you sure it's not just one of them?

**Comment by nvanggaard** [comment] 2015-09-15 20:57
Of course! I'll do it the next time it happens.

I know that I have some settings which makes some windows floating, but they should only do it if the window has the title: "Firefox Preferences" or "Library" and the class is if Firefox.
But well if there is a bug in firefox which gives the window that title for a moment I guess the window will float.

**Comment by Airblader** [comment] 2015-09-15 21:01
You also have non-firefox related criteria in there that will float a window where you only match on the title. That's potentially "dangerous" because any website containing that word in its title will cause your Firefox to float. I think it's unlikely that this is what is causing it, but a) you never know, b) it would explain the randomness. So let's just make sure. Either way, with this new information we'd be able to see in the log file what is causing the window to float (hopefully). :)

**Comment by Airblader** [comment] 2015-09-15 21:02
P.S.: You should generally try to avoid matching on the title. It's really better to match on the window class or other things instead. I know some applications don't set useful classes, though.

**Comment by nvanggaard** [comment] 2015-09-15 21:14
Well I get your point that it can be dangerous only matching the title, but that's an old rule. Besides i have a friend who has this issue as well. 

But I will try to change the title=Figure * rule to something else, and see if it helps.

**Comment by Airblader** [comment] 2015-09-15 21:16
It might be easier to keep the rule, wait for it to happen and get the information I mentioned above. When it happens, we know when to stop looking and we can analyze it. If you remove the rules, you won't know how long to wait before concluding that they were at fault. :)

**Comment by stapelberg** [comment] 2015-09-16 17:35
Chances are really high this is either unwanted behavior in Firefox or your config file at fault. I’ll close this, please reopen when you have concrete evidence that there’s a bug in i3.

**Closed by stapelberg** 2015-09-16 17:35 UTC
Labels: 4.10, bug

**Comment by nvanggaard** [comment] 2015-09-16 17:39
It happen again this evening. 
Link to log file:
http://logs.i3wm.org/logs/5725485073956864.bz2

output from xprop:
http://pastebin.com/bdJbsmEm

It happen at 19.27. 

Hope this helps :)

**Comment by stapelberg** [comment] 2015-09-16 18:31
```
09/16/2015 06:55:43 PM - handlers.c:handle_event:1321 - event type 28, xkb_base 85
09/16/2015 06:55:43 PM - _NET_WM_NAME changed to "Login to remote access - Aalborg University Library (AUB) - Mozilla Firefox"
09/16/2015 06:55:43 PM - assignments.c:run_assignments:20 - Checking if any assignments match this window
09/16/2015 06:55:43 PM - Checking window 0x0180007c (class Firefox)
09/16/2015 06:55:43 PM - Regular expression "^Thunderbird$" does not match "Firefox"
09/16/2015 06:55:43 PM - Checking window 0x0180007c (class Firefox)
09/16/2015 06:55:43 PM - Regular expression "^Thunderbird$" does not match "Firefox"
09/16/2015 06:55:43 PM - Checking window 0x0180007c (class Firefox)
09/16/2015 06:55:43 PM - Regular expression "MATLAB R2015a" does not match "Login to remote access - Aalborg University Library (AUB) - Mozilla Firefox"
09/16/2015 06:55:43 PM - Checking window 0x0180007c (class Firefox)
09/16/2015 06:55:43 PM - Regular expression "Qalculate" does not match "Login to remote access - Aalborg University Library (AUB) - Mozilla Firefox"
09/16/2015 06:55:43 PM - Checking window 0x0180007c (class Firefox)
09/16/2015 06:55:43 PM - Regular expression "Figure *" does not match "Login to remote access - Aalborg University Library (AUB) - Mozilla Firefox"
09/16/2015 06:55:43 PM - Checking window 0x0180007c (class Firefox)
09/16/2015 06:55:43 PM - Regular expression "Firefox" matches "Firefox"
09/16/2015 06:55:43 PM - window class matches (Firefox)
09/16/2015 06:55:43 PM - Regular expression "Firefox Preferences" does not match "Login to remote access - Aalborg University Library (AUB) - Mozilla Firefox"
09/16/2015 06:55:43 PM - Checking window 0x0180007c (class Firefox)
09/16/2015 06:55:43 PM - Regular expression "Firefox" matches "Firefox"
09/16/2015 06:55:43 PM - window class matches (Firefox)
09/16/2015 06:55:43 PM - Regular expression "Library" matches "Login to remote access - Aalborg University Library (AUB) - Mozilla Firefox"
09/16/2015 06:55:43 PM - title matches (Login to remote access - Aalborg University Library (AUB) - Mozilla Firefox)
09/16/2015 06:55:43 PM - assignments.c:run_assignments:43 - matching assignment, would do:
09/16/2015 06:55:43 PM - assignments.c:run_assignments:45 - execute command floating enable
09/16/2015 06:55:43 PM - commands_parser.c:parse_command:271 - COMMAND: *[id="25165948"] floating enable*
[…]
09/16/2015 06:55:43 PM - ipc.c:ipc_send_window_event:1157 - Issue IPC window floating event (con = 0x105a100, window = 0x0180007c)
```

At 19:27, i3 registers a click into that window:

```
09/16/2015 07:28:11 PM - click.c:handle_button_press:350 - Button 0 press on window 0x0180007c (child 0x00000000) at (659, 342) (root 661, 362)
09/16/2015 07:28:11 PM - click.c:handle_button_press:356 - floating_mod = 0, detail = 1
09/16/2015 07:28:11 PM - click.c:route_click:175 - --> click properties: mod = 0, destination = 2
09/16/2015 07:28:11 PM - click.c:route_click:176 - --> OUTCOME = 0x105a100
09/16/2015 07:28:11 PM - click.c:route_click:177 - type = 2, name = (null)
09/16/2015 07:28:11 PM - ../i3-4.10.4/src/bindings.c:get_binding_from_xcb_event:208 - (removed numlock, state = 0)
09/16/2015 07:28:11 PM - ../i3-4.10.4/src/bindings.c:get_binding_from_xcb_event:212 - (removed upper 8 bits, state = 0)
09/16/2015 07:28:11 PM - ../i3-4.10.4/src/bindings.c:get_binding_from_xcb_event:217 - (checked mode_switch, state 0)
09/16/2015 07:28:11 PM - ../i3-4.10.4/src/bindings.c:get_binding_from_xcb_event:228 - no match, new state_filtered = 0
09/16/2015 07:28:11 PM - ../i3-4.10.4/src/bindings.c:get_binding_from_xcb_event:235 - Could not lookup key binding (modifiers 0, keycode 1)
09/16/2015 07:28:11 PM - con.c:con_focus:195 - con_focus = 0x105a100
09/16/2015 07:28:11 PM - con.c:con_focus:195 - con_focus = 0x1008660
09/16/2015 07:28:11 PM - con.c:con_focus:195 - con_focus = 0x1007400
09/16/2015 07:28:11 PM - con.c:con_focus:195 - con_focus = 0x1006fb0
09/16/2015 07:28:11 PM - con.c:con_focus:195 - con_focus = 0x1004c70
09/16/2015 07:28:11 PM - floating.c:floating_raise_con:388 - Raising floating con 0x1008660 / (null)
```

I don’t see anything unexpected here, and the logfile is rather big.

I think we’ll need steps to reproduce. From what I see, I’m still not convinced there’s actually an i3 bug.
