### ISSUE TITLE
i3 doesn't set focus to window when moving from different Xorg screen

### ISSUE THREAD

**Issue by sleep-walker** [i3/i3#2216] opened 2016-02-19 11:43 UTC
I have 3 monitors connected to 2 video cards running Xorg with two screens and two instances of i3 (4.11) . Simply said, keyboard doesn't follow mouse when crossing Xorg screen boundary. I can use mouse to switch windows and get focus that way but it is not much handy.

I found another user with the same problem on [reddit](https://www.reddit.com/r/i3wm/comments/3q6np9/i3_on_multiple_x_screens_x_screens_not_only/).

As quick workaround I have script bound to key combination so I can get focus quickly:
```
#!/bin/bash
if [ "$DISPLAY" != ":0.1" ]; then
    export DISPLAY=:0.1
else
    export DISPLAY=:0.0
fi

i3-msg workspace back_and_forth
i3-msg workspace back_and_forth
```

Relevant excerpt from log:
```
19.2.2016 12:29:13 - handlers.c:handle_enter_notify:131 - enter_notify for 00000543, mode = 0, detail 4, serial 1228
19.2.2016 12:29:13 - handlers.c:handle_enter_notify:132 - coordinates 5, 648
19.2.2016 12:29:13 - handlers.c:handle_enter_notify:153 - Getting screen at 5 x 648
19.2.2016 12:29:13 - randr.c:get_output_containing:102 - comparing x=5 y=648 with x=0 and y=0 width 1280 height 1024
19.2.2016 12:29:13 - workspace.c:_workspace_show:385 - Not switching, already there.
19.2.2016 12:29:13 - con.c:con_focus:199 - con_focus = 0x200ad50
19.2.2016 12:29:13 - con.c:con_focus:199 - con_focus = 0x2009800
19.2.2016 12:29:13 - con.c:con_focus:199 - con_focus = 0x2009310
19.2.2016 12:29:13 - con.c:con_focus:199 - con_focus = 0x2008ef0
```

Log from the i3 session on secondary screen (DISPLAY=:0.1)
http://logs.i3wm.org/logs/5676982813589504.bz2

Version used:
```
$ i3 --moreversion 2>&- || i3 --version
Binary i3 version:  4.11 (2015-09-30, branch "4.11") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.11 (2015-09-30, branch "4.11") (pid 14177)
Loaded i3 config: /home/tcech/.config/i3/config (Last modified: Pá 19. únor 2016, 12:03:45 CET, 155 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

**Comment by Airblader** [comment] 2016-02-19 11:48
We don't support multiple X screens. Duplicate of #2082

**Comment by Airblader** [comment] 2016-02-19 11:49
If someone can come up with a clean pull request, we'll be happy to discuss it, though.

**Closed by Airblader** 2016-02-19 11:48 UTC
Labels: 4.11

**Comment by i336** [comment] 2016-04-14 07:25
Further information and (really hacky, but low CPU) workaround, from #2297:

How to reproduce this bug on ANY machine, regardless of your GPU / X setup:

```
Xephyr :0 -screen 640x480 -screen 640x480 &q
DISPLAY=:0.0 i3 --shmlog-size=26214400 &
DISPLAY=:0.1 i3 --shmlog-size=26214400 &
DISPLAY=:0.0 xterm & DISPLAY=:0.0 xterm &
DISPLAY=:0.1 xterm & DISPLAY=:0.1 xterm &
```

Sit the Xephyr windows side by side then move the mouse between the two closest `xterms` (if the `xterms` are not vertical then set them to be). The bug will immediately be apparent.

Workaround (prepare for epic horrid hax):

```
xev -root -event mouse | sed -un 's/.*same_screen \(NO\|YES\).*/\1/;t1;b2;:1;s/NO/1/p;s/YES/0/p;:2' | while read x; do export DISPLAY=:0.$x; xdotool windowfocus $(xprop -root _NET_ACTIVE_WINDOW | grep -o '0x[^$]\+'); done
```

This runs `xev -event mouse`, which lists events like this:

```
(... event, serial 19, synthetic NO, window 0x31e,)
    mode NotifyNormal, detail NotifyNonlinearVirtual, same_screen YES,
...
    mode NotifyNormal, detail NotifyNonlinearVirtual, same_screen NO,
...
    mode NotifyNormal, detail NotifyNonlinearVirtual, same_screen YES,
```

A regex captures the `same_screen` info and uses that to set `DISPLAY=:0.x` for the resulting `xdotool` command (you might need to rewrite this bit to suit your setup - any regex will do).

The result doesn't use endless polling with `sleep 0.1`s, or anything like that, so it's pretty good - the only thing that goes nuts as I move my rapidly mouse between screens is Chrome, but Chrome goes nuts whether this is running or not. :P
