### ISSUE TITLE
i3-style window titles for client-side-decorated windows

### ISSUE THREAD

**Issue by pv4** [i3/i3#4151] opened 2020-07-02 15:38 UTC
## I'm submitting a…
<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
If a window is a client-side-decorated one then the standard i3-style window title (with window name) is not displayed. It only starts being displayed if e.g. the csd-window is tabbed with other ones.

## Desired Behavior
For users who got used to standard i3-style window titles (like me) it would be nice to have an option to show i3-style title even if a window is a csd one and has its own "title" (with close/minimize/maximize buttons etc.).

The quick-and-dirty workaround I currently use with 4.18 is in the attached patch. It forces the desired behavior without any options to disable it in config. It works for me but I'm unsure whether it's 100% correct and doesn't break anything.
[i3-4.17.1-no_csd.patch.gz](https://github.com/i3/i3/files/4865252/i3-4.17.1-no_csd.patch.gz)

## Environment
<pre>
i3 version: 4.17.1, 4.18 (tested by me though I'm sure other versions are affected too)
</pre>

**Comment by orestisfl** [comment] 2020-07-02 16:03
I think this is a duplicate of https://github.com/i3/i3/issues/2255. See if https://github.com/i3/i3/issues/2255#issuecomment-291691768 works for you

**Closed as completed by orestisfl** 2020-07-02 16:03 UTC
Labels: enhancement

**Comment by pv4** [comment] 2020-07-02 18:40
> I think this is a duplicate of #2255. See if [#2255 (comment)](https://github.com/i3/i3/issues/2255#issuecomment-291691768) works for you

You're right, thanks. The solution works for me. I really tried to find anything related to csd before creating a new issue but failed. Sorry.

Although I prefer
```
for_window [tiling] border normal
```
I think it's sliiightly faster than regular expression matching variant.
