### ISSUE TITLE
Strange interaction of `layout tabbed` with `workspace_layout`

### ISSUE THREAD

**Issue by Xyene** [i3/i3#4255] opened 2020-11-13 15:29 UTC
## I'm submitting a…

<pre>
[ ] Bug
[ ] Feature Request
[x] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

I'm not really sure if this is a bug, but it does sound like i3 is doing something other than what the documentation say it should be doing, so here it is.

1. With `workspace_layout tabbed`, and opening a single application on an empty workspace, the resulting layout is `H[T[app]]` (workspace node layout is `splith`).
2. With `workspace_layout default` and doing the same, the layout is `H[app]` (`app` is a direct child of the workspace node).
3. With `workspace_layout tabbed`, but running `layout tabbed` on an empty workspace, the layout is `T[T[app]]`.
4. With `workspace_layout default`, but running `layout tabbed` on an empty workspace, **the layout is again `T[T[app]]`**.

## Expected Behavior

In step 4, I feel like the layout produced should be `T[app]`. The documentation for `workspace_layout` says:

> This option determines in which mode new containers on workspace level will start.

It seems like the layout in step 4 violates this: the new workspace-level container was created with a tabbed layout, despite `workspace_layout` being set to `default`.

This is admittedly a bit of a niche issue, but it came up while working on making Sway's layout behavior more consistent with i3's (https://github.com/swaywm/sway/pull/5756). So, I think understanding i3's reasoning here (in case this is intended behavior) would be helpful :)

## Environment

i3 master.

**Comment by orestisfl** [comment] 2024-01-28 16:08
Duplicate of #3001

**Closed as not planned by orestisfl** 2024-01-28 16:08 UTC
Labels: documentation
