### ISSUE TITLE
i3-dmenu-desktop stopped working

### ISSUE THREAD

**Issue by dkatsanikakis** [i3/i3#2371] opened 2016-06-10 10:00 UTC
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.12 (2016-03-06, branch "4.12") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.12 (2016-03-06, branch "4.12") (pid 1485)
Loaded i3 config: /home/dkatsanikakis/.config/i3/config (Last modified: Fri 10 Jun 2016 12:33:37 PM EEST, 1082 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

**LogFile**
http://logs.i3wm.org/logs/5729821648748544.bz2

**What I did:**
I have enabled the i3-dmenu-deskotp by binding to the "$mod+d". All was working fine until suddenly the specific key-bind stop responding.

**What I saw:**
I noticed that the i3-dmenu-dekstop was not showing in my bar so i went and check my syslog and found the bellow messages:

```
Jun  6 16:08:31 mypc /etc/gdm3/Xsession[1485]: No such file or directory at /usr/bin/i3-dmenu-desktop line 28.
Jun  6 16:08:32 mypc /etc/gdm3/Xsession[1485]: No such file or directory at /usr/bin/i3-dmenu-desktop line 28.
```

I opened the relevant file and found the line mentioned in the error message however i have no knowledge of Perl hence i could not understand much. 

**What I expected instead:**
It should have displayed on the status bar the available programs to be executed.

**Comment by Airblader** [comment] 2016-06-10 18:38
Duplicate of #2368. Closing this one since the other one has more information.

**Closed by Airblader** 2016-06-10 18:38 UTC
Labels: 4.12
