### ISSUE TITLE
Crash when closing floating placeholder window which is not on screen

### ISSUE THREAD

**Issue by spasticVerbalizer** [i3/i3#1739] opened 2015-06-08 10:52 UTC
I have run into a reproducible crash while trying to get a saved layout to match a floating window, after appending the layout and closing the floating window via $mod+Shift+q i3 crashes. The floating placeholder window does not map to the screen, but does exist somewhere on the workspace, as the workspace will not close after closing the two non-floating windows and moving away. When I focus the floating window using $mod+space and close it with $mod+shift+q, i3 crashes.

i3 version:

    Binary i3 version:  4.10.2 (2015-04-16, branch "4.10.2") © 2009-2014 Michael Stapelberg and contributors
    Running i3 version: 4.10.2 (2015-04-16, branch "4.10.2") (pid 25104)
i3 log:
http://logs.i3wm.org/logs/5765606242516992.bz2
Workspace file:
http://pastebin.com/Yw9fJDLr

**Comment by Airblader** [comment] 2015-06-11 19:23
This could be related to #1271.

**Comment by Airblader** [comment] 2015-06-11 19:25
The bottom of the log reads

> 08-06-15 12:43:28 - ERROR: No state found

Since this error case is followed by an `assert(false);`, it explains the crash.

**Comment by Airblader** [comment] 2015-06-11 19:28
I can repro the crash with the given layout file.

**Comment by Airblader** [comment] 2015-06-11 19:35
Here's the part of the tree for the workspace with the broken floating container: http://pastebin.com/m6sA3N29

**Comment by Airblader** [comment] 2015-06-11 19:47
And here's the relevant part of my i3 log when loading the layout file (floating container only): http://pastebin.com/Qf7M82cu.

The interesting part being that it does actually say

> 06/11/2015 09:42:14 PM - x.c:x_con_init:158 - adding new state for window id 0x00800094

**Comment by Airblader** [comment] 2015-06-11 19:58
I think the problem is that closing the container removes the state and then rendering is somehow triggered for it which causes this crash. I still have to investigate more, though.

**Comment by Airblader** [comment] 2015-06-12 17:21
Mostly for self reference, here is a condensed version of my log file of the crash. It covers only the time from the command on and rendering logs have been removed.

http://pastebin.com/XPem9WiS

**Comment by Airblader** [comment] 2015-06-12 21:21
So from what I can tell so far, the window goes through `x_con_kill` twice, causing the crash as the second time the state will already be gone from the first time. I haven't yet understood why this happens only for floating + placeholder, though.

**Comment by Airblader** [comment] 2015-06-13 17:13
OK, I think here is what happens: `tree_close` is called for the floating container. Around line 220, we iterate over its children and call `tree_close` on them. The call for the child now moves on to around line 320 where, because it is floating, `tree_close` is called on the parent.

This looks like an infinite loop kind of deal to me, but we don't get that far because the duplicated call to `x_con_kill` already causes the assertion failure. For a floating urxvt I cannot repro this because it supports WM_DELETE (as probably most applications do) which aborts the process. So maybe this is why this only seems to break for placeholder windows.

This is still sort of a suspicion, though. The code is really complex, unfortunately, and a naive attempt to not call `x_con_kill` (to verify the infinite loop) only causes other issues.

**Comment by Airblader** [comment] 2015-06-13 17:35
I think I will stop looking into this for now. If this is the case, fixing it will take a lot of knowledge on why the process works the way it does. @stapelberg Maybe you can take a look sometime and see if what I said in my previous comment makes sense?

**Comment by stapelberg** [comment] 2015-08-05 19:41
Adding a “rect” property to the floating_con fixes the issue in my testcase. I’ll try to make i3-save-tree(1) add this and also make i3 try to cope with it being missing.

**Comment by stapelberg** [comment] 2015-08-05 20:12
There is one more hidden issue: the workspace itself gets killed when killing the floating container. Something else must still be wrong.

**Comment by Airblader** [comment] 2015-08-05 20:14
I can't look it up right now but I think we have an open bug that also has the root cause of the workspace being killed. I've looked into it a bit, but  the workflow is fairly complex with many code paths. 

Also, adding the rest as you mentioned will also fix another open issue about floating placeholders being misplaced, I think.

**Comment by stapelberg** [comment] 2015-08-05 20:33
@spasticVerbalizer How did you generate that stored layout? I’m curious about the `"floating": "user_on"` line in the floating_con, which is unexpected. If you can reproduce this, can you please provide a logfile where you generate such a layout file?

**Closed** 2015-08-05 20:44 UTC
Labels: 4.10, bug, reproducible
