### ISSUE TITLE
Artefacts (glitches) arount qt icons in tray.

### ISSUE THREAD

**Issue by Niroday** [i3/i3#3197] opened 2018-03-24 11:45 UTC
**Output of `i3 --moreversion 2>&- || i3 --version`:**
Binary i3 version:  4.15 (2018-03-10) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15 (2018-03-10) (pid 849)to abort…)
Loaded i3 config: /home/localuser/.config/i3/config (Last modified: Sat 24 Mar 2018 11:31:20 AM MSK, 11458 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

**URL to a logfile as per https://i3wm.org/docs/debugging.html:**
https://logs.i3wm.org/logs/5672265731538944.bz2

**What I did:**
Appears when i restart i3 or use "minimize on start" option in qt application settings.

**What I saw:**
Artifacts (glitches) around qt icons in tray (keepassxc, qbittorent).
![qt-bug](https://user-images.githubusercontent.com/36510085/37557990-03789756-2a1e-11e8-8edc-6ae78fd227e8.png)
![bug2](https://user-images.githubusercontent.com/36510085/37557991-039b2b54-2a1e-11e8-82d4-a4a186552844.png)
![bug1](https://user-images.githubusercontent.com/36510085/37557992-03bba406-2a1e-11e8-8b74-a3a64bcb03df.png)

**What I expected instead:**
"Clean" icons.

[This topic](https://github.com/keepassxreboot/keepassxc/issues/1733) describes a part of a problem.

**Comment by Airblader** [comment] 2018-03-24 11:54
Duplicate of https://github.com/i3/i3/issues/2325

For an explanation of what's going on, see https://github.com/awesomeWM/awesome/issues/1720 or https://github.com/awesomeWM/awesome/issues/1856

This would likely be fixed by implementing the replacement specification, for which an open feature request on here already exists.

**Closed by Airblader** 2018-03-24 11:54 UTC
Labels: 4.15
