### ISSUE TITLE
Emacs gtk native tooltips are not shown as tooltips (only in i3 AFAIK)

### ISSUE THREAD

**Issue by memeplex** [i3/i3#3334] opened 2018-07-24 23:47 UTC
## I'm submitting a…
<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

When emacs is compiled with gtk3 support and native tooltips are enabled (`x-gtk-use-system-tooltips` is `t`) tooltips are shown as ordinary windows despite the GTK theme: squared and  non-transparent. This doesn't happen in gnome and cinnamon, at least. Also, in i3 other apps (for instance, firefox) correctly show tooltips.

I've dealt with emacs tooltip code in the past (but I barely remember the details) and it does the following trick: after the tooltip is created they store it as part of the containing frame and reuse it each time a tooltip is requested for the containing frame. Maybe the window type is not exactly the same as that of a honest tooltip because of this manipulation. But nevertheless, as I've said, other window managers (mutter, muffin... well they're almost the same) correctly identifies the window type. Also, compton recognizes the window as a tooltip (for example, I'm able to change its opacity by setting a `tooltips {...}` rule).

So this is clearly the result of some peculiarities of both i3 and emacs but it could be pointing out a corner case that i3 is not correctly coping with.
 
## Expected Behavior

Tooltips honour the GTK theme and look the same they do in every other app.

## Reproduction Instructions

Install emacs in a linux environment (most probably it will be compiled with gtk3 support this days), press `M-:` and eval `(setq x-gtk-use-system-tooltips t)` then move the mouse over the modeline to open a tooltip.

## Environment

Output of `i3 --moreversion 2>&-`:

<pre>
Binary i3 version:  4.15 (2018-03-10) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15 (2018-03-10) (pid 11418) abort…)
Loaded i3 config: /home/carlos/.config/i3/config (Last modified: Tue 24 Jul 2018 03:58:40 PM -03, 459 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

Configuration file:

<pre>
# General settings
set $mod Mod4
floating_modifier $mod
font pango:DejaVu Sans Bold 10
default_border normal 1
hide_edge_borders both
workspace_auto_back_and_forth yes
set $nexec exec --no-startup-id

# Theme
set $bg #13191c
set $border #101619
set $fg #83898c
set $fg_high #cfd7d3
set $fg_urg #cc6666
#                       Border  Background Text     Indicator Child border
client.focused          $border $bg        $fg_high $fg       $border
client.focused_inactive $border $bg        $fg      $fg       $border
client.unfocused        $border $bg        $fg      $fg       $border
client.urgent           $border $bg        $fg_urg  $fg       $border
client.placeholder      $border $bg        $fg      $fg       $border
client.background       $border

# App shortcuts
bindsym $mod+l $nexec emacsclient -c
bindsym $mod+Control+l exec xfce4-terminal
bindsym $mod+Shift+l exec firefox
bindsym $mod+Mod1+l exec spotify
bindsym $mod+Tab $nexec rofi -no-fixed-num-lines -location 7 -show window -yoffset -25
bindsym $mod+Return $nexec "rofi -location 7 -combi-modi drun,run -show combi -yoffset -25"
bindsym $mod+Control+Return $nexec music toggle
bindsym $mod+Shift+Return $nexec music mute
bindsym $mod+Mod1+Return $nexec dual
bindsym $mod+Shift+Control+Return $nexec passmenu
bindsym $mod+Left $nexec music prev
bindsym $mod+Right $nexec music next
bindsym $mod+Down $nexec music down
bindsym $mod+Up $nexec music up
bindsym $mod+Shift+Down $nexec xbacklight -dec 2
bindsym $mod+Shift+Up $nexec xbacklight -inc 2
bindsym $mod+s $nexec search $(xclip -o)
bindsym $mod+Control+s $nexec search -r
bindsym $mod+o $nexec shot %c
bindsym $mod+Control+o $nexec shot %d
bindsym $mod+Shift+o $nexec shot %c 5
bindsym $mod+Mod1+o $nexec shot %d 5

# Change focus
bindsym $mod+b focus left
bindsym $mod+n focus down
bindsym $mod+Shift+Control+n focus child
bindsym $mod+p focus up
bindsym $mod+Shift+Control+p focus parent
bindsym $mod+f focus right
bindsym $mod+grave focus right

# Change layout
bindsym $mod+w layout splith
bindsym $mod+Control+w layout splitv
bindsym $mod+a layout tabbed
bindsym $mod+Control+a layout stacking
bindsym $mod+d split h
bindsym $mod+Control+d split v
bindsym $mod+m fullscreen toggle
bindsym $mod+Control+m border toggle
bindsym $mod+space focus mode_toggle
bindsym $mod+Control+space floating toggle

# Move window
bindsym $mod+Control+b move left
bindsym $mod+Control+n move down
bindsym $mod+Control+p move up
bindsym $mod+Control+f move right
bindsym $mod+Control+1 move container to workspace 1
bindsym $mod+Control+2 move container to workspace 2
bindsym $mod+Control+3 move container to workspace 3
bindsym $mod+Control+4 move container to workspace 4
bindsym $mod+Control+5 move container to workspace 5
bindsym $mod+Control+6 move container to workspace 6
bindsym $mod+Control+7 move container to workspace 7
bindsym $mod+Control+8 move container to workspace 8
bindsym $mod+Control+9 move container to workspace 9
bindsym $mod+Control+0 move container to workspace 10

# Resize window
bindsym $mod+Control+Left resize shrink width 10 px or 5 ppt
bindsym $mod+Control+Up resize grow height 10 px or 5 ppt
bindsym $mod+Control+Down resize shrink height 10 px or 5 ppt
bindsym $mod+Control+Right resize grow width 10 px or 5 ppt

# Switch to workspace
bindsym $mod+1 workspace 1
bindsym $mod+2 workspace 2
bindsym $mod+3 workspace 3
bindsym $mod+4 workspace 4
bindsym $mod+5 workspace 5
bindsym $mod+6 workspace 6
bindsym $mod+7 workspace 7
bindsym $mod+8 workspace 8
bindsym $mod+9 workspace 9
bindsym $mod+0 workspace 10

# Move workspace
bindsym $mod+Shift+1 rename workspace to 1
bindsym $mod+Shift+2 rename workspace to 2
bindsym $mod+Shift+3 rename workspace to 3
bindsym $mod+Shift+4 rename workspace to 4
bindsym $mod+Shift+5 rename workspace to 5
bindsym $mod+Shift+6 rename workspace to 6
bindsym $mod+Shift+7 rename workspace to 7
bindsym $mod+Shift+8 rename workspace to 8
bindsym $mod+Shift+9 rename workspace to 9
bindsym $mod+Shift+0 rename workspace to 10
bindsym $mod+Mod1+p move workspace to output up
bindsym $mod+Mod1+n move workspace to output down
bindsym $mod+Mod1+f move workspace to output right
bindsym $mod+Mod1+b move workspace to output left

# Marks
bindsym $mod+Control+F1 mark --toggle 1
bindsym $mod+F1 [con_mark=1] focus
bindsym $mod+Control+F2 mark --toggle 2
bindsym $mod+F2 [con_mark=2] focus
bindsym $mod+Control+x mark --toggle x
bindsym $mod+Shift+x move window to mark x, unmark x
bindsym $mod+x swap container with mark x, unmark x

# Scratchpad
bindsym $mod+z scratchpad show
bindsym $mod+Control+z floating enable, move scratchpad
bindsym $mod+Shift+z scratchpad show, scratchpad show
bindsym $mod+e [title="^Scratchpad - Emacs"] scratchpad show
bindsym $mod+Control+e [title="^Scratchpad - Terminal$"] scratchpad show
bindsym $mod+Shift+e [title="(Gmail|Slack|WhatsApp)"] focus
bindsym $mod+Mod1+e [class="^Spotify$"] scratchpad show
bindsym $mod+Shift+Control+e $nexec emacsclient -F '((title . "Scratchpad - Emacs"))' -a '' -c ~/notes/inbox.org
bindsym $mod+Shift+Control+Mod1+e exec xfce4-terminal --title 'Scratchpad - Terminal'

# Control
bindsym $mod+r exec i3-input
bindsym $mod+Control+r reload
bindsym $mod+Shift+r restart
bindsym $mod+Shift+Control+r exit
bindsym $mod+c exec i3lock -c 1d1f21
bindsym $mod+Control+c exec systemctl sleep
bindsym $mod+Shift+c exec systemctl hibernate
bindsym $mod+Shift+Control+c exec systemctl poweroff
bindsym $mod+Control+q kill

# Rules
for_window [class="^Pavucontrol$"] floating enable
for_window [class="^qpaeq$"] floating enable
for_window [class="^Gpick$"] floating enable
for_window [class="^Connman-gtk$"] floating enable
for_window [class="^Xmag$"] floating enable
for_window [class="^Spotify$"] floating enable, resize set 1000 700, move position center
for_window [title="^Htop$"] floating enable
for_window [title="^Scratchpad - Terminal$"] floating enable, move scratchpad
for_window [title="^Scratchpad - Emacs$"] floating enable, move scratchpad

# Startup
$nexec emacsclient -F '((title . "Scratchpad - Emacs"))' -a '' -c ~/notes/inbox.org
$nexec xfce4-terminal --title 'Scratchpad - Terminal'
</pre>

<pre>
- Linux Distribution & Version: Linux archlinux 4.17.8-1-ARCH #1 SMP PREEMPT Wed Jul 18 09:56:24 UTC 2018 x86_64 GNU/Linux
- Are you using a compositor: compton
</pre>

**Comment by memeplex** [comment] 2018-07-26 17:48
Ok, I will try to be clearer. Let's consider these four combinations: i3/mutter x firefox/emacs. And let's say my gtk3 theme specifies rounded, transparent tooltips. Also, emacs is in each case configured for system (gtk3) tooltips.

1. i3, firefox: tooltips are as defined by the gtk3 theme.
2. i3, emacs: tooltips  are opaque and squared.
3. mutter, firefox: tooltips are as defined by the gtk3 theme.
4. mutter, emacs: tooltips are as defined by the gtk3 theme.

Now, this implies that it's neither an inherent limitation of i3 nor of emacs to show tooltips as specified by the gtk3 theme. What I think is happening is:

1. As you said, i3 doesn't support shaped windows nor transparencies and it's somehow managing these tooltips for emacs but not for firefox.

2. Emacs has a very peculiar way of dealing with tooltips: one is created for each emacs top level window (what is called a "frame" in emacs jargon) and then is stored and made visible/hidden as needed.

I don't know why i3 is leaving other tooltips alone but managing emacs' ones instead. Maybe the way emacs is manipulating the tooltip sets or unsets some client properties that makes i3 believe it's another type of window.

**Comment by Airblader** [comment] 2018-07-27 07:29
Tooltips, generally speaking, are likely to be override_redirect windows, which causes the window manager to not manage those windows. If a client creates a tooltip without override_redirect, the window manager will (have to) manage it, and does so in the way it seems fit.

Can you run a `xwininfo -all` on one of those tooltips that appear like regular windows? Maybe also a `xprop`.

**Comment by memeplex** [comment] 2018-07-28 02:21
Well, it wasn't simple to get the info for those shy tooltips but with the right amount of dirtiness everything becomes possible:

# Emacs is using it own tooltips (non gtk):

```
~::  xwininfo -root -tree  > /tmp/no-tt

~:: xwininfo -all -id $(sleep 4; xwininfo -root -tree  > /tmp/yes-tt; diff /tmp/no-tt /tmp/yes-tt | tail -1 | sed -re 's/[^0]*([x0-9a-f]+).*/\1/')

xwininfo: Window id: 0x800f99 (has no name)

  Root window id: 0xf4 (the root window) "i3"
  Parent window id: 0xf4 (the root window) "i3"
     0 children.

  Absolute upper-left X:  959
  Absolute upper-left Y:  677
  Relative upper-left X:  959
  Relative upper-left Y:  677
  Width: 315
  Height: 44
  Depth: 24
  Visual: 0x20
  Visual Class: TrueColor
  Border width: 1
  Class: InputOutput
  Colormap: 0x22 (installed)
  Bit Gravity State: ForgetGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: yes
  Corners:  +959+677  -90+677  -90-45  +959-45
  -geometry 315x44-90-45

  Bit gravity: ForgetGravity
  Window gravity: NorthWestGravity
  Backing-store hint: NotUseful
  Backing-planes to be preserved: 0xffffffff
  Backing pixel: 0
  Save-unders: No

  Someone wants these events:
      StructureNotify
  Do not propagate these events:
  Override redirection?: Yes

  No window manager hints defined
  Window manager hints:
      Window type:
          Tooltip
      Process id: (unknown)

  No normal window size hints defined
  No zoom window size hints defined

  No window shape defined
  No border shape defined

~:: xprop -id $(sleep 4; xwininfo -root -tree  > /tmp/yes-tt; diff /tmp/no-tt /tmp/yes-tt | tail -1 | sed -re 's/[^0]*([x0-9a-f]+).*/\1/')

_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_TOOLTIP
```

# Emacs is using gtk tooltips

```
~:: xwininfo -id $(sleep 4; xwininfo -root -tree  > /tmp/yes-tt; diff /tmp/no-tt /tmp/yes-tt | tail -1 | sed -re 's/[^0]*([x0-9a-f]+).*/\1/')

xwininfo: Window id: 0x8001ad (has no name)

  Absolute upper-left X:  953
  Absolute upper-left Y:  403
  Relative upper-left X:  -1
  Relative upper-left Y:  -1
  Width: 1
  Height: 1
  Depth: 0
  Visual: 0xbf
  Visual Class: TrueColor
  Border width: 0
  Class: InputOnly
  Colormap: 0x0 (not installed)
  Bit Gravity State: ForgetGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +953+403  -412+403  -412-364  +953-364
  -geometry 1x1-33+404
```

Two observations:

1. In the gtk tooltip case no new window appears after the diff, but the tooltip window geometry changes. This is what I was saying about reusing the tooltip.

2. In the gtk tooltip case xprop returns nothing.

Maybe this should be reported to emacs bug tracker so that they correctly set the window type.

**Comment by memeplex** [comment] 2018-07-28 12:14
Well, it wasn't simple to get the info for those shy tooltips but with the right amount of dirtiness everything becomes possible:

# Emacs is using it own tooltips (non gtk):

```
~::  xwininfo -root -tree  > /tmp/no-tt

~:: xwininfo -all -id $(sleep 4; xwininfo -root -tree  > /tmp/yes-tt; diff /tmp/no-tt /tmp/yes-tt | tail -1 | sed -re 's/[^0]*([x0-9a-f]+).*/\1/')

xwininfo: Window id: 0x800f99 (has no name)

  Root window id: 0xf4 (the root window) "i3"
  Parent window id: 0xf4 (the root window) "i3"
     0 children.

  Absolute upper-left X:  959
  Absolute upper-left Y:  677
  Relative upper-left X:  959
  Relative upper-left Y:  677
  Width: 315
  Height: 44
  Depth: 24
  Visual: 0x20
  Visual Class: TrueColor
  Border width: 1
  Class: InputOutput
  Colormap: 0x22 (installed)
  Bit Gravity State: ForgetGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: yes
  Corners:  +959+677  -90+677  -90-45  +959-45
  -geometry 315x44-90-45

  Bit gravity: ForgetGravity
  Window gravity: NorthWestGravity
  Backing-store hint: NotUseful
  Backing-planes to be preserved: 0xffffffff
  Backing pixel: 0
  Save-unders: No

  Someone wants these events:
      StructureNotify
  Do not propagate these events:
  Override redirection?: Yes

  No window manager hints defined
  Window manager hints:
      Window type:
          Tooltip
      Process id: (unknown)

  No normal window size hints defined
  No zoom window size hints defined

  No window shape defined
  No border shape defined

~:: xprop -id $(sleep 4; xwininfo -root -tree  > /tmp/yes-tt; diff /tmp/no-tt /tmp/yes-tt | tail -1 | sed -re 's/[^0]*([x0-9a-f]+).*/\1/')

_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_TOOLTIP
```

# Emacs is using gtk tooltips

```
~:: xwininfo -id $(sleep 4; xwininfo -root -tree  > /tmp/yes-tt; diff /tmp/no-tt /tmp/yes-tt | tail -1 | sed -re 's/[^0]*([x0-9a-f]+).*/\1/')

xwininfo: Window id: 0x8001ad (has no name)

  Absolute upper-left X:  953
  Absolute upper-left Y:  403
  Relative upper-left X:  -1
  Relative upper-left Y:  -1
  Width: 1
  Height: 1
  Depth: 0
  Visual: 0xbf
  Visual Class: TrueColor
  Border width: 0
  Class: InputOnly
  Colormap: 0x0 (not installed)
  Bit Gravity State: ForgetGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +953+403  -412+403  -412-364  +953-364
  -geometry 1x1-33+404
```

Two observations:

1. In the gtk tooltip case no new window appears after the diff, but the tooltip window geometry changes. This is what I was saying about reusing the tooltip.

2. In the gtk tooltip case xprop returns nothing.

Maybe this should be reported to emacs bug tracker so that they correctly set the window type.

**Comment by Airblader** [comment] 2018-08-01 09:14
As suspected, the Emacs GTK tooltips are not override-redirect, which is unusual for tooltips. In any case, this means i3 is being asked to manage the window, which we do.

Please report this to emacs. Feel free to link here! I'll close this as working as intended.

**Closed by Airblader** 2018-08-01 09:14 UTC
Labels: 4.15, bug

**Comment by memeplex** [comment] 2018-08-03 22:22
Interesting enough, doing the same experiment for firefox tooltips also shows a non override redirected window for the tooltip... I will report any news from the emacs front.
