### ISSUE TITLE
i3 crashes/becomes unresponsive sometimes during dock/undock

### ISSUE THREAD

**Issue by Corni** [i3/i3#2424] opened 2016-08-15 21:56 UTC
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.12-85-g012de8c (2016-08-03, branch "next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.12-85-g012de8c (2016-08-03, branch "next") (pid 27381)
Loaded i3 config: /home/corni/.i3/config (Last modified: Mon 15 Aug 2016 12:43:44 PM CEST, 39762 seconds ago)

The i3 binary you just called: /home/corni/build/i3/i3
The i3 binary you are running: /home/corni/build/i3/i3

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5689127638925312.bz2

**What I did:**

Sometimes when docking or undocking my Thinkpad T440s from the dock, i3 hangs.
The windows are still there, I can move my mouse pointer, sound still plays, but I can't interact with anything anymore.
I feel that this happens more often after running i3 for a longer time. I wanted to file this bug report and was unable to reproduce the issue with a freshly started i3 with docking/undocking like 10 times, but after coming home after using i3 for some time and docking in, the problem occurs the first try. 
According to the log, i3 crashed, but the process is still alive (at least I think it is the same process), and a gdb backtrace can be found here:
http://pastebin.com/2JYHPBKd

My screen configuration:
undocked - internal (eDP1, 1920x1080)
docked: internal off, external DP2-1 2560x1440, external DP2-2 1920x1200.
If relevant: I *think* that the docking station uses a Displayport MST chip, which (formerly?) caused some issues with the linux kernel.
On dock/undock I run the following script via udev
http://pastebin.com/d3mcK7Tz
The i3-restart here is needed to get i3bar to render the tray icons.

After the issue occured, I can't use i3-msg anymore, as i3 already hangs in the poll syscall, so I doubt that the restart in the script gets executed anyways.

If there is anything I can do to assist debugging this issue, I'm glad to help. This is really annoying, as I nondeterministically lose all open applications during dock/undock.

Edit: Ahhh, just saw: The black box which appears then is the crash dialog from #2422, so i3 has, in fact crashed - then I do not know from which process the gdb backtrace is.

**Comment by Airblader** [comment] 2016-08-16 04:55
The backtrace shows that this is a duplicate of #2252

**Closed by Airblader** 2016-08-16 04:55 UTC
Labels: 4.12
