### ISSUE TITLE
Feature Request: Enabling Capture from other workspaces with OBS

### ISSUE THREAD

**Issue by zenny** [i3/i3#1925] opened 2015-09-15 22:09 UTC
Please make it possible to capture the windows open in other workspaces than in the one where obs (obsproject.com) is running.

The discussion is here:
http://infra.in.zekjur.net/archives/i3-discuss/2015-September/002197.html

Thank you.

NB: Posting this feature request as Michael advised to.

**Comment by stapelberg** [comment] 2015-09-16 17:37
@zenny, to make this more appealing for volunteers to pick up, can you provide the steps to reproduce? I.e. if I’ve never used OBS before, help me understand what to do in order to see what you’d like fixed.

**Comment by zenny** [comment] 2015-10-04 06:07
Sorry for delay. To reproduce.

1) Start OBS (say in workspace 3)
2) Add a Windows Xcomposite as a source to any scene
3) Under the drop-down list of that specific source, choose any apps that is running in the workspace (say workspace 1) other than from where you launched OBS (workspace 3 as above §1).
4) You will get a just get red blank image in the placeholder for the source. However, any other applications that is running withing the workspace running OBS (in this example workspace 3) works perfect.

Hope this helps.

**Comment by ccryx** [comment] 2015-12-08 15:38
I tried to reproduce this issue with obs-studio-0.12.3 from the AUR. I also experience the redscreen with windows that are currently not visible but as soon as they become visible (or if I add the source while they are visible) OBS dies. This happens in awesome, openbox and i3 both with and without compton running. So I guess this is an obs bug rather than an i3 bug.

**Comment by Airblader** [comment] 2015-12-08 19:09
The link provided in the original i3 mailing list thread actually received a comment between the mail thread and opening of this issue which describes both the reason and a workaround[1]. Also see [2].

I very much doubt we are going to change the entire foundation the i3 workspace concept is based on (which is unmapping windows on invisible workspaces and not rendering those workspaces); @stapelberg correct me if I'm wrong. Hence I don't think we can do anything about this and I'll close this ticket.

[1] https://obsproject.com/forum/threads/workspace-screen-capture-issues-ubuntu-gnome-14-04.35811/#post-165955
[2] https://obsproject.com/forum/threads/red-screen-when-using-xcomposite.18522/

**Closed by Airblader** 2015-12-08 19:09 UTC
Labels: enhancement

**Comment by stapelberg** [comment] 2015-12-10 08:30
Correct, having workspaces map/unmap windows is the standard way of implementing workspaces, and we won’t diverge from that.

**Comment by squigglezworth** [comment] 2023-04-17 14:59
Have attitudes changed regarding this? Streaming is becoming more and more important, and it would be great if i3 could support it... 

If not, does anyone know of any workarounds that still work these days? The one linked above does not seem to for me.

**Comment by stapelberg** [comment] 2023-04-17 15:17
OBS screen capture works just fine with i3.

What doesn’t work is capturing workspaces that are not currently visible.

I don’t know how that could be fixed. If there was a possible fix, I don’t mind discussing it over a PR.

There’s not so much an attitude/opinion blocker here, but rather a technical obstacle.

**Comment by squigglezworth** [comment] 2023-04-29 14:49
Sorry - bad choice of words. I should have said 'circumstances'. Could you elaborate a bit more on the technical obstacle(s)?

**Comment by stapelberg** [comment] 2023-04-29 14:59
See comment https://github.com/i3/i3/issues/1925#issuecomment-163532657 from 2015: All X11 window managers I know of implement workspaces by mapping/unmapping windows (which is X11 terminology for making a window visible/invisible). This is something we cannot change.

AFAIU, OBS does not capture unmapped windows. 

So, I don’t see what could be done to make this work. Maybe we’re missing something, but I don’t know what it is.

**Comment by Jaywalker** [comment] 2023-12-28 00:22
@stapelberg Not that I have a dog in this fight; I was just researching this for a friend who uses i3... This is how bspwm solves the problem, though its not in the mainline branch. I use the patch from this branch and it works fine for me. Maybe its doable in i3 too - https://github.com/baskerville/bspwm/tree/hide_by_moving

**Comment by stapelberg** [comment] 2023-12-28 12:38
Thanks for the link. I’m somewhat surprised that this seems to work in practice (if it does). I would expect that some applications make assumptions based on the mapped/unmapped state of windows. Also, there might be a difference in X11 resource usage.

In either case, this is too weird a departure from how X11 operates, so I don’t think we’d want to merge the move-instead-of-unmap approach into i3.

**Comment by Jaywalker** [comment] 2023-12-28 19:14
Yep, absolutely. Just wanted to confirm that it does indeed work in practice. I use it regularly on my system and have never had any issues. That doesn't mean that you're wrong and that some applications may have issues, but none of the ones I have used seem to have complained.

**Comment by squigglezworth** [comment] 2023-12-28 19:38
Just for what it's worth, I'd personally be willing to use a hack like this if it meant achieving the original request. I realize such a hack would never be merged into the master branch, but if someone made a patch, that would be greatly appreciated :)

I'd do it myself, but, well.. this is far outside my wheelhouse :P

Either way, I appreciate you taking the time to look at the other approach, @stapelberg. Happy holidays 🎄
