### ISSUE TITLE
Incorrect error handling on 'set' and 'set_from_resource' config statements

### ISSUE THREAD

**Issue by kneitinger** [i3/i3#2390] opened 2016-06-30 17:59 UTC
Output of `i3 --moreversion 2>&- || i3 --version`:

```
Binary i3 version:  4.12 (2016-03-06, branch "4.12") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.12-76-g3ffa88e (2016-06-25, branch "next") (pid 24623)
Loaded i3 config: /home/leaf/.i3/config (Last modified: Thu 30 Jun 2016 10:24:23 AM PDT, 283 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: /home/leaf/Programming/i3/i3
```

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5697124062724096.bz2

**What I did:**

I placed the following lines inside of my configuration file:

```
set $foo
set $
set_from_resource $bar
set_from_resource
bindsym Mod4+1 exec echo $foo >> /home/leaf/i3vartest
bindsym Mod4+2 exec echo $bar >> /home/leaf/i3vartest
```

Then I started i3 with that configuration file, and pressed Mod4+1, then Mod4+2

**What I saw:**

```
% cat i3vartest 
8: Slack

%
```

(note: "8: Slack" is the value of the last variable defined before $foo)

```
% ./i3 -C -c ~/.i3/config
% 
```

**What I expected instead:**

I was able to fix it by changing the `scr/config_parser.c` lines:

```
        if (strcasecmp(key, "set") == 0) {
            char v_key[512];
            char v_value[4096];

            if (sscanf(value, "%511s %4095[^\n]", v_key, v_value) < 1) {
                ELOG("Failed to parse variable specification '%s', skipping it.\n", value);
                continue;
            }
```

to:

```
        if (strcasecmp(key, "set") == 0) {
            char v_key[512];
            char v_value[4096];

            if (sscanf(value, "%511s %4095[^\n]", v_key, v_value) < 2) {
                ELOG("Failed to parse variable specification '%s', skipping it.\n", value);
                continue;
            }
```

and the same for set_from_resource, but with 3 as the desired sscanf return value.

This gave me the output:

```
% ./i3 -C -c ~/.i3/config
06/30/2016 10:48:35 AM - ERROR: Failed to parse variable specification '$foo', skipping it.
06/30/2016 10:48:35 AM - ERROR: Failed to parse variable specification '$', skipping it.
06/30/2016 10:48:35 AM - ERROR: Failed to parse resource specification '$bar', skipping it.
06/30/2016 10:48:35 AM - ERROR: Failed to parse resource specification '$bar', skipping it.
```

**Considerations:**
While all of those set/set_from_resource attempts threw errors, they weren't necessarily correct, the 4th on was not called '$bar', but sscanf did not overwrite the string holding the variable's key, it used the one from the previous line.  While it still fails, it could be a better described error.  Additionally, simply checking the number of arguments to set/set_from_resource, and verifying that the first one starts with '$' allows a user to have a variable whose key is literally '$'.  Because of my commit #2306 , this is actually harmless, and works fine, but is it desired??

Thank you!

**Comment by kneitinger** [comment] 2016-06-30 18:04
Also, I would be happy to submit the fix and tests once the bug is verified and the acceptance criteria is established.

**Comment by Airblader** [comment] 2016-06-30 21:04
Makes sense to me.

**Comment by Airblader** [comment] 2016-07-01 13:50
Just to clarify, I meant it makes sense what you're saying and we should fix it :)

**Comment by kneitinger** [comment] 2016-07-02 00:36
Great! The more I think about it, I feel that '$' should certainly not be a valid variable key. 

I haven't tested it, but I bet it causes issues with lines like
`bindsym Mod2+c notify-send $(date)`

Even if that line somehow parses correctly, it just seems like this is very likely to cause a regression at some point.

Agreed?

**Comment by Airblader** [comment] 2016-07-02 07:45
Yes, zero length variable names certainly don't sound sensible and should be ignored. :)

**Comment by kneitinger** [comment] 2016-07-09 10:26
I'm working on the test cases and they're a bit tricky, but they brought up the question of whether or not we actually want invalid `set` statements to be passively ignored and logged as they currently are, or if parsing should fail completely with error output like any other failed directive.

Because variable parsing doesn't actually print error messages with the nagbar (only with `i3 -C`), one typo could really trip up a user whose config loaded but is acting very strangely.

**Comment by stapelberg** [comment] 2016-07-11 07:29
Invalid statements should in general result in an error message that is visible to the user.

**Comment by ael-code** [comment] 2016-11-13 13:37
```
Binary i3 version:  4.12 (2016-03-06, branch "4.12") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.12 (2016-03-06, branch "4.12") (pid 2079)
Loaded i3 config: ~/.config/i3/config (Last modified: Sun 13 Nov 2016 02:11:53 PM CET, 398 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3-with-/i3
```

I'm getting crazy, I've inserted the following line in my i3 config file
` set_from_resource $black i3wm.color0 #000000`
But the variable is empty. Thus I've tried without the default
` set_from_resource $black i3wm.color0`
then with:
` set_from_resource $black`
and finally with:
` set_from_resource`

In all the above case the variable is empty and there is no error or further information in the log.

Am I missing something?

**Comment by Airblader** [comment] 2016-11-13 18:33
> Am I missing something?

Yes, the fact that `set_from_resource` has been introduced with 4.13 and not 4.12. :-)

**Comment by ael-code** [comment] 2016-11-13 18:59
I was confused by a couple of things:
- This is an open issue and one of the label says `4.12`
- No error in the log even if I was using an unsupported config statement
- The official user guide says nothing about the version is documenting

I'll open an issue about the user guide (3rd), but how can you explain the second one? I mean I don't think that is normal not raising any error if there is an unsupported statement in the config file.

**Comment by Airblader** [comment] 2016-11-13 19:03
> This is an open issue and one of the label says 4.12

The label defines when the issue was opened. Some people (luckily) run the development branch before the release to give us feedback. Admittedly we should perhaps keep an eye on labelling them appropriately, though.

> No error in the log even if I was using an unsupported config statement

I assume that happens because the parser might read it as `set _from_resource …`, which wouldn't be ideal. Just a guess, though. There definitely should be an error displayed (also when running `i3 -C`). Feel free to open a ticket for that.

> The official user guide says nothing about the version is documenting

Our guide always refers to the current release version which we strongly recommend everybody updates to. We don't have versioned userguides on the website. If you want the userguide of an old version, just build the documentation from that tag.

**Comment by stapelberg** [comment] 2016-11-13 19:07
> We don't have versioned userguides on the website.

Actually, we do: https://i3wm.org/docs/4.12/userguide.html

I agree that we could do a better job at documenting what features went in at which version, and which version a userguide is documenting. Pull requests welcome.

**Comment by Airblader** [comment] 2016-11-13 19:10
You never stop learning. :-)

**Comment by kneitinger** [comment] 2016-11-14 03:54
Sorry folks, life got the best of me on this patch!  I feel bad for sitting on this issue for so long, I have a fix, but if I remember correctly, I had a lot of difficulty writing test cases that check this. How would you recommend moving forward? Would the IRC channel be a good place to ask for help with the tests?

**Comment by stapelberg** [comment] 2017-08-20 11:18
Marking this as a duplicate of issue #2564, which I just fixed.

**Closed by stapelberg** 2017-08-20 11:18 UTC
Labels: 4.13, bug, reproducible
