### ISSUE TITLE
i3 fail to load workspace definition when top container have marks parameter

### ISSUE THREAD

**Issue by serg-kozhemyakin** [i3/i3#2607] opened 2016-12-14 13:48 UTC
Binary i3 version:  4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13 (2016-11-08) (pid 10272) abort…)

http://logs.i3wm.org/logs/5682462386552832.bz2

trying to load workspace definition with marks set for containers. i3 config:
exec --no-startup-id "i3-msg 'workspace 0; append_layout ~/.config/i3/tmp/ws0.json'"

ws0.json:
{
    "layout": "splith",
    "percent": 1,
    "type": "con",
    "nodes": [
        {
            "marks": ["Rosters"],
            "layout": "tabbed",
            "percent": 0.15,
            "type": "con",
            "nodes": [
                {"name": "Skype", "swallows": [{ "class": "^Skype\\-bin$", "title": "Skype. \\d\\.\\d for Linux" }] },
                {"name": "Pidgin", "swallows": [{ "class": "^Pidgin$", "window_role": "^buddy_list$" }] }
            ]
        },
        {
            "layout": "splitv",
            "percent": 0.85,
            "type": "con",
            "nodes": [
                {
                    "layout": "tabbed",
                    "percent": 0.5,
                    "marks": ["Chats"],
                    "type": "con"
                }
            ]
        }
    ]
}

**Comment by Airblader** [comment] 2016-12-14 18:40
Duplicate of #2511

**Closed by Airblader** 2016-12-14 18:40 UTC
Labels: 4.13, bug
