### ISSUE TITLE
Switching outputs results in mouse jumps

### ISSUE THREAD

**Issue by thraizz** [i3/i3#4130] opened 2020-06-15 16:50 UTC
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Let there be two outputs, DP-1 and DP-2.
After switching from DP-1 to DP-2 e.g. with `i3-msg workspace <workspace-on-DP-2>` or with `i3-msg focus output DP-2` the mouse jumps back to the upper left corner of DP-1 when trying to move the cursor. If I switch from DP-2 to DP-1, the mouse jumps to the upper corner of DP-1 as well.

## Expected Behavior
The mouse should remain on the focused workspace and not jump back to the last output.

## Reproduction Instructions
Switch from one workspace to another on a different output and move the mouse.

### Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.18.1 (2020-04-22) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.18.1 (2020-04-22) (pid 27779)bort…)
Loaded i3 config: /home/arons/.config/i3/config (Last modified: Mo 15 Jun 2020 18:00:27 CEST, 2182 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

### i3 config
<pre>
set $mod Mod4
exec --no-startup-id picom

# start a terminal
bindsym $mod+Return exec xfce4-terminal

bindsym $mod+Shift+r restart
bindsym $mod+Shift+q kill

bindsym $mod+F2 focus output DP-1
bindsym $mod+F1 focus output DP-5

# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"

</pre>

### Logfile
<pre>
Logfile URL: https://logs.i3wm.org/logs/5646761133604864.bz2
</pre>

<pre>
- Linux Distribution & Version:
OS: Manjaro Linux x86_64
Kernel: 5.4.43-1-MANJARO

- Are you using a compositor (e.g., xcompmgr or compton):
Yes, picom:
$ picom --version
vgit-e553e
</pre>

**Comment by orestisfl** [comment] 2020-06-15 17:26
Can you try without picom?

**Comment by orestisfl** [comment] 2020-06-15 17:32
And, if you have the time, can you also try with https://github.com/i3/i3/pull/3545 please?

**Comment by thraizz** [comment] 2020-06-15 18:02
Sure, will try both and report back.

**Comment by thraizz** [comment] 2020-06-15 18:26
The behavior is not affected by picom, however, #3545 fixes it! Reinstalling i3 brings the bug bag.

edit: Building i3 from `i3/next` doesn't resolve the issue.
edit2: I am pretty sure that this is a duplicate of #3598 - I use a coordinate transformation matrix to set my mouse speed. When setting `xinput set-float-prop "2.4G Mouse" "Coordinate Transformation Matrix" 1 0 0 0 1 0 0 0 1` (matrix was `0.25 0 0 0 0.25 0 0 0 1`) the bug disappears.

**Comment by orestisfl** [comment] 2020-06-15 19:07
Yes, I agree that this is a duplicate of #3598, that's why I asked about that PR.

Thank you very much for your time and confirmation.

**Closed as completed by orestisfl** 2020-06-15 19:07 UTC
Labels: bug, 4.18
