### ISSUE TITLE
Allow match on WM_CLIENT_MACHINE

### ISSUE THREAD

**Issue by T4cC0re** [i3/i3#4126] opened 2020-06-11 11:32 UTC
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

i3 does not allow to match on the `WM_CLIENT_MACHINE` attribute.

## Desired Behavior

i3 does allow to match on the `WM_CLIENT_MACHINE` attribute. This is desirable when having X11 forwarding to another machine. I want to be able to distinguish windows of the same class and instance based on the machine they're coming from.

If I am given some pointers I think I would be able to provide a patch for this.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.18.1 (2020-04-23) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.18.1 (2020-04-23) (pid 1538)abort…)
Loaded i3 config: /home/t4cc0re/.config/i3/config (Last modified: Tue 09 Jun 2020 02:21:42 AM CEST, 212982 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
- Linux Distribution & Version: Arch Linux
- Are you using a compositor (e.g., xcompmgr or compton): No
</pre>

**Comment by orestisfl** [comment] 2020-06-11 11:39
Duplicate of https://github.com/i3/i3/issues/3981

**Closed as completed by orestisfl** 2020-06-11 11:39 UTC
Labels: enhancement

**Comment by T4cC0re** [comment] 2020-06-11 11:41
Sorry for the noise, I did search for WM_CLIENT_MACHINE and nothing popped up.

**Comment by orestisfl** [comment] 2020-06-11 11:42
No worries :)
