### ISSUE TITLE
Reload and restart do not make some keybindings start working

### ISSUE THREAD

**Issue by Hi-Angel** [i3/i3#5968] opened 2024-03-29 06:06 UTC
### Welcome

- [X] Yes, I'm using the latest major release or the current development version. These are the only supported versions.
- [X] Yes, I've searched similar issues and discussions on GitHub and didn't find any.

### Current Behavior

Pressing the hotkey does nothing

### Expected Behavior

Pressing hotkey would do the action bound to it

### Reproduction Instructions

It is a known old problem that [i3 sometimes loses keybindings](https://github.com/i3/i3/issues/2753) due to some odd interaction with KDE.

A larger *(and also old)* problem though is that i3 does not restore them upon reload/restart and it's unclear why.

The log attached is for me pressing `Mod4 + 3` which does nothing at all. In the config you can also see a duplicate `ctrl+Mod4+3` entry, this one was added by me to make sure I can switch to the workspace for the duration of writing this report. So the action per se works, it's just that the keybinding somehow gets ignored by i3.

# Steps to reproduce

1. Wait for [keybindings loss](https://github.com/i3/i3/issues/2753) to reproduce
2. Execute `restart` or `reload` i3 command
3. Press the keybinding that got lost

### i3 version

```text
Binary i3 version:  4.23 (2023-10-29) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.23 (2023-10-29) (pid 5171)
Loaded i3 config:
  /home/constantine/.config/i3/config (main) (last modified: Пт 29 мар 2024 08:39:51, 1131 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: /usr/bin/i3
```

### Config file

```text
# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout some time, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see http://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod4

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:Hack, FontAwesome 9
#font pango:Monospace, FontAwesome5Brands, FontAwesome5Free 9
#font pango:Monospace, Font Awesome 5 Free Solid 9

# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
#font pango:DejaVu Sans Mono 8

set $black        #282828
set $darkblack    #1d2021
set $darkwhite    #ffffff
set $whitesmoke   #f5f5f5
set $skyblue      #3399ff
set $green        #42b879
set $darkred      #8b0000
set $darkgray     #414141
set $lightgray    #D3D3D3
set $transparent  #000000E5

# Before i3 v4.8, we used to recommend this one as the default:
# font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
# The font above is very space-efficient, that is, it looks good, sharp and
# clear in small sizes. However, its unicode glyph coverage is limited, the old
# X core fonts rendering does not support right-to-left and this being a bitmap
# font, it doesn’t scale on retina/hidpi displays.

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return exec konsole
bindsym $mod+F1 exec --no-startup-id killall gta4Browser.exe

# kill focused window
bindsym $mod+Shift+c kill

# start dmenu (a program launcher)
# bindsym $mod+d exec dmenu_run
# There also is the (new) i3-dmenu-desktop which only displays applications
# shipping a .desktop file. It is a wrapper around dmenu, so you need that
# installed.
# bindsym $mod+d exec --no-startup-id i3-dmenu-desktop
bindsym $mod+r exec --no-startup-id rofi -show run -m -1 -hide-scrollbar

# change focus
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+h focus left
bindsym $mod+l focus right

# move focused window
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+h move left
bindsym $mod+Shift+l move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+Shift+v split v

# split in vertical orientation
bindsym $mod+v split h

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+d focus child

# Name the workspaces
set $tag1 "1 &#xf1d7;"
set $tag2 "2 &#xf121;"
set $tag3 "3 "
set $tag4 "4 &#xf120;"
set $tag5 "5 &#xf03d;"
set $tag6 "6 &#xf001;"
set $tag7 "7"

# tag workspaces
workspace $tag1 output primary
workspace $tag2 output nonprimary
workspace $tag3 output primary
workspace $tag4 output primary
workspace $tag5 output nonprimary
workspace $tag6 output primary
workspace 7 output nonprimary
workspace 8 output primary
workspace 9 output primary

# switch to workspace
bindsym $mod+1 workspace $tag1
bindsym $mod+2 workspace $tag2
bindsym $mod+3 workspace $tag3
bindsym ctrl+$mod+3 workspace $tag3
bindsym $mod+4 workspace $tag4
bindsym $mod+5 workspace $tag5
bindsym $mod+6 workspace $tag6
bindsym $mod+7 workspace 7
bindsym $mod+8 workspace 8
bindsym $mod+9 workspace 9

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace $tag1
bindsym $mod+Shift+2 move container to workspace $tag2
bindsym $mod+Shift+3 move container to workspace $tag3
bindsym $mod+Shift+4 move container to workspace $tag4
bindsym $mod+Shift+5 move container to workspace $tag5
bindsym $mod+Shift+6 move container to workspace $tag6
bindsym $mod+Shift+7 move container to workspace 7
bindsym $mod+Shift+8 move container to workspace 8
bindsym $mod+Shift+9 move container to workspace 9

# reload the configuration file
bindsym $mod+Shift+r reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Control+r restart
# exit i3 (logs you out of your X session)
# bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'"
```

### Linux distribution & Version

Archlinux

### Are you using a compositor?

picom

### Logfile

https://logs.i3wm.org/logs/6237042862194688.bz2

**Comment by orestisfl** [comment] 2024-04-29 08:36
Thanks but the underlying bug/issue here is https://github.com/i3/i3/issues/2753, I don't see the reason to have a separate ticket so I'll close this one as a duplicate.

**Closed as not planned by orestisfl** 2024-04-29 08:36 UTC
Labels: bug, 4.23

**Comment by Hi-Angel** [comment] 2024-04-29 09:20
@orestisfl but aren't these issues different? The one you linked is about keybindings sometimes breaking. This one however is about reload/restart don't making them work.

**Comment by Hi-Angel** [comment] 2024-04-29 09:24
Just to clarify: I get what you mean by saying that the underlying issue is the same *(as opposed to its appearance which isn't)*. But the issue you linked doesn't seem to have determined what the underlying issue is, so… do you know what that is? If that's the case, it might be useful to just mention it there 😊

**Comment by orestisfl** [comment] 2024-04-29 10:48
The issue was linked by you. If your reproduction instructions include <wait for other issue to happen> then we should probably keep track of it only at one ticket instead of two which is more confusing.

> do you know what that is?

I haven't spent much time to investigate the original issue, just doing basic housekeeping here. If I misunderstand something just let me know.
