### ISSUE TITLE
Window not focused on goto/mark and subsequent crash on i3 restart

### ISSUE THREAD

**Issue by AladW** [i3/i3#2597] opened 2016-12-02 12:16 UTC
Output of `i3 --moreversion 2>&- || i3 --version`:
```
Binary i3 version:  4.13-24-gd7dcef6 (2016-11-30, branch "next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13-24-gd7dcef6 (2016-11-30, branch "next") (pid 22696)
Loaded i3 config: /home/archie/.config/i3/config (Last modified: Fr 02 Dez 2016 13:03:51 CET, 323 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5738196700758016.bz2

**What I did:**

I've created a mode to set marks on windows and jump to them. The mode looks as follows:
```

set $mode_mark add (a), goto (g), chromium (c), thunderbird (b), emacs (e), qpdfview (q), recoll (r)
mode "$mode_mark" {
                # hardcoded focus keybindings
                bindsym c [class="(?i)chromium"] focus; mode "default"
                bindsym b [class="(?i)thunderbird"] focus; mode "default"
                bindsym q [class="(?i)qpdfview"] focus; mode "default"
		bindsym r [class="(?i)recoll"] focus; mode "default"
		bindsym e [class="(?i)emacs"] focus; mode "default"
		bindsym k [class="(?i)keepassx?"] focus; mode "default"

                # keybindings for marking and jumping to clients
                bindsym a exec i3-input -F 'mark %s' -P 'Mark name: '
                bindsym g exec i3-input -F '[con_mark=%s] focus' -P 'Go to mark: '; mode "default"

                # Assign marks to keys 1-5
                bindsym Shift+1 mark mark1
                bindsym Shift+2 mark mark2
                bindsym Shift+3 mark mark3
                bindsym Shift+4 mark mark4
                bindsym Shift+5 mark mark5

                # Jump to clients marked 1-5
                bindsym 1 [con_mark="mark1"] focus
                bindsym 2 [con_mark="mark2"] focus
                bindsym 3 [con_mark="mark3"] focus
                bindsym 4 [con_mark="mark4"] focus
                bindsym 5 [con_mark="mark5"] focus

                # Exit to the default mode
                bindsym Return mode "default"
                bindsym Escape mode "default"
}

bindsym $mod+m mode "$mode_mark"
```

**What I saw:**

When jumping to a window with a mark, the titlebar is focused but otherwise the focus remains on the originally focused window. I've made a screencast to demonstrate this:

https://paste.xinu.at/fYYNU/

When restarting i3 afterwards, it crashes with SIGABRT. Backtrace:

https://paste.xinu.at/H0oe/

I've reproduced this both with my original configuration and a minimally changed default from i3-wizard-config.

https://paste.xinu.at/bz1/ (my config)
https://paste.xinu.at/HLrpc/ (i3-wizard-config + mode)

**What I expected instead:**

I expect that the window selected by a mark is fully focused, both for the titlebar and otherwise. I also expect that i3 doesn't crash when I restart it.

**Comment by Airblader** [comment] 2016-12-02 13:58
The crash is a duplicate of #2511. The focus issue is something we should look into. I'll need to take a look at it. Meanwhile, can you provide the output of `xprop` for the emacs window?

**Comment by AladW** [comment] 2016-12-02 14:01
https://paste.xinu.at/BYH8/

**Comment by AladW** [comment] 2016-12-02 14:20
FWIW, the focus issue is also a regression from 4.12. I'll do a bisect later

**Comment by Airblader** [comment] 2016-12-02 14:30
@AladW Thanks, that'd be really useful. :-)

**Comment by AladW** [comment] 2016-12-02 14:52
6746aa4b5ff884f9bbebd45685f2aadb0a8a62f7

**Comment by Airblader** [comment] 2016-12-02 14:55
Interesting. Does this happen only for emacs or for other clients as well? Can you pull a xtrace log while running emacs* under x11trace?

*) If other clients show it, too, please use the »simplest« kind of program (like a terminal). More graphical applications will produce quite a bit more log here.

**Comment by AladW** [comment] 2016-12-02 15:07
Yes, it's the same with other applications. Here's the log for urxvt:

https://paste.xinu.at/Du7s/

**Comment by Airblader** [comment] 2016-12-02 16:59
Thanks. I can reproduce this, but only when actually using i3-input. Haven't figured out the cause yet.

**Comment by Airblader** [comment] 2016-12-02 17:16
OK, I think I can explain what's happening here. Upon terminating, i3-input will revert input focus back to wherever it was when it opened (by sending a request early on and only getting the reply in the end). To set the focus, it uses CurrentTime. What happens now is this:

1. terminal is focused, has input focus and runs i3-input.
2. i3-input acquires input focus. i3 learns of the change and updates the latest_time to this point (*)
3. i3-input queries the input focus (which will be the terminal).
4. i3-input shuts down and fetches the reply (terminal) and sets input focus to the terminal. The connection is flushed.
5. i3-input sends the IPC message.
6. i3 now processes the IPC message before the FocusIn is processed. Since we use (*) to set input focus, the X server rejects the focus request.
7. i3 processes the FocusIn event (which reverts focus to the terminal). At this point i3 incorrectly thinks the input focus is owned by emacs, but it detects the FocusIn as a grab/ungrab event and ignores it.

This leaves us in the inconsistent state of i3 thinking emacs is focused, but the actual input focus being with the terminal. I'll need to think a bit more about where exactly things go wrong and how it can be fixed.

**Comment by Airblader** [comment] 2016-12-02 17:19
Side note: I'm not sure why the event in 7. is detected as grab/ungrab, that sounds wrong. However, fixing this would only lead to the terminal being focused which isn't what the user expects to happen here.

**Comment by Airblader** [comment] 2016-12-02 17:47
@stapelberg Why does i3-input acquire input focus anyway? We grab the keyboard, that should be enough. That's how rofi seems to do it as well and a quick test is positive, too (and fixes this issue).

**Closed** 2016-12-02 18:05 UTC
Labels: 4.13, bug, reproducible

**Comment by AladW** [comment] 2016-12-02 18:13
Thanks for the quick fix. :+1:

**Comment by Airblader** [comment] 2016-12-02 22:07
It was mostly thanks to your quick feedback and willingness to investigate and provide information, so thank you!
