### ISSUE TITLE
Print as PDF has filename issue

### ISSUE THREAD

**Issue by olivierbeltrando** [i3/i3#5059] opened 2022-07-27 09:10 UTC
## I'm submitting a…
<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
When trying to print a page into a PDF from a web browser (Firefox, Chrome), it is difficult to save the pdf file with a custom name.

## Expected Behavior
The save as function should work normally (ie. not go in filter mode all the time)

## Reproduction Instructions
Video of the reproduction: https://youtu.be/Mb_BLn4Vaxw
- In Firefox/Chromimum press control-P
- Select PDF, then Click on save
- File-Saver window is opened, try to change the filename -> Bug is that it triggers the "filter" function of the File-Saver window.

## Environment
- Ubuntu 22.04 (with all packages up-to-date)
- I3WM on top (https://i3wm.org/) 4.20.1
- Firefox 103 or Chromium

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.20.1 (2021-11-03) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.20.1 (2021-11-03) (pid 37166)
Loaded i3 config:
  /home/olivier/.config/i3/config (main) (last modified: ven. 20 mai 2022 22:08:23, 5834363 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

The issue can be reproduced even with a config as short as this one. (So I am guessing this is not a config issue)
<details><summary>Config file</summary><pre>
set $mod Mod4
font pango:monospace 6
</pre>
</details>

<pre>
Logfile URL: https://logs.i3wm.org/logs/6326242353610752.bz2
</pre>

<pre>
- Linux Distribution & Version: - Ubuntu 22.04 (with all packages up-to-date)
- Are you using a compositor (e.g., xcompmgr or compton): Compton
</pre>

## Additional text
Hello i3 team,

Hope you are all well.
So I am opening the bug here although I am not 100% sure about in which component the issue is. This bug started appearing after I moved to Ubuntu 22.04. It happens when I try "to print into a pdf" (control-P + destination "save in pdf") in Firefox or Chrome using i3wm.
It does not happen with the Default Ubuntu Gnome flavour, only with the i3wm.
I have uploaded a video here (https://youtu.be/Mb_BLn4Vaxw) to show how to reproduce, and give an overview, and also possibily give a glimpse on how annoying this bug is :D

I hope this is enough data to investigate and possibily fix :)

Other than this I am super happy with i3, I have been using it for 4 years :)

Cheers,
Olivier

**Comment by Airblader** [comment] 2022-07-27 09:15
Thank you for the detailed report & video!

This doesn't look like an issue with i3 to me. Everything that is happening is happening inside the client's window, which the window manager is not involved in. The only thing i3 could be getting wrong here is setting the keyboard input focus, but since the key strokes still end up in the correct window that doesn't seem to be the case either.

**Comment by olivierbeltrando** [comment] 2022-07-27 09:31
Hi @Airblader , 
Wow this is super quick ! What would be your suggestion ? which would be the component that could be at fault ?
I would be happy to push my ticket to the right backlog, so if you have any idea on where this should land, that would be awesome :)
Cheers,
Olivier

**Comment by Airblader** [comment] 2022-07-27 09:34
A few things to try and circle in on the issue:

1. Try different keyboards to rule out input hardware issues.
2. Try different applications that let you print. Ideally even using different underlying framework (Qt, GTK), but this is hard to tell as a user.
3. Try a different (simple) window manager such as Openbox, Awesome, ... (who knows, I could be wrong)

**Comment by olivierbeltrando** [comment] 2022-07-27 09:40
### Different keyboards
- Tried with 2 different keyboards, same results

### Different applications
- LibreOffice : no issues
- Gnome File viewer (https://wiki.gnome.org/Apps/EyeOfGnome) : no issues (so theoretically same fwk (Gnome))
- Shotwell : no issues

Not sure which other apps I should try. (Also on vanilla Ubuntu 22.04 I have no issues).

### Different WM
test ongoing.

Thank you for the support :)

**Comment by Airblader** [comment] 2022-07-27 09:42
You can also already consider posting on the i3wm subreddit. There might be people with more ideas, or with some luck someone who can reproduce the issue. Or, in the worst case, people with more time than me. ;-)

**Comment by olivierbeltrando** [comment] 2022-07-27 09:51
## Different WM
* OpenBox : issue is there :warning: 
* Awesome: issue is there :warning: 

So it looks like the WMs send info to the File-Saver dialog (Nautilus ?) which puts the text into the "filter" section.

Ok will try the subreddit :)

Thanks again.

**Comment by Airblader** [comment] 2022-07-27 09:53
Great (for us) :+1: I would report an issue to the application owning that dialog (you can try to `xprop` it to get some information on it). Since you do not have the issue in many other places it's less likely to be a framework issue.

**Comment by Airblader** [comment] 2022-07-27 09:53
I'll close this issue here for now as unactionable, but please to feel free to cross-reference or comment.

**Closed as not planned by Airblader** 2022-07-27 09:53 UTC
Labels: bug, bug_somewhere_else, 4.20

**Comment by olivierbeltrando** [comment] 2022-07-27 10:07
Good idea the xprop. putting it for the record. And the new lead is : "xdg-desktop-portal-gnome", "xdg-desktop-portal-gnome"

Thanks again @Airblader .

```shell
> xprop
_GTK_THEME_VARIANT(UTF8_STRING) = 
_NET_WM_DESKTOP(CARDINAL) = 1
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
I3_FLOATING_WINDOW(CARDINAL) = 1
_NET_WM_STATE(ATOM) = _NET_WM_STATE_MODAL
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		window id # of group leader: 0x1a00002
WM_TRANSIENT_FOR(WINDOW): window id # 0x1200092
_NET_WM_OPAQUE_REGION(CARDINAL) = 0, 0, 1288, 741
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x1, 0x1, 0x0, 0x0
XdndAware(ATOM) = BITMAP
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 27262982, 27262983
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x1a00005
WM_CLIENT_LEADER(WINDOW): window id # 0x1a00002
_NET_WM_PID(CARDINAL) = 64578
WM_LOCALE_NAME(STRING) = "fr_FR.UTF-8"
WM_CLIENT_MACHINE(STRING) = "olivier-B450M-DS3H"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 433 by 419
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "xdg-desktop-portal-gnome", "xdg-desktop-portal-gnome"
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG
WM_ICON_NAME(STRING) = "Enregistrer sous"
_NET_WM_ICON_NAME(UTF8_STRING) = "Enregistrer sous"
WM_NAME(STRING) = "Enregistrer sous"
_NET_WM_NAME(UTF8_STRING) = "Enregistrer sous"
```

Cheers,
Olivier

**Comment by olivierbeltrando** [comment] 2022-07-27 10:15
And the new issue logged on xdg-desktop-portal-gnome : https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/issues/53

**Comment by olivierbeltrando** [comment] 2022-12-23 18:59
Turns out this is a behavior that happens with the save as functionality (thanks @t8-ch) on program installed by snap (so firefox and chromium on my ubuntu).

On this thread a temporary workaround has been found for firefox
https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1968887
set the `widget.use-xdg-desktop-portal.file-picker` to `0` in the `about:config` in Firefox.

Real issue is tracked on this thread I think: 
https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1949340
