### ISSUE TITLE
Allow number in workspace to output assign

### ISSUE THREAD

**Issue by joepvd** [i3/i3#3685] opened 2019-04-15 22:12 UTC
## I'm submitting a…
<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Trying to make use of workspace-to-output-assignments. When copying the number idiom `bindsym $mod+1 number 1` to this assignment, nagbar tells the following:

```
ERROR: CONFIG: Expected one of these tokens: 'output'
ERROR: CONFIG: Line 150: workspace number 1 output LVDS1 VGA1
ERROR: CONFIG:                            ^^^^^^^^^^^^^^^^^^^
```

## Desired Behavior
I can continue to use the `workspace number X` idiom when assigning workspaces to outputs.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.16.1 (2019-01-27) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.16.1 (2019-01-27) (pid 2394)abort…)
Loaded i3 config: /home/joep/.config/i3/config (Last modified: Mo 15 Apr 2019 23:34:26 CEST, 918 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
- Ubuntu 16.04
- Are you using a compositor (e.g., xcompmgr or compton): compton
</pre>

**Comment by orestisf1993** [comment] 2019-04-15 22:28
Documentation here can be improved but this already works, just remove the `number` token

**Comment by joepvd** [comment] 2019-04-16 08:09
Oh, I see. The reason I tried is probably actually a bug, and it relates to actions after a new output has been made available.

Take the following config:

```
workspace 1 output HDMI1 eDP1
workspace 2 output HDMI1 eDP1
```
And this state:
- Output HDMI1 is disabled
- Workspace 1 is called `1: named`, on eDP1
- Workspace 2 is called `2`, on eDP1.

Now enable output HDMI1. Result:
- Workspace `2` gets moved to output HDMI1
- Workspace `1: named` stays put.

I would expect the workspace `1: named` also to get reassigned to te new output.

When I change the name of workspace 1 with e.g. `i3-msg -t run_command 'rename workspace "1: named" to "1: named"'`, the workspace gets moved to the new output.

**Comment by anowlcalledjosh** [comment] 2019-04-17 18:29
I also often notice some buggy behaviour when connecting new monitors.

If I have workspaces `1: named` and `2: named` on a single output `eDP-1` (`2: named` has focus) with the following config:

```
workspace 1 output eDP-1
workspace 2 output HDMI-2
```

then connecting `HDMI-2` will result in not only the `2: named` workspace moving to `HDMI-2`, but also a new workspace called just `2` being created on `HDMI-2`, and that new workspace is given focus.

I then have to use the mouse to select the `2: named` workspace again and make the `2` workspace go away, since `workspace left` and `workspace right` don't seem to work properly when there are duplicate numbers.

**Comment by angeelgod** [comment] 2020-04-15 22:00
I can confirm this buggy behavior is still present on i3 version 4.18-1, and agree on the original issue as this should be a new feature altogether (like being able to `workspace number NUMBER output OUTPUT`) as to remove any ambiguity while assigning workspaces to output, and avoid conflicts between named and non-named workspaces

**Closed** 2020-10-19 08:41 UTC
Labels: bug
