### ISSUE TITLE
i3 hangs after unlock when resuming from suspend or waking up screen

### ISSUE THREAD

**Issue by zaeph** [i3/i3#3296] opened 2018-05-27 09:47 UTC
Hello,

## I'm submitting a…
<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Sometimes, upon resuming from suspend, unlocking with i3lock, and receiving notifications which had been held until unlock, i3 hangs. I can somewhat interact with the window on the current workspace (usually Emacs) which reacts to focus changes (switching between focussed and unfocussed faces on the mode-line) but not to keyboard or mouse inputs. The time on my i3bar (i3blocks) is still running, as are most of the other blocks except some of the icons in the tray. The notifications received prior to the hang remain on screen past their expiration time and cannot be dismissed. I cannot change workspace or restart/exit i3, and it doesn’t react to SIGCONT sent from another a newly opened tty. SIGKILL kills i3 and drops me back in the original tty.

## Expected Behavior
Upon resuming from suspend, unlocking with i3lock, and receiving notifications which had been held until unlock, i3 runs normally.

## Reproduction Instructions
This is the first bug report I ever submit, so please bear with me as I familiarise myself with the method.

So far, I’ve encountered about 10 hangs like the one described above, and I was able to get logs for most of them (systemd journals for all of them, and i3 logs for the last 6).
The problem is that I can’t find a reliable way to reproduce them. Somehow, the easiest way to reproduce the problem is to resume the computer from a long suspend session (e.g. from night to morning). However, it also happened a couple of times when waking up the screen and unlocking. As is usually the case with *random* hangs, it’s hard to pinpoint exactly what the issue may be. All I know is that they started happening this week.
I’ve been investigating my logs, and I wasn’t able to find anything conclusive so far. My educated guess would be that it comes from an interaction between i3, my notification service (dunst with dunstify), and the update of my i3blocks via RTMIN signals. Desperate as I was for clear reproducible steps, I’ve checked in my Linux journal if I had installed or tweaked anything remotely incriminating. I’ve uncovered four possible trails: 1) modifying the *DRI* and *TearFree* options in 20-intel.conf, 2) forcing acceleration in Firefox via modifying variables in about:config 3) an overhaul of the systemd service I use for locking my laptop on screen-off and suspend, and 4) the creation of an edit-in-emacs script which required the addition of a couple of lines to my i3/config. The first three proved inconclusive, since reverting them didn’t prevent further hangs, and the change to my i3/config was so insignificant in (4) that I doubt that it’d be the culprit.
At first, I suspected a repeat of #2539 or [#polybar435](https://github.com/jaagr/polybar/issues/435), but SIGCONT wasn’t able to resume i3. The i3 logs didn’t speak a whole lot to me. All I can tell is that once the hang occurs, i3 does not log anything, which would seem to indicate a problem with i3 itself, hence my submitting a bug report here rather than on i3blocks or dunst. I also use the i3-gaps patch, but it seems to be reliable enough to not consider it as a player in this issue.

## Environment
Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.15.0.1 (03-13-2018) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15.0.1 (03-13-2018) (pid 24969)rt…)
Loaded i3 config: /home/zaeph/.config/i3/config (Last modified: Sat 26 May 2018 16:08:48 CEST, 68046 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

[i3/config](https://pastebin.com/hvM0qbL3)
The lines which have been changed within the last two weeks are the following:
<pre>
for_window [title="edit-in-emacs.txt"] floating enable
for_window [title="edit-in-emacs.html"] floating enable
</pre>

For now, I will only include a link to the shortest i3 log, namely the one which occured only 5 min after startx. The log is fairly large, probably because I tried to overload my notification system prior to locking my laptop to see if I could reproduce the hang.
I've also included my systemd journal from startx until I moment I switched to tty2, which I did right after the hang happened (I've expunged some GPG info).
[i3.log](https://github.com/i3/i3/files/2042443/i3.log) (Last 10s on pastebin: [i3.log](https://pastebin.com/eMr7NDM2))
[journalctl-relevant-part.log](https://github.com/i3/i3/files/2042451/journalctl-relevant-part.log) ([pastebin](https://pastebin.com/UaEqpDnE))

<pre>
- Linux Distribution & Version: Arch
- Are you using a compositor (e.g., xcompmgr or compton): No.
</pre>

Please excuse me for the length of the report and its lack of pinpointing. I'm at a loss after a week of troubleshooting, and the randomness of it all makes it difficult to track on my own. I hope you'll be able to assist me, and in the meantime, I'll see if I can refine my investigation.

Thank you.

**Comment by orestisf1993** [comment] 2018-05-27 10:49
Can you check with https://github.com/i3/i3/pull/3263 please? After cloning i3/i3, you need to run `git fetch origin pull/3263/head:pr3263`, then `git branch pr3263` and then follow https://i3wm.org/docs/hacking-howto.html#_building_i3.

Other than that, it would be helpful if we had a backtrace of i3 when this happens.

**Comment by Zaeph** [comment] 2018-05-27 13:57
> You shouldn't apologize for a detailed and specific bug report — on the contrary, I wish every issue would be as well-formulated as yours!

Thank you for your compliment. I just didn’t want it to be too verbose, since it tends to muddle the point.

> Can you check with #3263 please? After cloning i3/i3, you need to run git fetch origin pull/3263/head:pr3263, then git branch pr3263 and then follow <https://i3wm.org/docs/hacking-howto.html#_building_i3>.

Thank you for your suggestion. I’ll preface my answer by mentioning that, coming from the Humanities, my knowledge of Linux is patchy at best. I made the switch after a couple of years using Emacs, and even though I try to be methodical about the ways I learn and document my findings, it’s very much an ongoing process. I’m grateful for your instructions, and I hope you won’t mind the triteness of some of my questions

This is the first time I had to build a package outside of Arch’s AUR, let alone from a different branch than the main one. I’ve followed your instructions, and I’ve encountered a problem when I ran `git branch pr3263`:
```sh
$ git branch pr3263
fatal: A branch named 'pr3263' already exists.
```
I assumed this wasn’t a big deal, and that `git fetch` had already created the branch. I then followed the build instructions on the wiki, and replace the following line in my .xprofile:
```sh
# exec i3 --shmlog-size=26214400
exec /home/zaeph/.builds/i3/build/i3 --shmlog-size 26214400
```
Then, runing `startx`, i3 starts properly, excepts for two things:

1.  My i3bar isn’t showing up, even when I restarted,
2.  Notifications which were usually sent by NetworkManager upon WiFi connections aren’t showing up. All my other notifications are working (volume/brightness control, emails, etc.).

To me, that would seem to indicate that the problem comes from either of them, if not both. I’ve scoured through #3263, which I had stumbled on before, but I doesn’t make a whole lot of sense to me because I lack experience with IPC and sockets. All I know is that I’d tried this [reproducible step](https://github.com/jaagr/polybar/issues/435#issuecomment-382932152) mentioned on jaagr/polybar#435, which did cause i3 to hang and then resume upon sending SIGCONT. It gave me hope that this would work with my own issue, but to no avail.

> Other than that, it would be helpful if we had a backtrace of i3 when this happens.

Is there a difference between logs and back-traces? I've provided an incriminating log in my first message, if that's of any help.

At any rate, thank you for your help, and I hope this helps.

**Comment by apetresc** [comment] 2018-05-27 14:29
I don’t think you’ve actually compiled the correct branch - the command you
wanted was ‘git checkout pr3263’, not ‘git branch pr3263’ — the latter
tries to _create_ a new branch named ‘pr3263’, which, as it already exists,
just failed and left you in ‘master’, which is probably what you built
instead.

So, try to rebuild again after a ‘git checkout pr3263’ and see if that
helps :)

**Comment by orestisf1993** [comment] 2018-05-27 14:31
Sorry for the time waste, I was typing from memory. I meant `git checkout pr3263`. You'll have to run this and then run again `make -j` inside the build/ folder.

There might be some incompatibilities between the i3 git version and 4.15 i3bar. Add these in the beginning of your script:
```
i3_path="$HOME/.builds/i3"
i3_build="$i3_path/build"
export PATH="$i3_path/:$i3_build/:$i3_build/i3-config-wizard:$i3_build/i3-dump-log:$i3_build/i3-input:$i3_build/i3-msg:$i3_build/i3-nagbar:$i3_build/i3bar:$PATH"
```
to use the git i3bar version too.

**Comment by Zaeph** [comment] 2018-05-27 15:29
Hello again,

> Sorry for the time waste, I was typing from memory. I meant git checkout pr3263. You'll have to run this and then run again make -j inside the build/ folder.

Done. I forgot to make a note of what `git checkout pr3263` returned, but it was something along the lines of ‘switching to branch’

> There might be some incompatibilities between the i3 git version and 4.15 i3bar. Add these in the beginning of your script: [...]

I've modified my .xprofile accordingly:
```sh
# exec i3 --shmlog-size=26214400
# exec /home/zaeph/.builds/i3/build/i3 --shmlog-size 26214400

i3_path="$HOME/.builds/i3"
i3_build="$i3_path/build"
export PATH="$i3_path/:$i3_build/:$i3_build/i3-config-wizard:$i3_build/i3-dump-log:$i3_build/i3-input:$i3_build/i3-msg:$i3_build/i3-nagbar:$i3_build/i3bar:$PATH"

exec i3 --shmlog-size=26214400
```
And here's what `i3 --moreversion 2>&-` reports:
```sh
$ i3 --moreversion 2>&-
Binary i3 version:  4.15-148-g26f50898 (2018-05-20, branch "next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15-148-g26f50898 (2018-05-20, branch "next") (pid 13031)
Loaded i3 config: /home/zaeph/.config/i3/config (Last modified: Sun 27 May 2018 14:58:28 CEST, 8340 seconds ago)

The i3 binary you just called: /home/zaeph/.builds/i3/build/i3
The i3 binary you are running: i3
```
There doesn't seem to be any change to the version running, so I suppose that the change isn’t supposed to show up there.

At any rate, my i3bar now works, and so do the notifications. I'll describe the behaviour 1) before changing i3_path, and 2) after changing i3_path.
1) Something that might be worthy of note is that prior to changing changing the i3_path, my notifications showed up behind the windows on the workspace, meaning I had to switch to an empty workspace to see them. The problem gets resolved after a few seconds of run-time. The NetworkManager notifications did not show up.
2) After changing the i3_path, my i3bar and my notifications all work properly. The NetworkManager notifications are also back. The only thing worthy of note with my notifications is that when they first show up, they create a slight visual glitch: a box slightly larger than the rectangle notification which shows my workspace background (drawn with feh).

I've tried suspending my computer after locking it, or waking up the screen after locking it, and neither of them led to a hang. Again, because of the randomness of my issue, it's hard for me to tell when those hangs will happen, so I will try to re-create the issue by putting my computer so sleep for a long-ish amount of time (1-2h) and see if hangs on resume & unlocking.

**Comment by orestisf1993** [comment] 2018-05-27 15:36
You did run make again after changing (`checkout`) the branch right?

**Comment by Zaeph** [comment] 2018-05-27 16:00
> Did did run make again after changing (checkout) the branch?

Yes, I did, and forgot to save the output. I re-did to get some sort of output, and that's what I got:
```sh
$ cd ~/builds/i3/build
$ make -j
make  all-am
make[1]: Entering directory '/home/zaeph/.builds/i3/build'
make[1]: Leaving directory '/home/zaeph/.builds/i3/build'
```

**Comment by orestisf1993** [comment] 2018-05-27 16:02
Don't worry, just making sure you did that step. Let us know if it hangs again.

**Comment by Zaeph** [comment] 2018-05-27 16:05
Thank you, and I will.

If I may hazard a guess for the future, if no further hang happens on my end, would it be conducive to a merge with the main branch?
Sorry if it's trite, but I hadn't got to the point of git, github, and version control up until now in my journey.

**Comment by Zaeph** [comment] 2018-05-27 19:43
So far, I've had two prolonged suspend sessions, and i3 resumed without trouble both times. A tentative conclusion would be that it is working. I'll wait three days to have a larger sample, and I'll report then.

**Comment by Zaeph** [comment] 2018-05-27 20:47
Folks, not only do I have excellent news, but also reproducible steps (at leats on my end).

Moments after my previous message, I’ve encountered a hang, the nature of which was bit special since it register mouse inputs. The hang occured when I was on Firefox, and I could interact with the page, the tabs, but also switch between the different workspaces.
But wary as I was, I’ve noticed something that had escaped my attention before. I’ve mentioned that I lock my computer with i3lock after two events: 1) upon suspending my computer, and 2) upon turning off the screen (I touch/remove a file which is used by systemd to know whether it should lock after an event). Sometimes, I would turn off my screen, and realise that I would instead prefer to suspend my computer. Then, while the computer is locked, I would either close the lid or use the <Fn>-shortcut, which on my Thinkpad is <Fn>-4 (not <F4>, 4). Tonight, I did the latter, and upon unlocking, it resulted in the hang I’ve described in this issue.

I was able to reproduce it 3 times after this, which implies that I can reliably reproduce the hangs on my end. Based on this, I was able to investigate:
1) The hangs are only cause when I use the <Fn>-shortcut when the computer is already locked, and not when I close the lid when the computer is already locked.
2) I’ve taken the liberty to go back to the main branch to see if I could also reproduce it on it, and I could indeed reproduce it.

Since I have reproducible steps, I can now provide you with proper logs.
[pr3263-i3.log](https://github.com/i3/i3/files/2042994/pr3263-i3.log)
[pr3263-journalctl-expunged.log](https://github.com/i3/i3/files/2042995/pr3263-journalctl-expunged.log)
[main-i3.log](https://github.com/i3/i3/files/2042996/main-i3.log)
[main-journalctl-expunged.log](https://github.com/i3/i3/files/2042997/main-journalctl-expunged.log)

You haven't told me whether there was a difference between back-traces and logs. I remember reading about `strace` in one of the bug reports here, so let me know if you'd like me to get you anything else. If you meant the trace that i3 returns upon killing it, I can tell you that it's more verbose in pr3263 than it is on the main branch, but I'm not sure how to grab this for you.

Hope this helps

**Comment by orestisf1993** [comment] 2018-05-27 21:13
Let's continue using the `next` branch. Since your issue remains with pr3263 we can ignore that branch. To acquire a backtrace you'll need to use gdb from a separate tty. Since ptracing non-child processes is not allowed to non-root users you'll either need to run gdb using `sudo` or run `echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope` once (temporary change).

Once the hang happens, switch to a new tty and run `gdb -p $(pidof i3)` and in gdb's prompt type:
```
set logging on
backtrace
backtrace full
quit
```

The output should be written in gdb.txt in your home folder (or root's home folder if you ran gdb with sudo). Please attach that file.

Also, to confirm that i3 is indeed frozen, in a new tty run:
```
DISPLAY=:0 i3-msg workspace test
```
i3-msg should get stuck too.

**Comment by Zaeph** [comment] 2018-05-27 21:42
I can confirm that `DISPLAY=:0 i3-msg workspace test` hangs as well.
Here are the logs you've asked me to provide.
[gdb.txt](https://github.com/i3/i3/files/2043042/gdb.txt)
[i3.log](https://github.com/i3/i3/files/2043043/i3.log)

**Comment by orestisf1993** [comment] 2018-05-27 21:57
It seems weird that i3 is stuck waiting for events but won't stop waiting even though i3-msg writes in it's socket. Can you please run
```
DISPLAY=:0 i3-msg workspace test&  # notice the '&'
ps aux | grep i3 > out.txt
```
and paste the output here?

**Comment by Zaeph** [comment] 2018-05-27 22:17
Here's the output:
```
zaeph    30846  1.0  0.5 21475078452 81508 tty1 T   00:08   0:00 i3 --shmlog-size=26214400 -a --restart /run/user/1000/i3/restart-state.30846
zaeph    30953  0.5  0.3 21475022652 56032 ?   S    00:08   0:00 i3bar --bar_id=bar-0 --socket=/run/user/1000/i3/ipc-socket.30846
zaeph    30954  0.0  0.0   4312  1812 ?        T    00:08   0:00 i3blocks -c /home/zaeph/.config/i3/i3blocks.conf
zaeph    31827  0.0  0.0  14816   984 tty2     S    00:08   0:00 i3-msg workspace test
zaeph    31842  0.0  0.0  12652  2344 tty2     S+   00:09   0:00 grep --color=auto i3
```
I stumbled upon something which might guide us in the right direction.
I was in a bit of a quandary trying to meet your request because, somehow, I couldn't reproduce the hang anymore. After a bit of investigating, it turned out that I'd left my *busy-mode* on, which suppresses my notifications from making sounds. It's a very basic setup:
```sh
$ cat .bin/notification-sound
#!/bin/bash

BUSY_MODE=$HOME/.busy-mode

if [[ ! -f $BUSY_MODE ]]; then
   mpv "/home/zaeph/SFX/Favourites/item-pickup.wav"
fi
```
And `busy-mode-control` is the tool I use to touch/remove `$BUSY_MODE` and generate notifications in i3blocks and dunst.

To come back to the hang, when my `busy-mode` is activated, if I suspend my computer with <Fn>-4 when it's already locked, resume it, unlock it, and send a couple of notifications, it doesn't hangs as it would if `busy-mode` were off. However, as soon as I turn off busy-mode it off, the hang happens.
Could this be due to my `mpv` as the sound-maker?

**Comment by orestisf1993** [comment] 2018-05-27 22:49
The T state here means "stopped by job control signal", are you sure that `kill -CONT $(pidof i3)` does nothing?

**Comment by Zaeph** [comment] 2018-05-27 22:55
Sending SIGCOUNT to i3 during a hang restored mouse input (I could change workspace by clicking on them), but it hangs again on keyboard input (couldn't change workspace by clicking on them).

(I'm calling it a night, I'll continue in the morning. Again, thank you for your help.)

**Comment by Zaeph** [comment] 2018-05-28 07:46
Would you like me to get you some logs when sending SIGCONT or when I'm preventing my notifications from making sounds with my /busy-mode/?
In the meantime, I'll try experimenting with `mpv` to see if it's causing the issue.

**Comment by Zaeph** [comment] 2018-05-28 09:03
Would you like me to get you some logs when sending SIGCONT or when I'm preventing my notifications from making sounds with my /busy-mode/?
In the meantime, I'll try experimenting with `mpv` to see if it's causing the issue.

**Comment by Zaeph** [comment] 2018-05-28 13:13
(Apologies for sending multiple comments in a row. Let me know if you’d rather have me edit my earlier ones.)

From now on, I’ll use *hang-able* to refer to the state where provoking a notification with sounds played by `mpv` would result in a hang.

A few notes:
1) In a hang-able state, I’ve tried launching `mpv` to play a regular video. It did not cause a hang.
2) When the hang happens, notifications remain on screen. Upon switching to another tty, and returning to `DISPLAY=:0`, there’s a grapical glitch appearing where the notifications used to be. The glitch is basically a window to my background (drawn by feh). Note that this glitch also appears for 100ms after initiliasing dunst and receiving the first notification. Sending SIGCONT to i3 restores mouse input, but the glitch remains.
Here’s a photograph taken with my phone, with the glitch surrounded by a red box:
![dunst-glitch](https://user-images.githubusercontent.com/12202828/40615962-57fcc7fe-6289-11e8-81c5-21b23a6c4141.jpg)
3) In a hanged stated, notifications which were sent using dunst and dunstify also hang. Sending SIGCONT to the main or child processes doesn’t change their behaviour. Sending SIGKILL successfully kills then, but the glitch remains.
4) Trying a screenshot for the graphical glitch, I’ve noticed that, in a hang-able state, launching `gscreenshot` also causes i3 to hang. I don’t know the inner-workings of `gscreenshot`, but I know that it starts, it takes a screenshot of the entire desktop, probably using `scrot`.

There definitely seems to be something going with the graphical display. Maybe something to do with X? At any rate, I’m starting to doubt more and more that this has anything to do with i3.

Also, I must say that, on my end, I’m quite content with the situation. It was killing me not to know what was causing the hang, but now that I do, it just became a matter of not suspending my computer with <Fn>-4. However, that is not to say that I’m not willing to help further, quite the contrary.

**Comment by Zaeph** [comment] 2018-05-28 20:55
Welp, bad news now.

I've encountered the hang again, and it wasn't provoked by using Fn-4 and resuming. It happened after merely turning off my screen, which locked my computer, and then unlocking it.
I could get i3 to resume by sending SIGCONT to it, and at first, mouse and keyboard inputs were both restored. Note that the graphical glitch mentioned in my previous comment is also there.
Upon attempting to send another notification, keyboard input is lost again. I've tried sending SIGCONT and SIGKILL to `dunst` and `mpv` to see if it'd give me back keyboard input, to no avail. However, I might have another track to follow.

After having lost keyboard input, I was able to move between my workspace and note differences in behaviour between the windows running:
1) In `firefox` everything works, as long as it involves clicking (tab-switching, link-clicking, scrolling, etc.),
2) In `terminator`, I can't seem to gain focus to the window. The cursor remains in its *inactive* state. Same behaviour whether it's a full-frame or floating window,
3) In `emacs`, and that's the interesting part, when clicking inside the frame, `emacs` lets me know that `H-<mouse-1> is undefined`. `H` in `emacs` notation is `Hyper`, which I've bound to the physical `Caps Lock` key to extend my shortcuts, and which is the modifier I use to send the notifications which cause i3 to hang and, after SIGCONT and another notification, refuse keyboard input. A tentative conclusion would be that my `Hyper` key is stuck in a pressed state.

Apparently, it could be something related to my xkb setup which is hack-ish and not particularly robust (I sometimes have to reload my mapping because it gets reset). I run a custom `setxkb-default` in my `.xprofile` which sets the keyboard profile. At any rate, it might be a red herring, but I've tried sending `DISPLAY=:0 setxkb-default` from tty2 to reset my keyboard config, but it didn't resolve it.

I'm at a loss again. It felt good to find reproducible steps, but now, it brought back the stress that my system can hang at seemingly random times. Once more, I'm not sure if this has anything to do with i3, but I'd appreciate your suggestions as to a next step could be.

**Comment by Zaeph** [comment] 2018-05-29 18:18
It’s been a journey, but I think I’ve got to the bottom of this.

I’m not sure how relevant my conclusion is going to be because I don’t think it’s related to `i3`, but I’ll let you be the judge of this.

First, the journey:
1) After yesterday’s unexpected hang, out of desperation, I started sending SIGCONT and SIGKILL to most of my running processes, hoping that one of them would stop grabbing my keyboard upon sending SIGCONT to `i3`. That didn’t prove conclusive, although I was able to resume some processes like this, e.g. `dunst`.
2) After that, I’ve searched for a way to tell X to stop any process currently grabbing the keyboard to stop doing so, and it turns out that there is such a thing: `DISPLAY=:0 xdotool key XF86Ungrab`, and if I send this command to X after resuming i3, keyboard input is restored. Note that a number of processes are still non-responsive, notably `dunst` and some tray apps (`nm-applet`, `copyq`, `fcitx` and `redshift-gtk`).
3) Following from (2), I was able to send `i3-msg restart`, which resulted in an interesting behaviour. The non-responsive processes were still non-responsive, but for the apps in the tray which showed up as blank icons in my `i3bar` before, they were removed from the tray and became windows on the workspace I was currently on. I had an inkling that it meant that those processes were paused, and that sending SIGCONT would resume their normal behaviour, and when I tried it, it was actually the case. The windows on the workspace closed themselves, and the icons appeared back in the tray.
4) Based on this, I assumed that my keyboard must have been grabbed by a process which managed my keyboard input, and I had two of those: `sxhkd` and `xcape`. Now, it started making a whole lot of sense that either one of them would cause this problem, and especially `sxhkd`, which I use for managing all sorts of scripts on my computer, including the ones sending the notifications which cause `i3` to hang. Upon manually restarting `sxhkd`, I was able to use those scripts without any problem.
5) Following from all this, and by conflating (2) and (4), I had to find the link between all those hanged processes, and it didn’t take me long to figure out that those were all the processes I ran from my `.xprofile`.
6) I transferred the lines launching the incriminated processes from my `.xprofile` to my `i3/config`, and after launching `i3`, I did not experience the hangs by doing the reproducible steps I’ve mentioned in a previous comment (locking, then putting to sleep with Fn-4). Problem solved, as far as I can tell at any rate.

# Conclusion:
There seems to be a problem with the way `i3` or `X11` manages the processes and daemons run in `.xprofile`. `i3` seems to be waiting for those processes to be resumed after an /irregular/ suspend (e.g. the Fn-4 suspend), causing it to hang, but `X11` doesn’t seem to be resuming those processes either. So, which of the two is supposed to manage those processes?

Unless there’s any more test you’d like me to run, I’m going to back to i3’s main-branch, since I’m pretty sure I won’t be experiencing this problem anymore.

I wanted to thank you all for your help which put me on the right track, and I hope this will be useful to you or to anyone stumbling upon it. This was by far the trickiest issue I’ve had to investigate, and I must say it’s given me a taste for it, so expect me to be back in the future!

**Comment by orestisf1993** [comment] 2018-05-29 19:45
This is peculiar but I am pretty sure it's not i3's issue since i3 doesn't manage these processes. You might be able to get to the bottom of this if you run one of these .xprofile applications using strace. With that you should be able to find who stops the applications (maybe a STOP signal?). I wish I could help but I don't have any way to reproduce this issue.

I am going to close the issue since there doesn't seem to be anything to be done from i3's side. Thank you for your detailed reports. You are very welcome to keep updating this issue if you have any news since this could be an issue with another application.

**Closed by orestisf1993** 2018-05-29 19:45 UTC
Labels: bug, 4.15

**Comment by Remyks** [comment] 2019-08-22 14:56
I think I find a solution, since I did it I haven't seen any new crash 
Open a new tab in firefox, go to "about:config", click yes, then search for "gfx.webrender.all" and set the value on true...
The only thing, when you will resume from sleep, there will be some invisible text (but after a time, or when you hoover your cursor on it, it'll return to normal)

**Comment by Lostinaa** [comment] 2023-09-24 13:21
I'm having z same issue... only the keyboard freeze after suspened or sleep it happened after I switched to i3 I never had the problem while I was using xfce
