### ISSUE TITLE
Add a command for setting all the windows to the same size

### ISSUE THREAD

**Issue by avalonv** [i3/i3#3792] opened 2019-09-10 21:53 UTC
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Desired Behavior
Similarly to `CTRL-W_=` on vim, a command that automatically resizes all (non floating) windows in the current i3 container to roughly the same size

**Comment by Airblader** [comment] 2019-09-13 07:36
Duplicate of #1623, also see there for a script achieving this.

**Closed by Airblader** 2019-09-13 07:36 UTC
Labels: enhancement

**Comment by avalonv** [comment] 2019-09-13 21:06
I was thinking of a native implementation within i3 since it seems like a common enough operation.

Thanks for linking the script though.
