### ISSUE TITLE
[enhancement] [feature request] Switch back and forth between monitors/outputs

### ISSUE THREAD

**Issue by herbygillot** [i3/i3#2260] opened 2016-03-13 22:24 UTC
Hi all, apologies for opening a pull request before opening this enhancement issue:

I'm looking to add the ability to switch back and forth between monitors, similar to the workspace back and forth switching.  With this feature, you can easily move rapidly between monitors while keeping the workspace sequence independent in the situation where you want workspace back and forth to switch differently.

The pull request implementing this feature is open at #2259

Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.10.3 (2015-07-30, branch "4.10.3") © 2009-2014 Michael Stapelberg and contributors
Running i3 version: 4.10.3 (2015-07-30, branch "4.10.3") (pid 1930)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

**Comment by stapelberg** [comment] 2016-03-21 18:51
I think this is a duplicate of #2118. Your PR provides only part of what was discussed there, but I don’t think it’d be fair to accept your special case while rejecting further back-and-forth functionality in general.

Hence, I’m closing this enhancement request in favor of having this functionality in external scripts.

**Closed by stapelberg** 2016-03-21 18:51 UTC
Labels: enhancement

**Comment by herbygillot** [comment] 2016-03-21 19:22
I understand where you're coming from, but this change does not aim to change workspace back_and_forth in any way.

It simply aims to provide one command for taking focus back to the last output you were focused on, which is a straightforward case that happens often enough when using i3.

It's meant to be a simple command that does what it says on the tin, and the user will use it how he or she will.

**Comment by stapelberg** [comment] 2016-03-21 19:26
Yes, I realize that.

I consider back-and-forth to be an orthogonal feature that could be applied to many different commands that i3 offers, so it doesn’t matter that this feature doesn’t change the “workspace back_and_forth” command specifically, it’s still a change related to back-and-forth.

**Comment by herbygillot** [comment] 2016-03-21 19:28
Understood. Thanks for taking a look.
