### ISSUE TITLE
i3bar can't start after i3wm restart

### ISSUE THREAD

**Issue by kusayuzayushko** [i3/i3#2394] opened 2016-07-10 17:30 UTC
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.12 (2016-03-06, branch "4.12") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.12 (2016-03-06, branch "4.12") (pid 743)
Loaded i3 config: /home/kusayu/.config/i3/config (Last modified: Sun 10 Jul 2016 10:45:41 PM NOVT, 1172 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

URL to a logfile as per http://i3wm.org/docs/debugging.html:
http://logs.i3wm.org/logs/5762957321437184.bz2

URL to i3bar log:
http://pastebin.com/vxR5d9b8

**What I did:**

Start i3, restart x-server twice (with Ctrl+Alt+Backspace).

**What I saw:**

from this moment i3bar disappeared and don't work until reboot no matter how much I restart i3wm, even though i can run i3bar with 'i3bar --bar_id bar-0'

**Comment by jebrosen** [comment] 2016-07-14 23:07
I am having the same issue. In fact, I have had it since first installing i3 and I thought I had to configure a bar myself in order to get one. It wasn't until I next restarted the computer that a bar magically appeared. The issue is present whether using the default config or my own configs. 

Interestingly, launching "i3bar -b bar-0" from dmenu fails but opening a terminal and launching "i3bar -b bar-0" there works. Log files from failed instances of i3bar begin with `(libev) epoll_wait: Invalid argument` and end with `Exiting due to signal.` before rendering anything.

i3 --moreversion output (note /usr/local/bin/; I built manually so I could have debug symbols)
```
Binary i3 version:  4.12-76-g3ffa88e (2016-06-25, branch "next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.12-76-g3ffa88e (2016-06-25, branch "next") (pid 1234)
Loaded i3 config: /home/jeb/.config/i3/config (Last modified: Thu 14 Jul 2016 01:40:13 PM MDT, 12337 seconds ago)

The i3 binary you just called: /usr/local/bin/i3
The i3 binary you are running: i3
```

Failed i3bar log file: http://pastebin.com/qb3kGyCD
Failed i3bar backtrace from the core dump: http://pastebin.com/QpqBrnc1


Furthermore, several applications including the ownCloud sync client and TeamViewer don't start properly. Both create a tray icon upon login. Upon a second login, however, they open up their main windows -- the same startup behavior as they have if they are started when already running.

**Comment by stapelberg** [comment] 2016-07-15 12:17
What shell is installed as `/bin/sh` on your system? Which shell do you specify as login shell in `/etc/passwd` for your user?

The “Exiting due to signal.” comes from i3status, but I believe i3status just exits because i3bar exits in this case.

Do you see the “epoll_wait: Invalid argument” message also in successful runs?

Can you provide an strace log of i3bar failing? Use `strace -s 2048 -f -v -tt -o /tmp/i3bar.log i3bar …`

**Comment by jebrosen** [comment] 2016-07-15 15:14
`File: '/bin/sh' -> 'bash'`. User login shell `/bin/bash`

Successful runs of i3bar do not show the epoll_wait invalid argument message. That code path calls abort() immediately after.

An strace log of i3bar failing will be difficult because setting the i3bar_command to the specified "strace ... i3bar" line makes all the problems disappear and everything works properly. I will try other strace parameters when I get a chance.

As far as I have seen, the only failure scenario is i3 starting i3bar directly when it's not the first login. The first login succeeds and starting via another process (strace, a terminal window, etc.) succeeds.

I've spent all the time I can on this issue for now; I will look at it again later today if I can. Running i3bar under strace makes logins work consistently as a temporary workaround. The same fix for i3bar fixes the other programs, likely because the indicator tray exists again.

**Comment by kusayuzayushko** [comment] 2016-07-15 21:06
>>>file /bin/sh               
/bin/sh: symbolic link to bash
user login shell is zsh.

**Comment by dustinRDF** [comment] 2016-07-22 09:54
```
ls -la /bin/sh
/bin/sh -> bash
```

I'm having the same issue. I'm running Arch Linux, and using i3 version 4.12. However, with some help from the #i3 IRC we were able to get it up and running after manually specifying which socket to use. Or at least I think that's what we did. It was all bit over my head to be honest. The command that got it to run was `i3bar --bar_id=bar-0 --socket=/run/user/1000/i3/ipc-socket.5362` I'm not sure if having /var and-or /tmp on separate partitions from / or /home has anything to do with it, but it might.

**Comment by fmorgner** [comment] 2016-07-22 13:51
Having the same issue here. Interestingly enough, using gdm as the display-manager makes the issue go away for me. I would prefer to use lightdm though. Restarting the display-manager (in the case  of lightdm) resolves the issue for one login. Logging out and in again causes the problem. Running 4.12 on Arch Linux

**Comment by jebrosen** [comment] 2016-07-22 16:12
I can confirm that the issue is present with lightdm and that restarting the display manager temporarily resolves the problem, as @fmorgner explained. Everything worked as expected under lxdm or sddm.

**Comment by dustinRDF** [comment] 2016-07-23 06:30
I can also confirm that it works as intended under sddm. Had some issues with lxdm not properly showing the login screen upon logout. You could still interact with it and log in if you knew were the user and password prompts were.

**Comment by janhieber** [comment] 2016-07-24 09:03
Also Arch with lightdm here, same issue. Works in ZSH shell but crashed when started by i3.

[core.i3bar.lz4.zip](https://github.com/i3/i3/files/380197/core.i3bar.lz4.zip)

**Comment by janhieber** [comment] 2016-07-24 09:48
Forgot to mention: This affected me after doing exactly two thing:

- removed intel DDX driver and switched to modesettings/glamour/DRI3 (HD4400)

- update of following packages: harfbuzz libwebp python2-setuptools libdrm calibre chromium device-mapper x265 ffmpeg ffmpeg2.8 gd gst-plugins-bad harfbuzz-icu perl-xml-libxml hplip htop lib32-libdrm libcdr libebml libmatroska libtorrent-rasterbar lvm2 man-db man-pages nodejs python-setuptools qbittorrent vlc

**Comment by jebrosen** [comment] 2016-07-27 23:19
I found a possibly related bug in lightdm that broke dbus, with EINVAL from libev being a symptom as it is in this situation: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=829557

This commit may have fixed it: https://bazaar.launchpad.net/~lightdm-team/lightdm/1.18/revision/2327


Whether or not this is the exact cause, the bug seems to have been fixed at some point between lightdm 1.18.2 and 1.19.3. I manually installed lightdm 1.19.3 and no longer experience the issue.

**Comment by stapelberg** [comment] 2016-07-30 17:29
@kusayuzayushko Can you please confirm that you’re using LightDM and that the issue is fixed with a different display manager?

**Comment by feynmanliang** [comment] 2016-07-30 21:15
I can confirm this is an issue with i3 and lightdm that is fixed when using
slim.

**Comment by jebrosen** [comment] 2016-08-21 02:00
Arch users (which seem to be most of us), rejoice! lightdm 1.18.3 has been released and was recently packaged. Two of us have confirmed in IRC that lightdm appears to work properly again after `pacman -Syu` to get the latest.

**Comment by fmorgner** [comment] 2016-08-21 07:01
I can also confirm that updating to 1.18.3 fixes the problem on Arch.

**Comment by stapelberg** [comment] 2016-08-21 20:10
Thanks for confirming, I’m closing this issue.

**Closed by stapelberg** 2016-08-21 20:10 UTC
Labels: 4.12, bug

**Comment by krissen** [comment] 2016-12-06 22:04
Hi. I stumbled on the exact same issue. I was not using lightdm though, but entrance. Was going nuts about this issue, troubleshooting with different configs and what have you. But switching to sddm solved the issue.
