### ISSUE TITLE
Assignment not going to correct workspace

### ISSUE THREAD

**Issue by dentafrice** [i3/i3#2060] opened 2015-11-09 03:09 UTC
http://logs.i3wm.org/logs/5668387241852928.bz2

Might be an issue with Spotify, but I figured I'd ask here.  Trying to assign a Spotify window to a specific workspace.. based on the log it looks like the assignment is running and finds a match but the window doesn't get moved to the correct workspace.

Version
```
Binary i3 version:  4.11 (2015-09-30, branch "4.11") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.11 (2015-09-30, branch "4.11") (pid 681)
Loaded i3 config: /home/mingle/.i3/config (Last modified: Sun 08 Nov 2015 06:27:12 PM PST, 2528 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

Assignment
```
set $tag5 "5: music"
assign [class="Spotify"] $tag5
```

Xprop of Spotify Window
```
$ xprop
_NET_WM_ICON(CARDINAL) = 
WM_CLASS(STRING) = "spotify", "Spotify"
WM_NAME(STRING) = "Spotify"
_NET_WM_NAME(UTF8_STRING) = "Spotify"
XdndProxy(WINDOW): window id # 0x2000002
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 0, 0
		window gravity: Static
_NET_WM_PID(CARDINAL) = 20173
WM_LOCALE_NAME(STRING) = "en_US.utf8"
WM_CLIENT_MACHINE(STRING) = "echelon"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING
```

**Comment by Airblader** [comment] 2015-11-09 09:42
Are you running spotify or spotify-beta? The latter would be better, the non-beta client has other bugs anyway. I agree with your interpretation of the log file, unfortunately it's not very clear on where things go wrong.

**Comment by stapelberg** [comment] 2015-11-09 20:16
What’s going wrong here is that spotify isn’t setting the hints when mapping the window:

```
11/08/2015 07:01:23 PM - manage.c:manage_window:165 - Managing window 0x01800001
11/08/2015 07:01:23 PM - window.c:window_update_class:21 - WM_CLASS not set.
11/08/2015 07:01:23 PM - window.c:window_update_name_legacy:95 - WM_NAME not set (_NET_WM_NAME is what you want anyways).
11/08/2015 07:01:23 PM - window.c:window_update_name:61 - _NET_WM_NAME not specified, not changing
[…]
11/08/2015 07:01:23 PM - tree.c:tree_open_con:154 - con = 0x25aeb50
11/08/2015 07:01:23 PM - con.c:con_new_skeleton:52 - opening window
11/08/2015 07:01:23 PM - con.c:_con_attach:149 - Inserting con = 0x263eaa0 after con 0x25ae9e0
11/08/2015 07:01:23 PM - x.c:x_con_init:164 - Adding window 0x004000b2 to lists
11/08/2015 07:01:23 PM - x.c:x_con_init:168 - adding new state for window id 0x004000b2
11/08/2015 07:01:23 PM - manage.c:manage_window:300 - new container = 0x263eaa0
```

What might work is to use `for_window [class="Spotify"] move to workspace $tag5`, since that has an effect even after the window is managed.

I’m closing this issue, since Spotify should set the window hints before calling `MapWindow`. Can you report an upstream bug please?

**Closed by stapelberg** 2015-11-09 20:16 UTC
Labels: 4.11, bug

**Comment by dentafrice** [comment] 2015-11-09 20:21
Will do, thanks for taking a look at this!

**Comment by Airblader** [comment] 2015-11-09 21:21
@dentafrice Again, though, if you're not using spotify-beta, try that first. :)

**Comment by japhir** [comment] 2016-01-12 19:09
I was going crazy over this, I thought I did something wrong. It doesn't work, even with the newest spotify beta. Thanks!

**Comment by chaseadamsio** [comment] 2016-03-27 20:36
I was having the same problem in the past few days. I just upgraded my NixOS channel and saw that there was a version bump to 0.9 to 1.0, so the spotify-beta version is def. the right direction for investigation. Thanks for suggesting @Airblader.

**Comment by vegangaro** [comment] 2017-07-11 16:23
Thanks.
`for_window [class="Spotify"] move to workspace $WS5`

**Comment by h3ct0rjs** [comment] 2017-10-29 00:44
Hi everybody, actually I'm fighting with a similiar situation but this time with virtualbox, How should I handle this ?

**Comment by h3ct0rjs** [comment] 2017-10-29 00:56
Hey, it's me again,  after testing the title option it seems to work properly: 
`for_window [title="Oracle VM VirtualBox Administrador"] move to workspace $WS5
`

**Comment by pavanjadhaw** [comment] 2017-10-29 11:47
I was facing the same problem with spotify.
I was using spotify beta but still faced the problem.
And as far workaround goes, I noticed few glitches so it wasnt solution I was looking for.
What I did is use id as criteria instead of class and it works really well.
You can use xwinifo for getting window id.
In my case I added 

> `assign [id="0x2a00001"] $ws8`

**Comment by Airblader** [comment] 2017-10-29 11:50
The ID is a really bad choice because it can and typically will be different every time. The proper workaround for broken clients such as spotify is to use for_window instead of assign.

**Comment by pavanjadhaw** [comment] 2017-10-29 11:55
Lol right, I got too excited that I have solution I didnt tought about that.
Sorry. :(

**Comment by krompus** [comment] 2018-03-24 14:00
@stapelberg Thanks! `for_window [class="Spotify"] move to workspace $ws9, workspace --no-auto-back-and-forth $ws9` works perfectly.

**Comment by Aster89** [comment] 2018-06-24 14:44
I have a similar problem: if I have `assign [class="^qutebrowser$" title="test"] → $ws2` the browser invariably opens on the current workspace, whereas if I change it to `for_window [class="^qutebrowser$" title="test"] move to workspace $ws2`, the browser moves to workspace 2 when I search for `test` (after irritatingly opening in the current workspace).

So it seems the problem is possibly related to the one stated by @stapelberg. Is it a bug and I should I report this to `qutebrowser`'s team, or is it unavoidable that this happens since I'm not checking `class` but `title`?

**Comment by hk3wxy** [comment] 2020-07-09 21:59
>What might work is to use for_window [class="Spotify"] move to workspace $tag5, since that has an effect even >after the window is managed.
>

Thank you!
