### ISSUE TITLE
[Feature request] Add support for NETWM_FULLSCREEN_MONITORS allowing i3 to use multiple monitors inside a VMware virtual machine

### ISSUE THREAD

**Issue by kinware** [i3/i3#2258] opened 2016-03-13 09:26 UTC
For people running i3 under a virtual machine in VMware multiple monitors does not work.The reason seems to be that VMware uses the NETWM_FULLSCREEN_MONITORS window manager hint instead of using xrandr.

Googling a bit on this seems to indicate that other window managers have added support without too much trouble, but I don't know how this applies to i3. The partial "Xinerama" support in i3 might be helpful, possibly.

Would this support be accepted into i3 if implemented?

Any developer(s) interested in working on this feature, or providing pointers on how to go about implementing support?

More info on this from VMware staff (?):

https://communities.vmware.com/thread/198341

Specification of the NETWM_FULLSCREEN_MONITORS event:

https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html#idm140200472531472

Test program:

https://bugzilla.gnome.org/show_bug.cgi?id=414476

**Comment by Airblader** [comment] 2016-03-13 14:19
I am 100% certain that we talked about this before, but I can't seem to find it right now. It may have been on the mailing list? Anyway, one problem I remember was this:

> The indices are from the set returned by the Xinerama extension.

How do we get those indices without Xinerama? Xinerama is outdated and while i3 does support it as a fallback, we generally want to use randr. So how do we get those indices without using Xinerama? 

The second problem is that we currently cannot fulfill this property. i3 supports fullscreen on a single or on all outputs, but not on arbitrary subsets of all outputs.

**Comment by Airblader** [comment] 2016-03-13 21:30
Duplicate of #2116

**Closed by Airblader** 2016-03-13 21:30 UTC
Labels: enhancement
