### ISSUE TITLE
[Feature Request] Command for focus_on_window_activation

### ISSUE THREAD

**Issue by jdorel** [i3/i3#3687] opened 2019-04-17 19:16 UTC
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Currently, focus_on_window_activation is not a command, so it can't (or at least it doesn't) work when using 'for_window <criteria>'

## Desired Behavior

I would like to disable focus_on_window_activation for a specific window (my RSS Reader)

**Comment by Airblader** [comment] 2019-04-17 19:54
Duplicate of #2855

**Closed by Airblader** 2019-04-17 19:54 UTC
Labels: enhancement
