### ISSUE TITLE
[feature request] i3-msg exit code

### ISSUE THREAD

**Issue by Niserd** [i3/i3#2194] opened 2016-02-05 18:42 UTC
Hello everybody.
I noticed, that even if i3-msg returns [{"success":false}], it still has exit code "0" which means "success", so that it is impossible to use something like "i3-msg .... || ...." and one has to compare strings (see https://github.com/i3/i3/issues/1809). It would be great if somebody implemented correct exit code handling for i3-msg.

**Comment by stapelberg** [comment] 2016-02-05 19:44
duplicate of https://github.com/i3/i3/issues/1639

**Closed by stapelberg** 2016-02-05 19:44 UTC
Labels: enhancement
