### ISSUE TITLE
Upload file popup (for Chrome and Firefox) broken

### ISSUE THREAD

**Issue by mrattfeldt** [i3/i3#3345] opened 2018-08-01 08:56 UTC
## I'm submitting a…

<pre>
[ x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

When attempting to upload file to Chrome (or Firefox) the popup is totally white and covers the whole screen. See the attached screen cast.

## Expected Behavior

A floating window for the file upload should appear.

## Reproduction Instructions

Start Chrome web browser and go to a site for uploading a file. Select 'Choose file'.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 

Binary i3 version:  4.15 (2018-03-10) © 2009 Michael Stapelberg and contributors
</pre>

<pre>
# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout some time, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see https://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod4

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:monospace 8

# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
#font pango:DejaVu Sans Mono 8

# Before i3 v4.8, we used to recommend this one as the default:
# font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
# The font above is very space-efficient, that is, it looks good, sharp and
# clear in small sizes. However, its unicode glyph coverage is limited, the old
# X core fonts rendering does not support right-to-left and this being a bitmap
# font, it doesn’t scale on retina/hidpi displays.

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return exec konsole

# kill focused window
bindsym $mod+Shift+q kill

# start dmenu (a program launcher)
bindsym $mod+d exec ~/scripts/dmenu_run
# There also is the (new) i3-dmenu-desktop which only displays applications
# shipping a .desktop file. It is a wrapper around dmenu, so you need that
# installed.
# bindsym $mod+d exec --no-startup-id i3-dmenu-desktop

# change focus
bindsym $mod+j focus left
bindsym $mod+k focus down
bindsym $mod+l focus up
bindsym $mod+semicolon focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+j move left
bindsym $mod+Shift+k move down
bindsym $mod+Shift+l move up
bindsym $mod+Shift+semicolon move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+h split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+d focus child

# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

# switch to workspace
bindsym $mod+1 workspace $ws1
bindsym $mod+2 workspace $ws2
bindsym $mod+3 workspace $ws3
bindsym $mod+4 workspace $ws4
bindsym $mod+5 workspace $ws5
bindsym $mod+6 workspace $ws6
bindsym $mod+7 workspace $ws7
bindsym $mod+8 workspace $ws8
bindsym $mod+9 workspace $ws9
bindsym $mod+0 workspace $ws10

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace $ws1
bindsym $mod+Shift+2 move container to workspace $ws2
bindsym $mod+Shift+3 move container to workspace $ws3
bindsym $mod+Shift+4 move container to workspace $ws4
bindsym $mod+Shift+5 move container to workspace $ws5
bindsym $mod+Shift+6 move container to workspace $ws6
bindsym $mod+Shift+7 move container to workspace $ws7
bindsym $mod+Shift+8 move container to workspace $ws8
bindsym $mod+Shift+9 move container to workspace $ws9
bindsym $mod+Shift+0 move container to workspace $ws10

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'"

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym j resize shrink width 10 px or 10 ppt
        bindsym k resize grow height 10 px or 10 ppt
        bindsym l resize shrink height 10 px or 10 ppt
        bindsym semicolon resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape or $mod+r
        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}

bindsym $mod+r mode "resize"

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
        status_command i3status
        output eDP1
}

# Move workspace to other output
bindsym $mod+m move workspace to output left

# Start program launcher gmrun
bindsym $mod+Shift+d exec gmrun

# Screen brightness
bindsym XF86MonBrightnessUp exec light -A 5
bindsym XF86MonBrightnessDown exec light -U 5

# Volume
bindsym XF86AudioRaiseVolume exec pactl set-sink-volume 0 +10%
bindsym XF86AudioLowerVolume exec pactl set-sink-volume 0 -10%
bindsym XF86AudioMute exec pactl set-sink-mute 0 toggle

# Spotify
bindsym XF86AudioPlay exec dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause
bindsym XF86AudioPrev exec dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous
bindsym XF86AudioNext exec dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next

# lock screen
bindsym $mod+Shift+z exec xscreensaver-command -activate

</pre>

<pre>
Logfile URL:
</pre>

<pre>
- Linux Distribution & Version: Arch Linux
- Are you using a compositor (e.g., xcompmgr or compton): No
</pre>

[cast.ogv.zip](https://github.com/i3/i3/files/2248749/cast.ogv.zip)

**Comment by Airblader** [comment] 2018-08-01 09:12
I cannot reproduce this. Can you please attach a log file as requested?

**Comment by mrattfeldt** [comment] 2018-08-01 09:49
Here it is: https://logs.i3wm.org/logs/5671274802053120.bz2

It was generated after starting i3 and reproducing the problem.

**Comment by mrattfeldt** [comment] 2018-08-01 11:54
I am on a high dpi laptop (Dell XPS 9370) if that helps.

**Comment by mrattfeldt** [comment] 2018-08-03 08:59
More information: the popup window is there, but it is huge so that any input fields and buttons are outside my screen.

**Comment by Airblader** [comment] 2018-08-03 09:04
The window is requesting to have this size:

```
08/01/2018 11:46:16 AM - manage.c:manage_window:166 - Managing window 0x0100000b
08/01/2018 11:46:16 AM - WM_CLASS changed to google-chrome (instance), Google-chrome (class)
08/01/2018 11:46:16 AM - WM_NAME changed to "Open File"
08/01/2018 11:46:16 AM - Using legacy window title. Note that in order to get Unicode window titles in i3, the application has to set _NET_WM_NAME (UTF-8)
08/01/2018 11:46:16 AM - _NET_WM_NAME changed to "Open File"
08/01/2018 11:46:16 AM - window.c:window_update_leader:166 - Client leader changed to 01000001
08/01/2018 11:46:16 AM - window.c:window_update_transient_for:191 - Transient for changed to 0x01200001 (window 0x0100000b)
08/01/2018 11:46:16 AM - window.c:window_update_strut_partial:204 - _NET_WM_STRUT_PARTIAL not set. 
08/01/2018 11:46:16 AM - WM_WINDOW_ROLE changed to "GtkFileChooserDialog"
08/01/2018 11:46:16 AM - WM_HINTS.input changed to "1"
08/01/2018 11:46:16 AM - startup.c:startup_sequence_get:285 - No _NET_STARTUP_ID set on window 0x0100000b
08/01/2018 11:46:16 AM - startup.c:startup_sequence_get:301 - Checking leader window 0x01000001
08/01/2018 11:46:16 AM - manage.c:manage_window:197 - startup workspace = 1
08/01/2018 11:46:16 AM - manage.c:manage_window:247 - Initial geometry: (0, 0, 7391, 5522)   
```

Since it's GTK, it probably somehow remembers a window size setting, so maybe resizing it manually would fix it for next time. In any case, i3 is just honoring what the application is requesting here, thus closing this bug as works as intended.

You can also use [floating_maximum_size](https://i3wm.org/docs/userguide.html#_constraining_floating_window_size) to restrict window sizes for floating windows to more sane values.

**Closed by Airblader** 2018-08-03 09:04 UTC
Labels: 4.15, bug, needs info

**Comment by mrattfeldt** [comment] 2018-08-03 09:51
Thank you so much! It seems you are correct. Setting floating_maximum_size gives the expected size, and then removing that option gives the same, remembered, size.

**Comment by zhang-wenchao** [comment] 2018-08-06 07:34
I also encountered this problem, enter gnome, resize the window
