### ISSUE TITLE
$mod+something bindsyms use wrong keyboard map

### ISSUE THREAD

**Issue by ckafi** [i3/i3#1519] opened 2015-03-04 21:28 UTC
Running i3 version 4.9 on x86_64 Arch Linux.
I use a non-standard keyboard layout called Neo (http://neo-layout.org), so my bindsyms are tailored for that specific layout. But since version 4.9 (4.8 worked fine), the $mod+something bindsyms kind of 'fall through' to the QWERTY layout.
As an example: When I press Super_L+z (in Neo) the action that will be triggered is the action for the Super_L+b (QWERTY) bindsym.
Here is the log. All I did was press Super_L+ü (that would be y in Qwerty) and Super_L+z (b in Qwerty), each four times.
http://logs.i3wm.org/logs/5684453372329984.bz2

**Comment by Airblader** [comment] 2015-03-04 21:35
I don't actually really understand what was done there, but my guess is it could be related: can you check whether your i3 contains commit https://github.com/i3/i3/commit/dcba0b46dd65a519c2fe54fdb2a5d6f3220d0ed4 ?

**Comment by stapelberg** [comment] 2015-03-04 21:38
This is a duplicate of #1302

**Closed by stapelberg** 2015-03-04 21:38 UTC
Labels: 4.9

**Comment by ckafi** [comment] 2015-03-04 21:47
Sorry, didn't see that.
