### ISSUE TITLE
Some windows won't display

### ISSUE THREAD

**Issue by gilbsgilbs** [i3/i3#2939] opened 2017-09-12 18:11 UTC
Output of `i3 --moreversion 2>&- || i3 --version`:

```
$ i3 --moreversion 2>&- || i3 --version                                                                                                         
Binary i3 version:  4.14 (2017-09-04) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.14 (2017-09-04) (pid 4306)o abort…)
Loaded i3 config: /home/me/.config/i3/config (Last modified: Sun 10 Sep 2017 11:09:48 PM CEST, 161187 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```
(I also tried with the latest version from git with the same result)

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5758753487978496.bz2

**What I did:**

- Install avidemux (2.7.0, qt5 gui)
- Open a video
- Change "Video output" to something different than "Copy" (HEVC x265 for instance)
- Click on Filters
- Double click on "Crop" filter

**What I saw:**

- The filter window does not open. (using another WM such as Gnome-Shell works)
- I can't regain focus on avidemux (it's completely frozen, idle). This probably means that avidemux thinks that the window is open when it's not.

**What I expected instead:**

I would expect the filter window to be displayed normally.

**Comment by stapelberg** [comment] 2017-09-18 07:48
I can reproduce this.

The crop filter settings window is briefly opened, then immediately closed by the app — I’m not sure why yet.

This looks like a race condition to me: when I set a breakpoint on xcb_unmap_window, the window correctly appears. When I disable the breakpoint, the window disappears.

**Comment by stapelberg** [comment] 2017-09-18 08:09
The following patch against avidemux solves the issue for me:

```diff
--- avidemux2-2.7.0/avidemux/qt4/ADM_UIs/src/toolkit.cpp.orig	2017-09-18 10:06:11.238712841 +0200
+++ avidemux2-2.7.0/avidemux/qt4/ADM_UIs/src/toolkit.cpp	2017-09-18 10:06:25.150554818 +0200
@@ -9,8 +9,9 @@
 
 void qtRegisterDialog(QWidget *dialog)
 {
-	if (widgetStack.count())
-		dialog->setParent(widgetStack.top(), Qt::Dialog);
+	if (widgetStack.count()) {
+		//dialog->setParent(widgetStack.top(), Qt::Dialog);
+	}
 
 	widgetStack.push(dialog);
 }
```

It’s note-worthy that the [documentation](https://doc.qt.io/qt-5/qwidget.html#setParent-1) `QWidget::setParent` function which avidemux is calling here remarks:

> Warning: It is very unlikely that you will ever need this function. If you have a widget that changes its content dynamically, it is far easier to use QStackedWidget.

@gilbsgilbs Could you report this issue in the avidemux issue tracker please? I’m happy to provide some more details if avidemux upstream requires them, but from i3’s perspective it looks like the dialog window pops up, then unmaps itself.

**Comment by gilbsgilbs** [comment] 2017-09-18 08:58
@stapelberg Thank you very much for spending some time on this. I'll definitely forward the issue to avidemux.

**Comment by gilbsgilbs** [comment] 2017-09-18 11:27
Follow-up: http://avidemux.org/smif/index.php/topic,17992.0.html

**Comment by stapelberg** [comment] 2017-09-18 12:52
Thank you. I’ll close this issue, but feel free to ask us to reopen it if it turns out that i3 is doing something wrong after all.

**Closed by stapelberg** 2017-09-18 12:52 UTC
Labels: 4.14, bug_somewhere_else, reproducible

**Comment by gilbsgilbs** [comment] 2017-09-30 18:34
@stapelberg 

After digging a bit more, I doubt this is only a bug from avidemux. I mean, the way `setParent` is used by avidemux looks indeed weird. However, I'm unsure wheter not showing the window at all is an expected behavior from i3.

Here is a tiny snippet that reproduces the issue:
```C++
#include <iostream>
#include <QtWidgets>

class MainWindow : public QMainWindow {
public:
    MainWindow(QWidget * parent = 0, Qt::WindowFlags flags = 0) {
        QWidget *subDialog = new QWidget();
        subDialog->show();
        subDialog->setParent(this);
    }
};

int main(int argc, char **argv) {
    QApplication app(argc, argv);
    MainWindow window;
    window.show();
    return app.exec();
}
```

The problem is that we call `setParent` after calling `show`. i3 doesn't seem to like this for some reason.

Some random remarks:
- If I remove `setParent` the dialog shows up properly.
- If I call `setParent` before `show`, the dialog shows up properly.
- If I remove `setParent` and set the parent in the constructor directly, the dialog shows up properly.

Could you kindly enlight me on whether this is expected or not (and explain why if possible 👼 ).

Thanks

**Comment by Airblader** [comment] 2017-09-30 18:57
The documentation of `setParent` states

> Note: The widget becomes invisible as part of changing its parent, even if it was previously visible. You must call show() to make the widget visible again.

Doesn't that clarify the issue?

**Comment by gilbsgilbs** [comment] 2017-09-30 19:16
@Airblader Mmh, probably yes. Thanks. I don't know how I forgot that. 🤔 Just tested my snippet on gnome-shell, and it has the same behavior than i3. Maybe I didn't reproduce anything finally. Sorry for the noise.

I still can't figure out why I cannot reproduce the avidemux bug in gnome-shell and this drives me crazy.

**Comment by Airblader** [comment] 2017-09-30 19:17
I don't know the internals here but this could simply be a race condition. If how just maps the window its going to depend on how fast everyone is.

**Comment by gilbsgilbs** [comment] 2017-09-30 19:28
Yup yup yup. gdb confirms the race condition. The bug reproduces or not depending on where you put the breakpoint. I was unsure whether it was on i3's fault or not, and you just made me realize it was most likely not.

Not worth notifying the 133 watchers, so I'm stopping here. Thank you very very much @Airblader .
