### ISSUE TITLE
[enhancement] forced fullscreen

### ISSUE THREAD

**Issue by spudowiar** [i3/i3#1935] opened 2015-09-19 16:56 UTC
I am enquiring about whether a force fullscreen feature would be well recieved. When you use fullscreen in `i3`, it sets the `_NET_WM_STATE` atom to `_NET_WM_STATE_FULLSCREEN` causing EWMH compliant applications to change their UI. My idea would be a non-EWMH compliant command `fullscreen enable|disable|toggle force` allowing you to unfullscreen a YouTube video, for example, without Firefox actually unfullscreening the video (for use as a media player much like how @Airblader uses Chrome and YouTube with sticky windows). I have written the patch but it would be good to have someone who understands the way `i3` works to check it over, if you decide to merge.

**Comment by stapelberg** [comment] 2015-09-19 17:02
duplicate of #1227 (summary: no, we don’t want that)

**Closed by stapelberg** 2015-09-19 17:02 UTC
Labels: enhancement

**Comment by spudowiar** [comment] 2015-09-19 17:15
mea culpa
