### ISSUE TITLE
The "Hide" button of Chrome's screen sharing sticky window doesn't work

### ISSUE THREAD

**Issue by masterAllen** [i3/i3#4954] opened 2022-04-22 12:00 UTC
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

![2022-04-22_19-36](https://user-images.githubusercontent.com/26152844/164709351-db12200f-1148-4a30-a983-80623427f5e9.png)

Click "hide" button and "sharing screen" info window will disappear.

## Expected Behavior

Click "hide" button but nothing happen, the window still exists.

## Reproduction Instructions

1. Share screen in Chrome and there will be a "sharing info" window at the bottom of the screen.
2. Click "hide" button, the window does not disappear.
3. However, the "Stop sharing" button works well.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 4.20.1
</pre>

<details><summary>Config file</summary><pre>
</pre>
</details>

<pre>
Logfile URL: https://logs.i3wm.org/logs/6196326639337472.bz2
</pre>

<pre>
- Linux Distribution & Version: Arch Linux
- Are you using a compositor (e.g., xcompmgr or compton): picom
</pre>

## Other Information
I find the same bug in qtile: https://github.com/qtile/qtile/issues/1974
xprop:
```
_NET_WM_DESKTOP(CARDINAL) = 4294967295
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
I3_FLOATING_WINDOW(CARDINAL) = 1
_NET_WM_WINDOW_OPACITY(CARDINAL) = 4109694196
_NET_WM_STATE(ATOM) = _NET_WM_STATE_ABOVE, _NET_WM_STATE_STICKY
_NET_WM_USER_TIME(CARDINAL) = 1559242
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 657, 1000
		program specified minimum size: 605 by 78
		program specified maximum size: 605 by 78
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x0, 0x0, 0x0
WM_NAME(UTF8_STRING) = "127.0.0.1:5050 is sharing your screen."
_NET_WM_NAME(UTF8_STRING) = "127.0.0.1:5050 is sharing your screen."
XdndAware(ATOM) = BITMAP
_NET_WM_ICON(CARDINAL) = 	Icon (128 x 128):
	(not shown)

_NET_WM_BYPASS_COMPOSITOR(CARDINAL) = 2
_GTK_HIDE_TITLEBAR_WHEN_MAXIMIZED(CARDINAL) = 1
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_PID(CARDINAL) = 7100
WM_CLIENT_MACHINE(STRING) = "allen-hong"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING, _NET_WM_SYNC_REQUEST
```

**Comment by Airblader** [comment] 2022-04-22 17:20
From the linked issue I assume the Hide button wants to minimize the window. However, i3 does not support minimizing windows because we have no reasonable way of doing so. A long time ago we tried to implement this the only reasonable way we could think of (https://github.com/i3/i3/commit/136b3e345bfde637d3270eafaa2d8aa3555cc3d5), but this caused issues with some clients and was subsequently reverted and now just reverts the state back to normal during #3421 for some compatibility with Wine.

I'm going to close this as working as intended, but please feel free to start a discussion if there is more to say here.

**Closed as completed by Airblader** 2022-04-22 17:20 UTC
Labels: bug, 4.20

**Comment by simonfontana** [comment] 2022-12-21 21:33
Found a workaround to hide the annoying pop-up.

```
# Hide Teams sharing pop-up as much as possible. Too low negative number will
# reset the window to it's default position, -55 px works for 1920x1080 screen.
for_window [floating_from="auto" title=" is sharing your screen.$"] border none, sticky enable, move position 0 px -55 px
```
