### ISSUE TITLE
some way to config i3 to keep  the status bar visible when window enters full screen mode 

### ISSUE THREAD

**Issue by zjj** [i3/i3#4111] opened 2020-05-29 07:06 UTC
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

the status is invisible while a window enters full screen mode

## Desired Behavior

a config to enable that I could see the status bar while the window enters full screen mode.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.12 (2016-03-06, branch "4.12") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.12 (2016-03-06, branch "4.12") (pid 6732)
Loaded i3 config: /home/pi/.config/i3/config (Last modified: Thu 27 Jun 2019 05:14:08 PM CST, 29108887 seconds ago)
</pre>

<pre>
- Linux Distribution & Version: CentOS Linux release 7.8.2003 (Core)
- Are you using a compositor (e.g., xcompmgr or compton):
</pre>

**Comment by Airblader** [comment] 2020-05-29 07:23
Thanks for opening this issue! Fullscreen by definition means taking up the entire space and this is not something we can or want to change. You're looking for maximization, which is a duplicate of #2107.

**Closed as completed by Airblader** 2020-05-29 07:23 UTC
Labels: enhancement
