### ISSUE TITLE
Icons in window titles

### ISSUE THREAD

**Issue by Harliff** [i3/i3#3883] opened 2019-12-17 22:30 UTC
## I'm submitting a…
[x] Feature Request

## Current Behavior
When you open lot of tabs, they looks very similar. You need to read the heading text to determine where is (for example) a terminal and where is a browser (spreadsheet/text/presentation/pdf//mail/etc). 

## Desired Behavior
I'd like to see small icon in from of every tab.

## Working sample
The required functionality was made by user mickael9 (see https://github.com/mickael9/i3-window-icons). I've used this path for about a year, but now I've give it up due to regular crashes of patched i3wm. It was based on release 4.14.1 and now outdated.

## Huh?
May you analyze the code (https://github.com/mickael9/i3-window-icons), maybe rewrite it and include into mainline?

**Comment by Airblader** [comment] 2019-12-17 22:39
Duplicate of #905

**Closed by Airblader** 2019-12-17 22:39 UTC
Labels: enhancement
