### ISSUE TITLE
Window focusing issue when moving mouse between X11 displays (:0.x)

### ISSUE THREAD

**Issue by i336** [i3/i3#2297] opened 2016-04-14 02:59 UTC
**Output of `i3 --moreversion 2>&- || i3 --version`**:

```
Binary i3 version:  4.12 (2016-03-06, branch "4.12") Â© 2009 Michael Stapelberg and contributors
Running i3 version: 4.12 (2016-03-06, branch "4.12") (pid 2599)
Loaded i3 config: /home/i336/.config/i3/config (Last modified: Sat Mar 26 18:24:51 2016, 1624298 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

**URL to a logfile as per http://i3wm.org/docs/debugging.html**:

```
$ DISPLAY=:1.0 i3-dump-log ...
http://logs.i3wm.org/logs/5764640680181760.bz2
$ DISPLAY=:1.1 i3-dump-log ...
http://logs.i3wm.org/logs/5657903226683392.bz2
```
**What I did:**

Move my mouse from one discrete X11 screen to another (for example, :0.1 > :0.0)

**What I saw:**

The window on the target X screen does not get focused when I move my mouse over it.

I believe I have focus-follows-mouse enabled: i3 tracks my mouse cursor and focuses the window under it at all times, except when moving between X screens.

At the moment, I must either...

- move the mouse from the initial window I touch on entering the target screen and into another window, or

- touch the titlebar of the window I want focused with my mouse

...for a focus change event to occur. (With the first method, if it's the first window I reached that I wanted focused, I have to move the mouse back to that window again.)

**What I expected instead:**

For the window on the target X screen to focus correctly the moment I mouseover it.

**How to reproduce this issue with perfect consistency using the i3 version documented above**:

Here's the configuration I used to produce the above logs (listed without `$` characters for easy copypasting)

```
Xephyr :0 -screen 640x480 -screen 640x480 &q
DISPLAY=:0.0 i3 --shmlog-size=26214400 &
DISPLAY=:0.1 i3 --shmlog-size=26214400 &
DISPLAY=:0.0 xterm & DISPLAY=:0.0 xterm &
DISPLAY=:0.1 xterm & DISPLAY=:0.1 xterm &
```

I arranged the Xephyr windows side-by-side, then moved the mouse between the two `xterms` that are closest together.

The cursor remained stuck in one of the terminal windows until I moved into a different `xterm` window on a particular screen.

For a reference of what I consider to be correct/working/sane behavior, if I configure Openbox with `<followMouse>yes</followMouse>` in `rc.xml` and run it inside Xephyr, it tracks my mouse and focuses the window my mouse cursor is under regardless of how I'm traversing X11 displays.

I would really appreciate some ideas on quick-hack fixes - unfortunately trying to force-focus the "correct" active window using `xdotool` has no effect.

**Comment by i336** [comment] 2016-04-14 03:31
I found a solution!

```
xdotool search --name --onlyvisible container behave %@ mouse-enter windowfocus   
```

Totally shoulda explored this a long time ago. That'll teach me! (I switched to i3 about a month ago, was starting to crazy xD)

Well, I'm sorted for the time being, although it'll be nice when i3 itself is fixed.

**Comment by Airblader** [comment] 2016-04-14 07:08
This is a duplicate of #2216 and #2082.

If you find a clean way to implement this, please document that proposal in the original ticket and we can consider reopening it there.

**Closed by Airblader** 2016-04-14 07:08 UTC
Labels: 4.12

**Comment by i336** [comment] 2016-04-14 07:14
Woops, should have searched the issue list.
