### ISSUE TITLE
new commands for splitting tabbed/stacked containers

### ISSUE THREAD

**Issue by jerojasro** [i3/i3#3971] opened 2020-03-08 20:58 UTC
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Splitting tabbed/stacked containers is too cumbersome currently: if I want two tabbed containers, side by side, I have to:

  * Open a couple of windows, and change the window layout to use a horizontal container.
  * Focus the left pane, and press `$mod+v` to force the creation of a new container.
  * Press `$mod+w` to change the container type to tabbed.
  * Repeat the last two steps for the right pane.

## Desired Behavior
I would like a single command to do this; if I'm in a tabbed/splitted container with two or more windows, this new command should do the following when executed:

  * split the space used by the current container in two (horizontally or vertically, depending on what option the command received).
  * create two new tabbed/splitted containers.
  * put the currently-focused window in one of these containers, and the other windows in the other container.

This new command aims to mimic the functionality of the notion window manager: notion has frames, where windows are shown; multiple windows are added as tabs to the currently-focused frame, and it is possible to bisect horizontally or vertically a frame.

I've already implemented this for i3 as a new command (`bisect v|h`), and I'm currently using it;  
please check the video at https://devnull.li/~jerojasro/tmp/bisect.webm for a demonstration of the behaviour of this new feature.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.18-20-g47be3641 (2020-02-24, branch "next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.18-20-g47be3641 (2020-02-24, branch "next") (pid 1927)
Loaded i3 config: /home/jerojasro/.config/i3/config (Last modified: dom 01 mar 2020 16:33:44 -05, 599594 seconds ago)

The i3 binary you just called: /usr/local/bin/i3
The i3 binary you are running: i3
</pre>

**Comment by jerojasro** [comment] 2020-04-04 23:33
I've created a pull request for the feature: https://github.com/i3/i3/pull/3988 

I dragged my feet about creating it because I wanted to write, or at least run, the tests, but bootstrapping the test environment is failing for me, I'm looking into that.

In the meantime, though, here is the code.

**Comment by orestisfl** [comment] 2021-01-12 09:33
Duplicate of #4207

If it is not 100% duplicate of the other issue, we will not be looking to further extend i3's complexity on this domain:

> We are generally happy with the current feature set of i3 and instead focus on maintenance such as stability and fixing bugs. New features will rarely be considered if they require additional configuration and/or commands, or if they add significant complexity (either through the exposed configuration or mental complexity) to the project.

https://github.com/i3/i3/blob/next/.github/CONTRIBUTING.md

**Closed by orestisfl** 2021-01-12 09:33 UTC
Labels: enhancement, requires-configuration
