### ISSUE TITLE
i3 crashes when starting Steam

### ISSUE THREAD

**Issue by lluchs** [i3/i3#2128] opened 2015-12-26 11:07 UTC
i3 4.11 crashes when starting Steam, while the "Connecting to Steam account" window is shown.

Logfile with minimal configuration: http://logs.i3wm.org/logs/5631131353350144.bz2

Pressing "b" on the crash dialog just saves a file containing "No stack.".

This seems to be similar to the previous issue #1337 / #1338, but with two monitors. The issue appeared after upgrading to i3 4.11 (from 4.10.4).

[Apparently, I'm not the only one with this problem.](https://www.reddit.com/r/i3wm/comments/3y2uzx/does_i3wm_work_with_steam/cybj0zv?context=3)

**Comment by LuaKT** [comment] 2015-12-26 14:12
I'm that other person with this issue.

Using i3 4.11 on Antergos with 3 monitors.
Debug logfile: http://logs.i3wm.org/logs/5756749483081728.bz2
The crash dump from "b" also just gives "No stack."

Steam log: http://pastebin.com/BWNNCx7T

The issue is inconsistent, sometimes I can start Steam fine without it crashing. It happens more frequently when I try and start Steam at startup in my config file.
Also, Steam doesn't crash when i3 crashes. It continues to load fine.

**Comment by Airblader** [comment] 2015-12-26 15:02
Since it doesn't happen in 4.10.4, can you please run a git bisect to identify the commit that broke it?

**Comment by Airblader** [comment] 2015-12-26 19:28
It looks like it might be memory corruption:

````
12/26/2015 11:40:51 AM - con.c:con_is_floating:446 - checking if con 0x1c3cef0 is floating
12/26/2015 11:40:51 AM - tree.c:tree_close:355 - not focusing, was not mapped
12/26/2015 11:40:51 AM - con.c:con_on_remove_child:1608 - on_remove_child
12/26/2015 11:40:51 AM - con.c:con_on_remove_child:1616 - not handling, type = 2, name = content
12/26/2015 11:40:51 AM - workspace.c:workspace_update_urgent_flag:806 - Workspace urgency flag changed from 43 to 0
12/26/2015 11:40:51 AM - ipc.c:dump_node:240 - About to dump unknown container type=993551988. This is a bug.
12/26/2015 11:40:51 AM - sighandler.c:handle_signal:292 - i3 crashed. SIG: 6
```

**Comment by Airblader** [comment] 2015-12-26 19:40
Can you please also try updating to the current development branch to see if the issue persists?

**Comment by lluchs** [comment] 2015-12-26 21:08
It's hard to bisect as the crash seems to be somewhat random - at least when restarting Steam over and over. I compiled and installed the development branch now and will report back tomorrow.

The i3 from git didn't crash when starting Steam, but after switching back to 4.11, i3 didn't crash either. I think it never crashes when you're already on the workspace the main Steam window is moved to, but I haven't found a way to make it crash reliably.

**Comment by LuaKT** [comment] 2015-12-27 01:32
I also got development to crash. Here is my log. 
http://logs.i3wm.org/logs/5146118144917504.bz2

**Comment by Airblader** [comment] 2015-12-27 01:46
Thanks. Since you have dev compiled, please retry getting a backtrace. Also, can you just keep restarting Steam to see how often it crashes? That way we can figure out whether a bisect is feasible if you try starting Steam x times per iteration. 

You can also try to bring i3 to crash and while the crash dialog is open (don't close it!), switch to another TTY and type "sudo gdb $(which i3) (pidof i3)" and then "bt full" to see if you can see a backtrace there. 

We appreciate your help.

**Comment by LuaKT** [comment] 2015-12-27 02:24
The backtrace returns "No Stack" still. Also the same message when using GDB in another TTY.

i3 crashes almost every time when you run it for the first time that session. After that it happens infrequently.

Have just done a git bisect and 6a5d5612356d8c40a8ce4034813239eddb7e2044 is the first bad commit. I'm going to run it again to check.

**Comment by Airblader** [comment] 2015-12-27 02:43
Thanks, the to very useful. If you can confirm that reverting that commit fixes the crash, I'll look into it as soon as I have time.

**Comment by LuaKT** [comment] 2015-12-27 02:51
Just ran it again and landed back at the same commit.

**Comment by lluchs** [comment] 2015-12-27 13:54
This commit makes sense. When starting Steam, you can shortly see the Steam workspace flashing red before the "Connecting to Steam" window appears.

**Comment by Airblader** [comment] 2015-12-27 16:43
Can you please try to append this patch to the development branch to see if it fixes the issue?

````
diff --git a/src/workspace.c b/src/workspace.c
index dc0a596..d24b9c9 100644
--- a/src/workspace.c
+++ b/src/workspace.c
@@ -790,6 +790,9 @@ static bool get_urgency_flag(Con *con) {
  *
  */
 void workspace_update_urgent_flag(Con *ws) {
+    if (ws == NULL)
+        return;
+
     bool old_flag = ws->urgent;
     ws->urgent = get_urgency_flag(ws);
     DLOG("Workspace urgency flag changed from %d to %d\n", old_flag, ws->urgent);

```

**Comment by LuaKT** [comment] 2015-12-27 17:54
Can't recreate the crash since applying this patch, will let you know if it happens again.

Thanks!

**Comment by Airblader** [comment] 2015-12-27 18:04
Thanks for testing and your support with everything. I'll prepare a pull request to get the fix merged.

**Closed** 2015-12-29 10:44 UTC
Labels: 4.11, bug
