### ISSUE TITLE
Some keybindings does not work when num lock is enabled

### ISSUE THREAD

**Issue by KabbAmine** [i3/i3#2418] opened 2016-08-06 12:34 UTC
Output of `i3 --moreversion 2>&- || i3 --version`:

```
Binary i3 version:  4.12-118-g155f034 (2016-08-03, branch "gaps-next") © 2009 Michael Stapelberg and contributors
(Getting version from running i3, press ctrl-c to aborRunning i3 version: 4.12-118-g155f034 (2016-08-03, branch "gaps-next") (pid 2882)
Loaded i3 config: /home/k-bag/.i3/config (Last modified: sam. 06 août 2016 15:20:19 MSK, 289 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

The logfile: _http://logs.i3wm.org/logs/5719570367119360.bz2_

**What I did:**

- Use i3 with the default `/etc/i3/config` file
- Enable numpad
- Launch `resize` mode with `$mod+r`
- Press `escape` to quit the mode

**What I saw:**

Nothing, the `escape` key is not taken account.

**What I expected instead:**

Quit the `resize` mode when pressing `escape`.

**Notes**

Note that a lot of combinaisons does not work when num lock is enabled (All keybindings where `shift` is involved, e.g `$mod+shift+r` to restart i3). 
This behavior started after d77d40173aa

**Comment by stapelberg** [comment] 2016-08-06 12:40
Thanks, will take a look in the next few days. Which keyboard layout are you using (`setxkbmap print`)?

**Comment by KabbAmine** [comment] 2016-08-06 12:43
`fr` most of the time, but the issue occurs when using `us`, `ru` or `ar`

**Comment by rosshadden** [comment] 2016-08-08 03:41
I don't know how you narrowed this down to `Numlock`, but I have the same issue.  I never would have figured out that was even remotely related.

I use `dvorak`, though this seems to be a problem when using `us` for me as well.

It might be helpful to be more specific, though.  These are the `setxkbmap` options I use:

```sh
setxkbmap \
	-layout us,us \
	-variant dvorak, \
	-option \
	-option grp_led:caps \
	-option grp:shifts_toggle \
	-option keypad:pointerkeys \
	-option compose:sclk \
	-option ctrl:nocaps
```

**Comment by KabbAmine** [comment] 2016-08-08 10:00
> I don't know how you narrowed this down to Numlock, but I have the same issue. I never would have figured out that was even remotely related.

No magic here :smile:  The issue started after the commit d77d4017 which is related to numlock.

**Comment by pjozog** [comment] 2016-08-14 22:30
Same problem here.  Standard US keyboard.  d77d40173aae250d2e5ba86a8bce7a6e857cbc67 is the culprit.

**Comment by joaolrpaulo** [comment] 2016-08-16 10:13
+1, exactly same problem here on US or PT keyboard.

**Comment by Xeollron** [comment] 2016-08-26 16:25
+1, Using the shift modified character in i3 config (Q instead of q) works when numlock is enabled.

**Comment by Airblader** [comment] 2016-09-02 05:48
This has been affecting a lot of people, I see it being reported in other places as well. We should really get this fixed with 4.13.

**Comment by stapelberg** [comment] 2016-09-02 07:03
Yeah, I want to get it fixed, but finding the time is hard.

**Comment by waplet** [comment] 2016-09-08 09:55
+1, with "lv" keyboard also does not work;
But putting two binds width "q" and "Q" aren't allowed in config.

**Comment by nmschulte** [comment] 2016-09-08 22:47
More data; I experience this issue w/ numeric lock as well (`4.12-97-g59c070b (2016-09-05, branch "next")`):

```
nmschulte@desmas-l:~$ setxkbmap -print
xkb_keymap {
	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
	xkb_types     { include "complete"	};
	xkb_compat    { include "complete"	};
	xkb_symbols   { include "pc+us(altgr-intl)+inet(evdev)"	};
	xkb_geometry  { include "pc(pc104)"	};
};
nmschulte@desmas-l:~$ setxkbmap -query
rules:      evdev
model:      pc104
layout:     us
variant:    altgr-intl
```

**Comment by nmschulte** [comment] 2016-09-08 22:50
I'm still working the RandR 1.5 changes (took notes on the airplane, need to realize them via git still), but looking at the commit in question, this oughtn't be too bad to figure.  I guess this part needs review:

> we now check whether the key has the same meaning when NumLock is enabled.

**Comment by waplet** [comment] 2016-09-09 05:44
@nmschulte I checked they keycodes using "xev" but they did match.

**Comment by nmschulte** [comment] 2016-09-09 16:28
I did the same and saw the same things too.

I'm going to add more diagnostic to the src and take a closer look.

**Comment by nmschulte** [comment] 2016-09-09 21:11
I added a few more logging lines (`"NMSBIND"` prefix), but I don't think they're important.  Looking at the log, the "automatic numlock fallback" seems to be skipped for all of the keys I would expect it not to:

```
bindings.c:translate_keysyms:468 - group = 0, event_state_mask = 13, &2 = no, &3 = yes, &4 = yes
bindings.c:add_keycode_if_matches:369 - NMSBIND [47 (0x3b)]: Adding non-NumLock bindings
bindings.c:add_keycode_if_matches:386 - NMSBIND [47 (0x3b)]: Checking NumLock keysym vs keysym
bindings.c:add_keycode_if_matches:401 - Skipping automatic numlock fallback, key 47 resolves to 0x3a with numlock
bindings.c:translate_keysyms:535 - state=0xd, cfg="semicolon", sym=0x3b → keycodes 47 47 (2)
bindings.c:translate_keysyms:468 - group = 0, event_state_mask = 13, &2 = no, &3 = yes, &4 = yes
bindings.c:add_keycode_if_matches:369 - NMSBIND [44 (0x6a)]: Adding non-NumLock bindings
bindings.c:add_keycode_if_matches:386 - NMSBIND [44 (0x6a)]: Checking NumLock keysym vs keysym
bindings.c:add_keycode_if_matches:401 - Skipping automatic numlock fallback, key 44 resolves to 0x4a with numlock
bindings.c:translate_keysyms:535 - state=0xd, cfg="j", sym=0x6a → keycodes 44 44 (2)
bindings.c:translate_keysyms:468 - group = 0, event_state_mask = 13, &2 = no, &3 = yes, &4 = yes
bindings.c:add_keycode_if_matches:369 - NMSBIND [45 (0x6b)]: Adding non-NumLock bindings
bindings.c:add_keycode_if_matches:386 - NMSBIND [45 (0x6b)]: Checking NumLock keysym vs keysym
bindings.c:add_keycode_if_matches:401 - Skipping automatic numlock fallback, key 45 resolves to 0x4b with numlock
bindings.c:translate_keysyms:535 - state=0xd, cfg="k", sym=0x6b → keycodes 45 45 (2)
bindings.c:translate_keysyms:468 - group = 0, event_state_mask = 13, &2 = no, &3 = yes, &4 = yes
bindings.c:add_keycode_if_matches:369 - NMSBIND [46 (0x6c)]: Adding non-NumLock bindings
bindings.c:add_keycode_if_matches:386 - NMSBIND [46 (0x6c)]: Checking NumLock keysym vs keysym
bindings.c:add_keycode_if_matches:401 - Skipping automatic numlock fallback, key 46 resolves to 0x4c with numlock
bindings.c:translate_keysyms:535 - state=0xd, cfg="l", sym=0x6c → keycodes 46 46 (2)
```

**Comment by nmschulte** [comment] 2016-09-09 22:40
I think I've fixed the issue w/ NumLock and Shift, but I see that there are still problems w/ `bindsym`s in modes and NumLock.  Checkout the PR: #2443.

**Comment by nmschulte** [comment] 2016-09-10 01:20
@stapelberg Is this an issue?  Check out this hunk, from the change prior to d77d401, 3bd5e6e: https://github.com/i3/i3/commit/3bd5e6e5c81b448f9f0ac84454671a871fbfea66#diff-5a430cdd532128e6a86db9a03e2d19a3L154

The prior code called `grab_keycode_for_binding`, but the new code calls `xcb_grab_key` directly, without all of the permutations that `grab_keycode_for_binding` does.  That seems problematic, but maybe I don't understand something.

**Comment by stapelberg** [comment] 2016-09-10 06:59
Sorry, I can’t get into the mindset to think about this issue in depth right now. I’ll update once I have time (hopefully within the next few days).

**Comment by nullbio** [comment] 2016-09-12 08:07
This is affecting me as well.

I have a tenkeyless keyboard, so no numlock key, and I have this issue. One thing I have observed is that if I have this in my config:

`bindsym $mod+shift+q` it does not work. But if I change it to `$mod+shift+Q` it does. A lot of my other binds are not working, for example single letter binds like this:

`bindsym e`. I tried `bindsym E` but that did not work either, so the uppercase only seems to fix things for things with `Shift`.

I have this in my config. This was working fine in regular i3, but not in i3-gaps. The `$mod+Shift+R` in that mode block works, but none of the other binds defined in there work:

```
set $mode_system System (l) lock, (e) logout, (s) suspend, (h) hibernate, (r) reboot, (Shift+S) shutdown, (alt+Shift+R) escape
mode "$mode_system" {
	bindsym l exec --no-startup-id i3exit lock, mode "default"
	bindsym e exec --no-startup-id i3exit logout, mode "default"
	bindsym s exec --no-startup-id i3exit suspend, mode "default"
	bindsym h exec --no-startup-id i3exit hibernate, mode "default"
	bindsym r exec --no-startup-id i3exit reboot, mode "default"
	bindsym Shift+S exec --no-startup-id i3exit shutdown, mode "default"
	bindsym Return mode "default"
	bindsym Escape mode "default"
	bindsym $mod+Shift+R mode "default"
}
```

**Comment by Airblader** [comment] 2016-09-12 08:50
> because I was using i3 before I tried i3-gaps and I did not have this problem

Yes, a lot was recently changed here and i3-gaps is usually up to date with upstream development, so you may see bugs there you don't see in the released i3 version. i3-gaps doesn't modify keybinding behavior at all. :-)

> On that note, does anyone know how I can toggle numlock from the command line?

I think (hope) `xdotool key Num_Lock` should work (otherwise it'll give you an error).

**Comment by nullbio** [comment] 2016-09-12 08:52
@Airblader `numlockx off` worked for me :) Thanks.

**Comment by Airblader** [comment] 2016-09-12 08:52
@nullbio Worked as in made the bug disappear?

**Comment by nullbio** [comment] 2016-09-12 09:07
@Airblader yeah, with toggling numlock through console resulted in every bug disappearing (from what I can tell). I guess some (or all) TKL keyboards ship with numlock enabled by default for some reason. Either that or Ubuntu 16.04 enables it by default, but I have no way to test it because this is the only keyboard I have haha. Thanks.

**Comment by stapelberg** [comment] 2016-09-12 09:11
Looking at this now.

**Comment by stapelberg** [comment] 2016-09-12 10:13
> The prior code called grab_keycode_for_binding, but the new code calls xcb_grab_key directly, without all of the permutations that grab_keycode_for_binding does. Don't you still need to ask for the key w/out the numlock mod, in order to know about those "aliases"? That seems problematic, but maybe I don't understand something. (Like... maybe the whole point of the change in the first place? I'm checking out the referenced issue trail now.)

Instead of blindly grabbing all possible combinations, the new code figures out which additional modifiers are necessary, stores them in the Binding_Keycode TAILQ and then grabs them. So, that’s working as intended.

**Comment by stapelberg** [comment] 2016-09-12 10:14
This issue should now be fixed. If you still encounter keybindings which don’t work with numlock enabled, please let me know how to reproduce (ideally, with the default i3 config aside from one addition, and with the US keyboard layout).

**Closed** 2016-09-12 10:14 UTC
Labels: 4.12, blocks-4.13, bug

**Comment by nullbio** [comment] 2016-09-12 12:36
Thank you @stapelberg

**Comment by ixjlyons** [comment] 2016-09-12 18:50
@stapelberg: With the default config at commit 2244c84, resize mode works correctly, but most regular keybindings with Shift still do not work with NumLock. Here is what I've found for all `Mod1+Shift+...` keybindings in the default config:

**Working**:

- `Mod1+Shift+Left`
- `Mod1+Shift+Down`
- `Mod1+Shift+Up`
- `Mod1+Shift+Right`
- `Mod1+Shift+space`

**Not working**:

- `Mod1+Shift+q`
- `Mod1+Shift+$left`
- `Mod1+Shift+$down`
- `Mod1+Shift+$up`
- `Mod1+Shift+$right`
- `Mod1+Shift+minus`
- `Mod1+Shift+1` (and the rest of the number keys)
- `Mod1+Shift+c`
- `Mod1+Shift+r`
- `Mod1+Shift+e`

**Comment by nmschulte** [comment] 2016-09-12 19:00
Putting the capitalized version of the symbol in the configuration is a work-around for this:
```
bindsym $mod+Shift+Q nop $mod+Shift+Q
```

**Comment by stapelberg** [comment] 2016-09-12 20:06
Thanks for the additional details, I can reproduce the issue with Mod1+Shift+q. @nmschulte’s PR #2443 helps with that, but it breaks the other test case in `t/264-keypress-numlock.t`, so I can’t merge it as-is. Let me see whether I can find a solution that satisfies both cases.

**Comment by stapelberg** [comment] 2016-09-12 20:25
Should be fixed now as well.

**Comment by KabbAmine** [comment] 2016-09-13 08:09
Good job guys, its working as expected for me.
I let you close the issue when everyone will be happy :smile:

**Comment by mpal9000** [comment] 2016-11-20 21:03
Hello, "shrink" and "grow" key bindings stopped working with num lock enabled. 

```
> i3 --version
i3 version 4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors
```

```
mode "resize" {
  # These bindings trigger as soon as you enter the resize mode [jkl;]
  bindcode 44 resize shrink width 10 px or 10 ppt
  bindcode 45 resize grow height 10 px or 10 ppt
  bindcode 46 resize shrink height 10 px or 10 ppt
  bindcode 47 resize grow width 10 px or 10 ppt

  # Go back to normal mode
  bindsym Escape mode "default"
}

# Enter the resize mode [r]
bindcode $mod+27 mode "resize"
```

**Comment by stapelberg** [comment] 2016-11-20 21:04
> Hello, "shrink" and "grow" key bindings stopped working with num lock enabled.

Please see issue #2558

**Comment by mpal9000** [comment] 2016-11-20 21:14
@stapelberg `Mod2+` before the key code did the trick! Now it doesn't work with num lock disabled, but it is not a problem for me. Thank you!

**Comment by timfayz** [comment] 2017-04-09 09:06
I write here because setting `shift+alt` as layout toggle makes i3 unresponsive to any binds with Shift (close the window, reload, etc). I've read the issue but didn't find the clear/final solution to this problem (as well as the https://github.com/i3/i3/issues/2417 which redirected me here). What should I do at the end to fix it?

**Comment by stapelberg** [comment] 2017-05-22 06:39
@timfayz Please open a separate issue with the minimal steps required to reproduce your issue.
