### ISSUE TITLE
Movement While in FullScreen (Feature Request)

### ISSUE THREAD

**Issue by JZL** [i3/i3#2509] opened 2016-10-17 18:52 UTC
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.11 (2015-09-30, branch "4.11") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.11 (2015-09-30, branch "4.11") (pid 1787)
Loaded i3 config: /home/jonah/.config/i3/config (Last modified: Fri 26 Aug 2016 08:57:42 AM EDT, 4513531 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

**What I did:**

 In a tabbed layout, I made one of the windows fullscreen. While still in full screen, if I try to focus left/right (to the other tabbed windows)

**What I saw:**

The left/right window does not appear. I stay at the same fullscreen window.

**What I expected/preferred instead:**
Change to a fullscreen view of the left/right tabbed window. Ideally, this would not be limited to tabbed layouts but for all navigation

(use case: I often have a editor and HTML previewer and prefer to view both full screen but switch between them fast. It might be possible to setup a macro which un-fullscreen-ed, moved left/right, and then fullscreen-ed)

I apologize that I am not on the newest version of i3 and didn't attach a logfile but I thought it would be OK since it is a feature request

**Comment by Airblader** [comment] 2016-10-17 19:11
This would break existing behavior when you are using more than one output since we focus directly to the output in that direction. Also, as you pointed out yourself, this effect can be easily achieved with a script (if you don't care about the multi-output scenario.)

**Comment by Airblader** [comment] 2016-10-17 19:51
Closing as duplicate of #1982. Please refer to the comments there for rationale.

**Closed by Airblader** 2016-10-17 19:51 UTC
Labels: 4.12, enhancement
