### ISSUE TITLE
Feature request handling of new external monitor

### ISSUE THREAD

**Issue by nvanggaard** [i3/i3#2217] opened 2016-02-20 09:18 UTC
I've been using i3 on my laptop running arch for quite some time, and I love it!

My config is made for using both the laptop without any external monitor, and with an external monitor. 

But if I for some reason need to connect a monitor to another port than my standard external monitor uses, I need to change in the config file and reload configuration. 

Therefore I think it would be nice if you somehow could manage this more smoothly. 

It could either be done by adding a feature to i3-msg such that it could change the variables in the config file (reload configuration would still be needed, but it would be faster than editing the config file).

    i3-msg $primaryOutput HDMI2
    
    >>> variable primaryOutput set to HDMI2 

Using this method it would be possible to make a udev event which could change the variables when an external monitor is connected to your computer.

Or it could be done by letting the i3 config file take input from a bash script

config file:

set $primaryOutput self_made_script_which_return_connected_screens

**Comment by Airblader** [comment] 2016-02-20 09:30
Can you elaborate what exactly you use that variable for? Maybe there are better solutions to the actual problem.

> It could either be done by adding a feature to i3-msg such that it could change the variables in the config file (reload configuration would still be needed, but it would be faster than editing the config file).

I think #1197 would make this unnecessary.

> Or it could be done by letting the i3 config file take input from a bash script

Currently, all external calls i3 makes are asynchronous, so it wouldn't work using the same mechanism. I also don't really like blocking on scripts when reading the config. We could also be using #2130 for this (once implemented).

Overall I'm not convinced this isn't addressed in a better way by existing feature requests, but again, it'd be even better to know what you are actually using the output variable for. For example, we also have #555 open, still.

**Comment by nvanggaard** [comment] 2016-02-20 09:45
I'm saying that the proposed solutions are the best, just a way which would solve my specific problem :)

My setup consist of 20 workspaces, where 10 is for my laptops screen, and 10 for the external screen, they are assign to the screen by:

workspace "1: Main" output $primaryOutput

So I was able to change the variable "on the fly" i would just need to reload my config and the screen which the workspace is assigned to would be changed.

I guess #1197 would make it doable, but it the ability to change the variable "on the fly" would make it easier.

**Comment by Airblader** [comment] 2016-02-20 09:47
Your usecase is a duplicate of #555.

**Closed by Airblader** 2016-02-20 09:47 UTC
Labels: enhancement

**Comment by nvanggaard** [comment] 2016-02-20 09:51
No it is not a duplicate of #555 

I want to be able to connect a screen to a random port on my computer and a set of workspaces should automatically be assigned to the screen.

**Comment by Airblader** [comment] 2016-02-20 09:54
Yes, and you do that by assigning those workspaces to all outputs that are in question for this:

````
workspace 10:foo output HDMI-0
workspace 10:foo output VGA-1
```

Which is #555. As for changing variables on the fly, I think using #1197 is plenty sufficient. A config reload is required either way. The only difference to what you propose is that overwriting a file would persist across reboots. I don't think there's a pressing need to avoid it, is there?

**Comment by Airblader** [comment] 2016-02-20 09:59
Besides, if we had an IPC command that allows redefining a variable, but still requires a reload of the config, then that command is pointless since the config will also contain `set $foo bar` somewhere, once again overriding the previously executed command.

**Comment by nvanggaard** [comment] 2016-02-20 10:05
Fair enough, that wasn't what I got from #555 

But that will work in most cases, unless if you connect 2 external monitors to a laptop, and you don't want to use the laptops screen. 

Have honestly not thought about that, but i think it my problem can be solve if #1197 is implemented.
