### ISSUE TITLE
Floating window placement in percent, left and bottom aligned

### ISSUE THREAD

**Issue by cehteh** [i3/i3#3856] opened 2019-11-03 20:33 UTC
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
`move position <x> px <y> px` takes arguments in 'px' which originate in the upper left  corner of the screen.

## Desired Behavior
It would be nice when `move position` also supports 'ppt' or '%' for defining the position.
On similar thought, the coordinates could be reversed to originate in on the right/bottom (which then uses the right/bottom border of a window as well). I suggest to use negative values for that:
 `move position -0 -0` would place a window on the bottom left of the screen.

## Rationale

Using these features makes positioning device independent. I'd like to share my i3 config on different computers which have different geometries. Such features would simplify this a lot.

We have 'ppt' already in the 'resize' command, would be orthogonal to use it on other commands where positions are given as well.

**Comment by orestisfl** [comment] 2021-01-01 20:57
Fixed by https://github.com/i3/i3/pull/4189
Duplicate of https://github.com/i3/i3/issues/3519

**Closed by orestisfl** 2021-01-01 20:57 UTC
Labels: enhancement
