### ISSUE TITLE
discrepancy between mouse position and focused window on mulitple workspace change

### ISSUE THREAD

**Issue by JeffAbrahamson** [i3/i3#2328] opened 2016-04-29 12:52 UTC
Output of `i3 --moreversion 2>&- || i3 --version`:

```
Binary i3 version:  4.12 (2016-03-06, branch "4.12") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.12 (2016-03-06, branch "4.12") (pid 1993)
Loaded i3 config: /home/jeff/.i3/config (Last modified: Sun 13 Mar 2016 08:29:11 CET, 4080004 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

URL to a logfile as per http://i3wm.org/docs/debugging.html:

```
http://logs.i3wm.org/logs/5645056174194688.bz2
```

**What I did:**

I switched from workspace group a to c and back to a. On a, I move the mouse from the left window to the right window. (I have windows (roughly) on the left and right of the right output.)

**What I saw:**

The mouse is over the left window and the focus is on the right window (or vice versa). It seems to be related to where the focus was last on the newly displayed workspace and where the mouse was on the previously displayed workspace for this output.

It seems this only happens when programmatically changing workspaces on two outputs at once.

**What I expected instead:**

Either the mouse should follow the focus or the focus should follow the mouse.

**Comment by Airblader** [comment] 2016-04-29 18:37
> the mouse should follow the focus

http://i3wm.org/docs/userguide.html#_mouse_warping

> the focus should follow the mouse

http://i3wm.org/docs/userguide.html#_focus_follows_mouse

The rest of what you describe is intended behavior. The reason here is that we want to allow users to quickly switch back and forth between workspaces without messing up the focus by setting it to where the mouse is. This would be rather unexpected behavior for most users.

**Comment by JeffAbrahamson** [comment] 2016-04-29 18:43
What I understand from that man entry is that the mouse warps to the center of the focused window on ws switch.  Is that not the behaviour?

What I find unexpected is that the mouse and the focus don't coincide.

**Comment by Airblader** [comment] 2016-04-29 18:59
Mouse warping only occurs when switching workspaces between outputs. I understand that you are switching workspaces on the same output, right? Or am I misunderstanding you?

**Comment by JeffAbrahamson** [comment] 2016-04-29 19:25
Aha, I missed a paste in my issue.  Sorry.  I have two screens, so two outputs.  I have some bindings like this to let me change them as sets.  So the issue is that there are two workspace changes in a row.  If I only change one workspace, this isn't an issue.

    bindsym a  workspace 1; workspace 2;  mode "default"
    bindsym b  workspace 3; workspace 4;  mode "default"
    bindsym c  workspace 5; workspace 6;  mode "default"
    bindsym d  workspace 7; workspace 8;  mode "default"
    bindsym e  workspace 9; workspace 10; mode "default"

(Later I have some code that makes sure that odd workspaces map to the left screen/output, even to the right.)

**Comment by Airblader** [comment] 2016-04-29 19:34
Ah, alright. I'll reopen for now so we can talk about this some more because I'm not convinced anymore my answers are addressing your actual situation.

I'm trying to follow your description in the original post but I think I'm getting lost. Can you maybe describe in individual steps what you are pressing, doing and expecting? And please also describe the layout of your windows in detail. Maybe even use some screenshots. That'd just make it clearer what's going on. :-)

**Comment by Airblader** [comment] 2016-05-19 22:01
@JeffAbrahamson Are you still interested in this?

**Comment by Airblader** [comment] 2016-05-27 19:30
Closing due to inactivity.

**Comment by JeffAbrahamson** [comment] 2016-08-18 07:14
For this example, I have two windows side-by-side on each head.  I'm using workspaces 7-8 (group d) and 9-10 (group e).

I'm not managing to catch the mouse cursor in my screen shots, so I indicate in the comments where it is.  The point is that sometimes the mouse is over one window but the focused window is adjacent.

I could see correct behaviour being to focus the window where the mouse is.  I could also see correct behaviour being to warp the mouse to where the focus is.  I don't think I have an opinion.  It is the discrepancy that I claim is a bug.

![2016-08-18-090726_3840x1200_scrot](https://cloud.githubusercontent.com/assets/1220683/17765064/d3c23fa0-6523-11e6-8afc-a3cbf3b10ac3.png)
![2016-08-18-090753_3840x1200_scrot](https://cloud.githubusercontent.com/assets/1220683/17765066/d3d0032e-6523-11e6-89b3-04408730afcf.png)
![2016-08-18-090858_3840x1200_scrot](https://cloud.githubusercontent.com/assets/1220683/17765065/d3cfe146-6523-11e6-8c18-d8bc56595ac5.png)
![2016-08-18-090932_3840x1200_scrot](https://cloud.githubusercontent.com/assets/1220683/17765067/d3d14b58-6523-11e6-9741-41fc886d430d.png)

**Comment by Airblader** [comment] 2016-08-18 07:19
> It is the discrepancy that I claim is a bug.

A bug is defined by what the intention of the program is. That said, can you please post your config?

**Comment by JeffAbrahamson** [comment] 2016-08-18 07:30
My i3 config is [here](https://github.com/JeffAbrahamson/dotfiles/blob/master/i3/i3/config).

> A bug is defined by what the intention of the program is. That said, can you please post your config?

_Said with an amused and wry smile:_

But since I don't know your intentions on this, I'm free to claim it appears to me to be a bug.  Then you get to clarify your intentions in this corner case that (based on this discussion) appears not yet to have been fully thought through all around.

When I say I believe it's a bug, I mean "I don't find documentation that this is intended behaviour (or not), but I believe it would be rational to question this being intended".  I'm open to a more concise way of saying that that doesn't use the word "bug".

**Comment by Airblader** [comment] 2016-08-18 12:14
;-)

Since your config doesn't contain `mouse_warping none`, this does seem to be a bug at first glance. I have pretty much no time right now to look into this, though, but I'll reopen the issue.

**Comment by JeffAbrahamson** [comment] 2018-11-04 19:29
Consider this:

I have two windows open side-by-side and only one display.  This is true in workspaces 1 and 2.

I hover over the right window in workspace 1 and so focus it.  I switch to workspace 2.  I'm hovering over the right window, and it is in focus.  I move the mouse left and hover over the left window, which is now in focus.

Now I switch back to workspace 1.  The mouse is still over the left window, but the right window is still focused.  I have to click (if that is meaningful) or move the mouse to another window to get focus and mouse to agree.

I think the right behaviour here is that on returning to workspace 1, the left window is now focused (because that's where the mouse is) not the right one (because that's where the mouse was but isn't anymore).

I'm pretty ok with changing the focus to be where the mouse is (the principle of FFM) or warping the cursor (if preserving the previously focused window seems a better priority).  I just find it quite confusing to have a FFM policy and then for the mouse to hover over an unfocused but focusable window.

**Comment by Airblader** [comment] 2018-11-04 19:50
Yes, it is. Closing because it's intended behavior.

**Closed by Airblader** 2018-11-04 19:50 UTC
Labels: 4.12, bug

**Comment by Airblader** [comment] 2018-11-04 19:52
As a further explanation, the reasoning for this behavior is that it avoids unexpected focus changes / mouse warps. I understand that people can feel different about this, but this is the policy we have and want in i3.

**Comment by orestisf1993** [comment] 2018-11-04 19:52
Strictly speaking, the current behavior is the intended one as described in the userguide:

https://i3wm.org/docs/userguide.html#_focus_follows_mouse

> By default, window focus follows your mouse movements **as the mouse crosses window borders**.

https://i3wm.org/docs/userguide.html#_mouse_warping

> By default, **when switching focus to a window on a different output** (e.g. focusing a window on workspace 3 on output VGA-1, coming from workspace 2 on LVDS-1), the mouse cursor is warped to the center of that window.

Rationale: https://github.com/i3/i3/issues/2327#issuecomment-240624080
> On a single monitor this is the intended behavior because it would generally be confusing if moving the mouse on one workspace changes the focus on another, invisible workspace when switching to that one.

The only way to not break current behavior is to extend `mouse_warping` like in https://github.com/i3/i3/pull/2813, https://github.com/i3/i3/issues/2971 or extend `focus_follows_mouse`.

**Comment by JeffAbrahamson** [comment] 2018-11-04 20:04
You're the developers, you get to decide.  So I won't argue with you.

But I think you're focusing to much on mouse warping.  I mentioned that as an "if focus doesn't follow the mouse, the mouse should perhaps follow the focus".  I'm not a fan of warping mice.

I would argue that changing workspace causes the mouse to cross a window border (there's an exit and an entry), not a bizarre teleportation of the mouse into the window in the new workspace.  So the window under the mouse in the newly displayed workspace should be focused.

My opinion.  I really don't understand a FFM policy that believes itself to be in a consistent state when the window under the mouse is focusable but not focused (ignoring discussions about what should happen when windows map and unmap).

**Comment by orestisf1993** [comment] 2018-11-04 20:31
> I would argue that changing workspace causes the mouse to cross a window border (there's an exit and an entry), not a bizarre teleportation of the mouse into the window in the new workspace. So the window under the mouse in the newly displayed workspace should be focused.

IMO, "crossing the border" implies traveling, the mouse should literally "cross" the border. Changing workspaces is more like a teleportation.

> My opinion. I really don't understand a FFM policy that believes itself to be in a consistent state when the window under the mouse is focusable but not focused (ignoring discussions about what should happen when windows map and unmap).

i3 allows other types of switching focus when FFM is enabled. Eg you can use the directional focus commands. The inverse, "if focus doesn't follow the mouse, the mouse should perhaps follow the focus", has been discussed and it was concluded that you should use an external script to implement it: https://github.com/i3/i3/issues/2971#issuecomment-365268904
