### ISSUE TITLE
unassign or assign timeout

### ISSUE THREAD

**Issue by lilydjwg** [i3/i3#4266] opened 2020-11-23 06:38 UTC
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
After `assign`ing something, there is no way to remove that assignment.

## Desired Behavior
A way to make a previous `assign` not effective.

I want this because I want to start up applications and move them to desired workspaces just after I log in, not when I manually start the same application again.

Examples are gvim and firefox. I usually have one instance of each running, but occasionally I need one more instance.

Using `i3-msg` + startup id only works if the startup id can be passed to the application (and supported by the application). This works for me with gvim, but I start firefox with a systemd service (for memory accounting and auto restarting on crash) and it's not easy to pass that on to the service. It's easier to `unassign` rules after a minute instead.

Generally, it would provide an easy way to move expected windows once but not always. Something like `assign once` won't work well because some application (e.g. firefox) may create multiple windows. Something like `assign timeout` will work nice as far as I can imagine.

Thanks to great scriptability of i3 I'm going to write a script to move the windows as they appear, but native support is better.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.18.3 (2020-10-19) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.18.3 (2020-10-19) (pid 2860)abort…)
Loaded i3 config: /home/arch/.config/i3/config (Last modified: 2020年11月23日 星期一 14时12分43秒, 945 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
- Linux Distribution & Version: Arch Linux
- Are you using a compositor (e.g., xcompmgr or compton): picom
</pre>

**Comment by Airblader** [comment] 2020-11-23 06:47
What about using https://i3wm.org/docs/layout-saving.html?

Apart from that this is essentially a duplicate of #4182, I think.

**Comment by lilydjwg** [comment] 2020-11-23 06:56
Yes, the similar will apply for `for_window`. I didn't search that. The discussion in #4182 seems to go off the point however. Reloading config is too overkilling and it will cause flashes as the bar disappears and reappears.

I'll give layout saving a try.

**Comment by lilydjwg** [comment] 2020-11-23 13:43
> What about using https://i3wm.org/docs/layout-saving.html?

It needs to know how many Firefox windows I have beforehand (Tab Groups is gone and I rely on windows to group my tabs). It's possible to read Firefox's last session data and generate a layout file with a script though.

**Comment by orestisfl** [comment] 2021-01-01 21:08
> Thanks to great scriptability of i3 I'm going to write a script to move the windows as they appear, but native support is better.

Since this is possible with the IPC interface I think we'd prefer to not make the assignments code more complex. Read about our recently announced approach to feature requests:

> We are generally happy with the current feature set of i3 and instead focus on maintenance such as stability and fixing bugs. New features will rarely be considered if they require additional configuration and/or commands, or if they add significant complexity (either through the exposed configuration or mental complexity) to the project.

**Closed as completed by orestisfl** 2021-01-01 21:08 UTC
Labels: enhancement, waiting
