### ISSUE TITLE
move workspace doesn't work on 4.17.x version

### ISSUE THREAD

**Issue by LKlemens** [i3/i3#3786] opened 2019-09-02 07:34 UTC
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

I have set `bindsym $mod+m move workspace to output left` in config to moving workspace. 
After upgrade i3-gaps to 4.17.x it stops working - press mod+m doesn't move workspace.
I've double check it and on 4.16.1 works well. 
## Expected Behavior

After press $mod+m workspace moves left.

## Reproduction Instructions

add this line to i3-config `bindsym $mod+m move workspace to output left`
Restart i3
Open two workspaces,
Focus on first workspace.
Press `$mod+m` combination.
On 4.17 nothing happen. 
On 4.16 works. 

## Environment

Output of `i3 --moreversion 2>&-`:
```
Binary i3 version:  4.17.1 (2019-08-30) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.17.1 (2019-08-30) (pid 4486)abort…)
Loaded i3 config: /home/klemens/.config/i3/config (Last modified: Mon 02 Sep 2019 06:40:11 AM CEST, 692 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```
<pre>
i3 version: 4.17.1
</pre>

<pre>

# force_xinerama yes
# popup_during_fullscreen ignore
for_window [class="^.*"] border pixel 1
workspace_layout tabbed
mouse_warping none
# focus_follows_mouse no
workspace_auto_back_and_forth yes
# sticky no

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
        # status_command i3status
        status_command polybar Bar
        tray_output primary
        separator_symbol '//"
        position bottom
        strip_workspace_numbers yes
        mode invisible
}

# border none

# i3 config file (v4)
#
# Please see http://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod4

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return   exec termite # -t shell -e tmux

# kill focused window
bindsym $mod+q kill

# reload the configuration file
bindsym $mod+Shift+c reload
#clipmenu
bindsym $mod+Shift+v exec clipmenu
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-msg exit"

bindsym $mod+m move workspace to output left

</pre>

<pre>
Logfile URL: https://logs.i3wm.org/logs/5736127055003648.bz2
</pre>

<pre>
- Linux Distribution & Version: Arch Linux 5.2.9-arch1-1-ARCH
- Are you using a compositor (e.g., xcompmgr or compton): I use compton
</pre>

**Comment by orestisfl** [comment] 2019-09-02 09:13
(confirmed that this is not gaps-specific: https://github.com/Airblader/i3/issues/316#issuecomment-527025255)

Can you please produce a new log file from a new session following the instructions here: https://i3wm.org/docs/debugging.html. Your file doesn't contain anything.

**Comment by LKlemens** [comment] 2019-09-02 16:56
logs : https://logs.i3wm.org/logs/5736127055003648.bz2

**Comment by orestisfl** [comment] 2019-09-02 17:03
Thanks, can you also paste the output of `xrandr`?

**Comment by LKlemens** [comment] 2019-09-02 17:09
sure
```
xrandr     
Screen 0: minimum 320 x 200, current 1366 x 768, maximum 8192 x 8192
eDP-1 connected primary 1366x768+0+0 (normal left inverted right x axis y axis) 344mm x 193mm
   1366x768      60.06*+
   1280x720      60.00    59.99    59.86    59.74  
   1024x768      60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   960x540       59.96    59.99    59.63    59.82  
   800x600       60.00    60.32    56.25  
   840x525       60.01    59.88  
   864x486       59.92    59.57  
   700x525       59.98  
   800x450       59.95    59.82  
   640x512       60.02  
   700x450       59.96    59.88  
   640x480       60.00    59.94  
   720x405       59.51    58.99  
   684x384       59.88    59.85  
   640x400       59.88    59.98  
   640x360       59.86    59.83    59.84    59.32  
   512x384       60.00  
   512x288       60.00    59.92  
   480x270       59.63    59.82  
   400x300       60.32    56.34  
   432x243       59.92    59.57  
   320x240       60.05  
   360x202       59.51    59.13  
   320x180       59.84    59.32  
VGA-1 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
HDMI-1 disconnected (normal left inverted right x axis y axis)
```

**Comment by orestisfl** [comment] 2019-09-02 17:32
This only lists a single output and the logs agree with this, is the other output active?

**Comment by LKlemens** [comment] 2019-09-02 18:01
no, I use only one screen

**Comment by Airblader** [comment] 2019-09-02 18:39
What do you expect the command to do if you're only one output?

**Comment by LKlemens** [comment] 2019-09-02 19:09
On version 4.16 I could change order of workspace to get closer these ones which I need most.

**Comment by Airblader** [comment] 2019-09-02 19:44
What do you mean with the order? You can influence that by renaming the workspaces with a numeric prefix (`1:foo`) and using `strip_workspace_numbers` to hide those from being displayed.

It seems like this issue is based on using the command for something it isn't intended to do — `move workspace output left` exists to move a workspace from one output to another (the one that is left of the current one).

**Comment by LKlemens** [comment] 2019-09-02 19:56
I use polybar.  I have renamed workspaces to icons. 
I move between workspace by
`bindsym $mod+j workspace prev`
`bindsym $mod+k workspace next`
binding. 
And `move workspace` allows me to move for instance firefox which was the 3th workspace to last 6th position, and thanks to this conversion I could move between 1st workspace (terminal) and 6th workspace (firefox) by one jump.  
Is there another way to do the same?

**Comment by Airblader** [comment] 2019-09-02 20:02
I assume polybar also has an option to strip workspace numbers, so the solution from above should still apply. In fact according to https://github.com/polybar/polybar/issues/126 it does so by default. 

In any case, I'm closing this issue as invalid since the move output command is meant to move workspaces between outputs.

**Closed by Airblader** 2019-09-02 20:02 UTC
Labels: 4.17, bug
