### ISSUE TITLE
Accessibility problem when launch a program using exec.

### ISSUE THREAD

**Issue by peyyman** [i3/i3#3090] opened 2017-12-16 13:00 UTC
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.14.1 (2017-09-24) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.14.1 (2017-09-24) (pid 1719)abort…)

URL to a logfile as per https://i3wm.org/docs/debugging.html:

https://logs.i3wm.org/logs/5747862927310848.bz2

**What I did:**

I have added a key binding to run a custom application written with qt toolkit(This application is designed for visually impaired users and meant to be fully accessible) .Then I pressed that key combination to run the application (Mod1+t).

**What I saw:**

The application launched but it is not accessible and also some of its functionality doesn't work!

**What I expected instead:**
This application has a list of items that user can select one of them. During navigation, the Orca Screen Reader must tell the user which item is selected (via speech). The problem is that Orca is silent in this case. But if I start that application from a terminal everything is ok and Orca speaks all items in that application.

**Comment by Airblader** [comment] 2017-12-16 17:58
Thank you for reporting the issue! i3 isn't actually involved in what happens inside the client window of a program, and, equally important, when launching a program through i3 we only pass that command to the shell and are done with it; any window opening as a result from that goes through the same process as if you had started the process otherwise. Since this isn't an i3 issue, I'm going to close this.

To not leave you hanging: a common issue is the environment in which a program is launched. We pass the command to /bin/sh and typically this means user profiles aren't sourced. So my advice would be to investigate whether the environment is missing something for this to work properly.

If that doesn't help, please report it to the corresponding apps. They can figure out why it isn't working as intended. Though unlikely, if they do find out we are somehow doing  something wrong, we'll at least know what it is. Thank you!

**Closed by Airblader** 2017-12-16 17:58 UTC
Labels: 4.14
