### ISSUE TITLE
Unable to open the right click menu in chromium after a screenshot with flameshot

### ISSUE THREAD

**Issue by mssdvd** [i3/i3#3118] opened 2018-01-14 12:43 UTC
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.14.1 (2017-09-24) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.14.1 (2017-09-24) (pid 654) abort…)
Loaded i3 config: /home/davide/.i3/config (Last modified: Sat 06 Jan 2018 15:39:08 CET, 682969 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

URL to a logfile as per https://i3wm.org/docs/debugging.html:

https://logs.i3wm.org/logs/5656236913590272.bz2

**What I did:**

- I press the Print key which is binded to [flameshot gui](https://github.com/lupoDharkael/flameshot)
- I press the Esc key or I make a screenshot

**What I saw:**

I can't open the context menu with either the right click or the Menu key in chromium.

**What I expected instead:**

After a screenshot the context menu should open as usual.

**Workaround**

The only way to solve temporarily the issue is to unfocus the the browser window.

Refers to [this issue.](https://github.com/lupoDharkael/flameshot/issues/58)

**Comment by Airblader** [comment] 2018-01-14 13:38
This is a duplicate of #3096. You can try running the patch given in #3097 if you want.

**Closed by Airblader** 2018-01-14 13:38 UTC
Labels: 4.14, bug

**Comment by mssdvd** [comment] 2018-01-14 13:52
Thank you!

**Comment by JianleiZhang** [comment] 2018-10-11 08:39
Problem recurrence。
```
Binary i3 version:  4.15.0.1 (03-13-2018) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15.0.1 (03-13-2018) (pid 490)bort…)
Loaded i3 config: /home/jlzhang/.config/i3/config (Last modified: 2018年10月10日 星期三 21时20分26秒, 69362 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

**Comment by harold** [comment] 2023-01-22 15:28
Hi! First, thanks for i3, it's amazing, I've lived inside it for years and it's beautiful and has had a profoundly positive impact on my computing life.

---

I have been encountering the problem in this issue recently --- after taking a screenshot with flameshot, Chrome's context menu (right click) doesn't work: in particular, the menu appears for a split second, and then quickly/surprisingly goes away, any time I click the right mouse button.

Restarting chrome fixes the problem. But the problem recurs reliably after taking another screenshot.

```
$ i3 --moreversion
Binary i3 version:  4.20.1 (2021-11-03) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.20.1 (2021-11-03) (pid 2236)
Loaded i3 config:
  /etc/regolith/i3/config (main) (last modified: Sun 17 Jul 2022 08:36:21 PM MDT, 16289313 seconds ago)
  /usr/share/regolith/i3/config.d/15_base_launchers (included) (last modified: Sun 17 Jul 2022 08:36:21 PM MDT, 16289313 seconds ago)
  /usr/share/regolith/i3/config.d/20_ilia (included) (last modified: Sun 17 Jul 2022 08:36:21 PM MDT, 16289313 seconds ago)
  /usr/share/regolith/i3/config.d/30_navigation (included) (last modified: Tue 27 Sep 2022 03:45:00 PM MDT, 10085994 seconds ago)
  /usr/share/regolith/i3/config.d/35_i3-gaps (included) (last modified: Sun 17 Jul 2022 08:36:21 PM MDT, 16289313 seconds ago)
  /usr/share/regolith/i3/config.d/40_default-style (included) (last modified: Sun 17 Jul 2022 08:36:21 PM MDT, 16289313 seconds ago)
  /usr/share/regolith/i3/config.d/40_next-workspace (included) (last modified: Sun 17 Jul 2022 08:36:21 PM MDT, 16289313 seconds ago)
  /usr/share/regolith/i3/config.d/40_workspace-config (included) (last modified: Sun 17 Jul 2022 08:36:21 PM MDT, 16289313 seconds ago)
  /usr/share/regolith/i3/config.d/55_session_keybindings (included) (last modified: Sun 17 Jul 2022 08:36:21 PM MDT, 16289313 seconds ago)
  /usr/share/regolith/i3/config.d/60_config_keybindings (included) (last modified: Sun 17 Jul 2022 08:36:21 PM MDT, 16289313 seconds ago)
  /usr/share/regolith/i3/config.d/70_bar (included) (last modified: Sun 17 Jul 2022 08:36:21 PM MDT, 16289313 seconds ago)
  /usr/share/regolith/i3/config.d/80_compositor (included) (last modified: Sun 17 Jul 2022 08:36:21 PM MDT, 16289313 seconds ago)
  /usr/share/regolith/i3/config.d/82_rofication-ilia (included) (last modified: Sun 17 Jul 2022 08:36:21 PM MDT, 16289313 seconds ago)
  /usr/share/regolith/i3/config.d/84_ftue (included) (last modified: Sun 17 Jul 2022 08:36:21 PM MDT, 16289313 seconds ago)
  /usr/share/regolith/i3/config.d/86_unclutter (included) (last modified: Sun 17 Jul 2022 08:36:21 PM MDT, 16289313 seconds ago)
  /usr/share/regolith/i3/config.d/88_network-manager (included) (last modified: Sun 17 Jul 2022 08:36:21 PM MDT, 16289313 seconds ago)
  /usr/share/regolith/i3/config.d/90_user-programs (included) (last modified: Sun 17 Jul 2022 08:36:21 PM MDT, 16289313 seconds ago)
  /home/harold/.config/regolith2/i3/config.d/16_keybinds (included) (last modified: Thu 05 Jan 2023 03:24:17 PM MST, 1443637 seconds ago)
  /home/harold/.config/regolith2/i3/config.d/50_resize-mode (included) (last modified: Tue 27 Sep 2022 04:08:33 PM MDT, 10084581 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

Anything else I can provide to help debug?

**Comment by voylin** [comment] 2024-12-16 06:05
Been experiencing the same bug, not certain what the status is on this, any updates?

**Comment by harold** [comment] 2024-12-16 15:31
This still gets me almost every day. I have found that if I move the chrome window to a different virtual desktop and then move it back, then the context menu is available again. 

I’ve gotten surprisingly fast at the key combinations needed to do this. 

I haven’t upgraded i3 in a long time. Hoping to make time to upgrade soon. Hopefully this is fixed. 

Thanks again for i3 - it’s wonderful and a key part of my workflows and daily life. 🙇🏻

**Comment by voylin** [comment] 2024-12-17 08:07
I don't have this issue with FireFox, only Chromium. So ... thinking of just changing as it happens too frequently that it's a pain. Same thing happens when using Godot though, so probably an OpenGL issue?
