### ISSUE TITLE
i3bar does not display workspace name if it contains certain special characters (at least < and &)

### ISSUE THREAD

**Issue by Adaephon-GH** [i3/i3#1941] opened 2015-09-21 09:21 UTC
[This question on superuser.com](http://superuser.com/questions/966706/i3-window-manager-ampersand-in-commands) describes an issue that workspace names seem to be empty when they contain a `&` character.

I did some testing and found that the workspaces seem to be (re-)named correctly but *i3bar* does not display them if they contain `&` or `<`. I used `i3-msg -t get_workspaces` and `i3-msg -t get_outputs` to check the what *i3* thinks the names are, and there the workspace name shows up as "Mail&News" while *i3bar* just shows an empty string. It does matter whether the workspace is actually renamed or created with that name in the first place.

There may be other characters that do not work but at least naming a workspace  ``_[]^\/{}*#$|~`!>=()-:@+%;,."'`` (of course `\` and `"` need to be quoted) seems to work without issue. 

I tested it on Ubuntu 14.04 with i3 4.10.4 (from the packages on sur5r.net):
Binary i3 version:  4.10.4 (2015-09-08, branch "4.10.4") © 2009-2014 Michael Stapelberg and contributors
Running i3 version: 4.10.4 (2015-09-08, branch "4.10.4") (pid 5876)

Here is a log from renaming a workspace from `xxx` to `foo&bar`: http://logs.i3wm.org/logs/6223562767597568.bz2

**Comment by Airblader** [comment] 2015-09-21 09:24
If you have a pango font, you need to escape it properly as an ampersand
is illegal. You can use "foo&amp;bar".

**Comment by Airblader** [comment] 2015-09-21 09:34
I replied to this in my emails because I thought it was a mailing list question, not a bug report. :) Closing the issue with the aforementioned explanation.

If you actually don't use pango, please let us know as in this case it should not have problems with the ampersand.

**Closed by Airblader** 2015-09-21 09:34 UTC
Labels: 4.10, bug

**Comment by Adaephon-GH** [comment] 2015-09-21 10:25
Ok, I use pango and when escaping `&` or `<` (`foo&amp;bar` or `foo&lt;bar`), the names are displayed. 

But think that does not really solve the issue. At the very least this should be mentioned in the User's Guide because it is far from obvious without at least some in-depth knowledge about pango and how i3bar renders names. 

Far better would be if the characters that cause this issue would be escaped automatically (for displaying, not when setting the name), so that the name shown is actually the name i3 knows.

**Comment by Airblader** [comment] 2015-09-21 10:29
> At the very least this should be mentioned in the User's Guide 

It is: "Workspace names are parsed as Pango markup by i3bar." with a link to pango markup explaining everything in detail.

> Far better would be if the characters that cause this issue would be escaped automatically

If we automatically escape any character, workspace names wouldn't actually support pango markup anymore, so that doesn't really make sense.

**Comment by Adaephon-GH** [comment] 2015-09-21 11:09
> > At the very least this should be mentioned in the User's Guide

> It is: "Workspace names are parsed as Pango markup by i3bar." with a link to pango markup explaining everything in detail.

Oh, :flushed:. I confess, I just looked if `&` was mentioned anywhere. 

> If we automatically escape any character, workspace names wouldn't actually support pango markup anymore, so that doesn't really make sense.

Oh, again. I seems I completely missed when the markup feature was introduced. I thought pango would just be used to allow for the usage of other fonts than X11 core fonts.

Thanks for the explanation, Airblader.
