### ISSUE TITLE
Google Chrome freezes

### ISSUE THREAD

**Issue by hholst80** [i3/i3#2736] opened 2017-04-11 09:30 UTC
Output of `i3 --moreversion 2>&- || i3 --version`:

```
Binary i3 version:  4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13 (2016-11-08) (pid 2711)o abort…)
Loaded i3 config: /home/hholst/.config/i3/config (Last modified: mån 10 apr 2017 09:41:04, 92736 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5703789046661120.bz2

**What I did:**

Press "Delete Merged branches" in GitLab gui.

**What I saw:**

Google Chrome looks up.

**What I expected instead:**

Press Escape to abort to make chrome respond again (I could not interact with it at all until I did so).

**Additional stuff**

```
Google Chrome	57.0.2987.133 (Official Build) (64-bit)
Revision	ec33cd0c06881d919ac0de419d829ad914e0be8f-refs/branch-heads/2987@{#887}
OS	Linux 
JavaScript	V8 5.7.492.71
Flash	25.0.0.127 /home/hholst/.config/google-chrome/PepperFlash/25.0.0.127/libpepflashplayer.so
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
Command Line	/usr/bin/google-chrome-stable --flag-switches-begin --flag-switches-end
Executable Path	/opt/google/chrome/google-chrome
```

![image](https://cloud.githubusercontent.com/assets/6200749/24902310/15c7e6c6-1eaa-11e7-9ecd-c7dd7f031434.png)

**Comment by Airblader** [comment] 2017-04-11 09:31
What makes you think this is an i3 issue?

**Comment by hholst80** [comment] 2017-04-11 10:16
It works fine with firefox. It also works fine with gnome shell and google chrome.

**Comment by hholst80** [comment] 2017-04-11 10:37
I expect this to be some kind of error with i3 because gitlab pulls up an application modal dialog:

![image](https://cloud.githubusercontent.com/assets/6200749/24905229/8a36fb4c-1eb3-11e7-8df6-54544a43fef9.png)

**Comment by Airblader** [comment] 2017-04-17 08:52
This is a known problem with Chrome, I believe. It has to do with the fact that Chrome busy loops until a certain event which it isn't actually guaranteed to get right away.

I am 99% that this is a Chrome bug, but I'll leave this open until someone (including me) had the time to look up again what exactly the problem was, given that this is admittedly vague (can't always have perfect memory :-) ).

**Comment by AsaAyers** [comment] 2017-07-10 20:22
One easy way I can reproduce this is to right click on an item in my bookmark bar and select "Edit". When Chrome opens a modal, it won't let you do anything until it's gone. So it looks like it locks up, but escape fixes it by closing the invisible modal.

Here is my log of exactly what happens when the edit modal opens. is `Not a managed window, ignoring UnmapNotify event` helpful? I don't know what it means.

`DISPLAY=:0 i3-dump-log -f`
```
07/10/2017 01:12:22 PM - handlers.c:handle_event:1369 - event type 85, xkb_base 85
07/10/2017 01:12:22 PM - handlers.c:handle_event:1378 - xkb event, need to handle it.
07/10/2017 01:12:22 PM - handlers.c:handle_event:1404 - xkb state group = 0
07/10/2017 01:12:22 PM - handlers.c:handle_event:1369 - event type 85, xkb_base 85
07/10/2017 01:12:22 PM - handlers.c:handle_event:1378 - xkb event, need to handle it.
07/10/2017 01:12:22 PM - handlers.c:handle_event:1404 - xkb state group = 0
07/10/2017 01:12:22 PM - handlers.c:handle_event:1369 - event type 7, xkb_base 85
07/10/2017 01:12:22 PM - handlers.c:handle_enter_notify:129 - enter_notify for 0080006f, mode = 0, detail 4, serial 12477
07/10/2017 01:12:22 PM - handlers.c:handle_enter_notify:130 - coordinates 1329, 353
07/10/2017 01:12:22 PM - handlers.c:handle_event:1369 - event type 18, xkb_base 85
07/10/2017 01:12:22 PM - handlers.c:handle_unmap_notify_event:446 - UnmapNotify for 0x01c0004e (received from 0x000002a0), serial 12477
07/10/2017 01:12:22 PM - Not a managed window, ignoring UnmapNotify event
```

**Comment by acrisci** [comment] 2017-07-15 19:57
This is kind of a serious issue because it affects any modal including alerts. Reproduce that by pressing F12 to get into the developer console and run javascript `alert('hi');` and you will see the same exact freeze.

The modal is actually appearing, but outside the visible bounds of the window. Make the window floating and resize it to be very wide. You will see that the modal actually pops up on the very right side. This to me suggests there is an issue with the window not being able to tell how large it is for some reason.

The UnmapNotify event in the above is unrelated. I think it's the context menu disappearing after you click `edit`.

Another observation is that if you make the chromium window very narrow, the modals appear in the right place.

I can reproduce this issue on both i3 and openbox. Gnome seems to get the right behavior which suggests that there is something we can do to fix it (but maybe not).

We aren't ignoring any client requests and the properties of the chrome window in both Gnome and i3 seem to look similar.

**Comment by psychon** [comment] 2017-07-16 06:49
> The modal is actually appearing, but outside the visible bounds of the window.

My 5c: Sounds like Chromium gets some ConfigureNotify event with wrong / bogus content. Looking around a bit (and having no clue about i3's code), I wonder if [this code](https://github.com/i3/i3/blob/5376a972c4a27148d720c27b91a44bb24e871cd5/src/xcb.c#L75-L88) does the right thing. However, this `DLOG` output would appear in debug output and so apparently it is not executed here?

**Comment by AsaAyers** [comment] 2017-08-11 17:44
My multi-monitor layout is `[laptop] [center monitor ] [right monitor]`. If Chrome is on my laptop screen, it displays correctly. This isn't related to which monitor is primary. I used `xrandr` to make my center `--primary`, and I can still only see the chrome modal when it's on the far left monitor. When Chrome tries to show a modal while on my center monitor, I can move my workspace to my left monitor and the modal appears, moving it again makes it disappear again.

xrandr shows my center monitor is: `DP-3 connected primary 3840x2160+2880+0 (normal left inverted right x axis y axis) 607mm x 345mm`. I think Chrome may be failing to account for that `+2880+0` offset. 

When floating and spanning 2 monitors, the modal gets forced onto the right monitor. This didn't seem to happen with 3. When on a single monitor, it is only visible on the left (0x0) monitor.

<details>
<summary>Screenshot experiments</summary>

I bookmarked this issue and edited it to get the modal open. All of the screenshots are my simply moving the window around, that "Edit bookmark" was left open.

![left-float](https://user-images.githubusercontent.com/324999/29224887-025100f0-7e81-11e7-87eb-ee20d91b2743.png)

![left-center-float](https://user-images.githubusercontent.com/324999/29224891-09a37900-7e81-11e7-95ed-72d101b53408.png)

![left-center-right-float](https://user-images.githubusercontent.com/324999/29224894-0d88c9da-7e81-11e7-8a29-f5606ed0f157.png)
![center-float](https://user-images.githubusercontent.com/324999/29224949-46a468d2-7e81-11e7-9ddb-e5bc55f6fc2f.png)
![center-right-float](https://user-images.githubusercontent.com/324999/29224951-495eee9e-7e81-11e7-9ce6-604798b61fb5.png)
![right-float](https://user-images.githubusercontent.com/324999/29224957-50232b5a-7e81-11e7-8598-207bb3179983.png)

![left](https://user-images.githubusercontent.com/324999/29224879-faf29936-7e80-11e7-8baa-523bd648c9ae.png)

![center](https://user-images.githubusercontent.com/324999/29224962-55a6adae-7e81-11e7-98cb-9b025b0a8438.png)
![right](https://user-images.githubusercontent.com/324999/29224965-5868d148-7e81-11e7-941d-dfb446356696.png)
</details>

I have used Chrome on multiple monitors for years, and chrome+i3+multiple monitors for a couple years now. I only started encountering this problem when I changed computers and I don't have my old one now. I didn't keep Chrome on my left monitor with my old computer, so there must be another factor to this.

**Closed** 2020-04-24 10:13 UTC
Labels: 4.13, bug, needs info
