### ISSUE TITLE
Truncated rendering of gvim when using tabs

### ISSUE THREAD

**Issue by ubitux** [i3/i3#2426] opened 2016-08-17 08:57 UTC
Output of `i3 --moreversion 2>&- || i3 --version`:

```
Binary i3 version:  4.12 (2016-03-06, branch "4.12") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.12 (2016-03-06, branch "4.12") (pid 341)
Loaded i3 config: /home/ux/.config/i3/config (Last modified: Fri 12 Aug 2016 03:28:25 PM CEST, 414515 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5703274724327424.bz2

**What I did:**

1. Go to a clean workspace, `meta+enter` to spawn a term, run `gvim /tmp/foo`
2. Within gvim scope: `meta+v`, `meta+s`, `meta+enter`, `meta+arrowup`
3. `meta+leftarrow` to focus orig term, `gvim --remote-tab-silent /tmp/bar`

**What I saw:**

The bottom of gvim is now truncated, unless I resize the vertical split (for instance).

**What I expected instead:**

The bottom of gvim being correctly rendered (as it is when skipping step 2. for example)

**Comment by Airblader** [comment] 2016-08-17 08:58
Can you provide a screenshot please?

**Comment by Airblader** [comment] 2016-08-17 09:00
I can reproduce this, but this will very likely be a gvim issue.

**Comment by Airblader** [comment] 2016-08-17 09:01
Also see #1047

**Comment by ubitux** [comment] 2016-08-17 09:08
http://ubitux.fr/pub/pics/i3-2426-before-tab.png
http://ubitux.fr/pub/pics/i3-2426-after-tab.png
http://ubitux.fr/pub/pics/i3-2426-after-resize.png

Note: I'm using

set guioptions-=m
set guioptions-=T
set guioptions+=c
set guifont=Monospace\ 9

But it's reproducible without this vim conf.

I'm not used to any other tiling WM.

**Comment by Airblader** [comment] 2016-08-20 12:55
> I'm not used to any other tiling WM.

No need to learn it in-depth. We just need to know whether this is a gvim or an i3 issue.

**Comment by Airblader** [comment] 2016-09-11 19:54
Closing this now since we have strong indications that it's a gvim issue and no tests with other WMs have been done to disprove this.

**Closed by Airblader** 2016-09-11 19:54 UTC
Labels: 4.12, bug, needs info
