### ISSUE TITLE
Programs with splash screens causes layouts to crash i3

### ISSUE THREAD

**Issue by Hubro** [i3/i3#3645] opened 2019-03-17 05:02 UTC
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

When a program with a splash screen (in my case Slack) matches the swallow criteria of a layout, i3 crashes.

## Expected Behavior

Not crashing.

## Reproduction Instructions

1. Create a layout that swallows windows matching the criteria `[class="^Slack$"]`. [Here's an example](https://gist.githubusercontent.com/Hubro/c9cacdc95398629ba9163a1fc7add456/raw/48a7ccd42809bd6ef61cf0ff4c3c7a78f5d2fd24/i3-communication-layout.json). 
1. Append the layout (`append_layout`)
1. Launch Slack. Make sure Slack isn't already running, as it won't produce a splash screen.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.16.1 (2019-01-27) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.16.1 (2019-01-27) (pid 798) abort…)
Loaded i3 config: /home/tomas/.config/i3/config (Last modified: Sun 17 Mar 2019 05:03:47 AM CET, 2860 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
Config URL: https://gist.githubusercontent.com/Hubro/c9d305348ef7595ce2e06f4bae931304/raw/9439c99a335828c10531844b9c9b40e64757af0c/config
</pre>

<pre>
Logfile URL: https://logs.i3wm.org/logs/5649881897107456.bz2
</pre>

<pre>
- Linux Distribution & Version: Arch Linux
- Are you using a compositor (e.g., xcompmgr or compton): No
</pre>

[This issue was also reported on Reddit a couple of months ago](https://www.reddit.com/r/i3wm/comments/aa2yzg/programs_with_splash_screens_crash_i3_when_being/), but I was unable to find the issue filed on GitHub. My apologies in advance if I simply missed it.

**Comment by orestisf1993** [comment] 2019-03-17 09:28
Probably a duplicate of https://github.com/i3/i3/issues/3610 but I haven't attempted to reproduce that one yet.

**Comment by orestisf1993** [comment] 2019-03-17 23:35
```diff
diff --git a/libi3/draw_util.c b/libi3/draw_util.c
index f88360dc3..bca397f17 100644
--- a/libi3/draw_util.c
+++ b/libi3/draw_util.c
@@ -23,7 +23,7 @@ static void draw_util_set_source_color(surface_t *surface, color_t color);
 
 #define RETURN_UNLESS_SURFACE_INITIALIZED(surface)                               \
     do {                                                                         \
-        if ((surface)->id == XCB_NONE) {                                         \
+        if ((surface)->cr == NULL || (surface)->id == XCB_NONE) {                \
             ELOG("Surface %p is not initialized, skipping drawing.\n", surface); \
             return;                                                              \
         }                                                                        \
```

I'd like to find the root cause but this patch fixes the crash for me.

**Comment by Hubro** [comment] 2019-03-17 23:39
TheSilvus uploaded a backtrace in the closed bug report: https://github.com/i3/i3/issues/3610#issuecomment-459988658

**Comment by orestisf1993** [comment] 2019-03-17 23:40
The linked file doesn't contain an actual backtrace. I do have a backtrace though.

**Comment by orestisf1993** [comment] 2019-03-18 00:24
Regression: 7ac37d8ae4

**Closed** 2019-03-19 09:16 UTC
Labels: 4.16, bug, reproducible
