### ISSUE TITLE
keyboard layout toggle in i3 status bar

### ISSUE THREAD

**Issue by frrobert2** [i3/i3#3311] opened 2018-06-16 13:50 UTC
## I'm submitting a…

<pre>
[X] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Currenly I use two keyboard layouts English and Greek
1. From a reboot:  If you login in to i3wm from a reboot there is no keyboard layout toggle in the i3 status bar.

2. If you login to LXDE, logout, and then login to i3wm with the the standard i3 status bar:   When you login to i3wm there is a keyboard layout toggle in the the i3 status bar in the righthand corner.  

3. If you login to LXDE, logout, and then login to i3wm with the the i3 staus using a conky script:  When you login to i3wm there is a keyboard layout toggle as a tile.  

## Expected Behavior
Consistant behavior of the keyboard toggle

## Reproduction Instructions
Install mutliple keyboard layouts.
Login in to LXDE and do something and be in desktop long enough for inialization script to complete.
If you login and immediately logout sometimes the behavior will not happen.
Logout out of LXDE and login to i3.
The keyboard layout toggle wiill appear with default i3 staus bar.
Change i3 to use another script such as a shell script calling conky.
logout and log back in and keyboard layout should appear as tile.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: Binary i3 version:  4.11 (2015-09-30, branch "4.11") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.11 (2015-09-30, branch "4.11") (pid 18908)
Loaded i3 config: /home/frrobert/.config/i3/config (Last modified: Fri 15 Jun 2018 04:27:47 PM EDT, 62145 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

</pre>

<pre>
1   # i3status configuration file.
  1 # see "man i3status" for documentation.
  2 
  3 # It is important that this file is edited as UTF-8.
  4 # The following line should contain a sharp s:
  5 # ß
  6 # If the above line is not correctly displayed, fix your editor first!
  7 
  8 general {
  9         colors = true
 10         interval = 5
 11         output_format = i3bar
 12 }
 13 
 14 order += "disk /"
 15 order += "disk /home"
 16 order += "ethernet _first_"
 17 order += "tztime local"
 18 
 19 
 20 ethernet _first_ {
 21         # if you use %speed, i3status requires root privileges
 22         format_up = "E: %ip"
 23         format_down = "E: down"
 24 }
 25 
 26 tztime local {
 27         format = "%m-%d-%Y %H:%M:%S"
 28 }
 29 
 30 load {
 31         format = "%1min"
 32 }
 33 
 34 disk "/" {
 35         format = "%avail"
 36 }
 37 disk "/home" {
 38         format = "%avail"
 39 }

</pre>

<pre>
Logfile URL:
</pre>

<pre>
- Linux Distribution & Version: Ubuntu 16.04 
- Are you using a compositor (e.g., xcompmgr or compton):no
</pre>

**Comment by Airblader** [comment] 2018-06-16 13:52
i3 / i3bar / i3status doesn't contain any tooling for this, that's not the window manager's job. I guess your DE launches some utility which provides a tray icon (which i3bar picks up on).

You need to figure out the name of that application and ensure to launch it yourself. Closing as not a bug.

**Closed by Airblader** 2018-06-16 13:52 UTC
Labels: enhancement

**Comment by frrobert2** [comment] 2018-06-16 14:35
Sorry for posting as a bug.  Thank you for providing guidance on fixing my problem.  I do appreciate it.
The issue was in case anyone else has it.  
Lxde was calling dbus for the session and if I logout of LXDE and login in to i3 the dbus session was still running and putting the icon in the i3 status bar.
So if you want system icons in the i3 status bar run 
exec --no-startup-id dbus-launch
in your i3config file.
