### ISSUE TITLE
Focusproblem using split h

### ISSUE THREAD

**Issue by Simerax** [i3/i3#4077] opened 2020-05-11 16:01 UTC
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

We start i3. No special setup, bindings or else. We have an empty screen with no containers.
When creating two new containers they are split equally on the screen (for example using the default $mod + Return to create i3-sensible-terminal's).
Both Containers have the same width.
Now the window focus of i3 is on the container to the right.
Now we activate `split h` this causes the container with focus to be split in half horizontally.
The left container is not affected and keeps it's width.

Now we have 1 Container which has 50% screen width and two containers each with 25% screen width.
So far the behaviour is as expected.

Now I want to create a new container. This Containers width should be ~33%. For this to work i have to focus the container with 50% width. If i would focus one of the 25% width containers i would just get a ~16.67% width container.

So far still as expected.

Now let's assume I had split the 50% container vertically using `split v`.
This would mean i have 2 Containers on top of each other both 50% screen height and 50% screen width and then the other 2 containers with 100% screen height and both with 25% screen width.

Now I'm no longer able to create a new Container with ~33% screen width. If I focus one of the 50%width %50height containers and use `split h` to create a new container i will get a 25% width and 50% height container.

## Desired Behavior

I would like to be able to say "hey I want to go back to the 'default' container creation/splitting mode" and create a new container which width is created from using 100% of the screen width and not from the point of "currently im in a group of containers which together use %50 width and everything has to be squeezed into those 50%"

In my case this would have been a ~33% width container because the two existing container-groups take 50% each therefore 100% / 3 => ~33%

Maybe this is already in i3 but i was not able to find this functionality.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: Binary i3 version:  4.17.1 (2019-08-30) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.17.1 (2019-08-30) (pid 2219)abort…)
Loaded i3 config: /home/xaver/.config/i3/config (Last modified: Mo 11 Mai 2020 17:02:48 CEST, 2768 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
- Linux Distribution & Version: Fedora 31
- Are you using a compositor (e.g., xcompmgr or compton): compton
</pre>

**Comment by Airblader** [comment] 2020-05-11 16:19
The container layout is a tree structure, so this behavior is expected. You can focus the window, then focus its parent (which is a split container) using `focus parent` and open a new window from there.

Closing as this works as intended. Please let us know if you have further issues. Do note that for how to use i3 we'd recommend reading the userguide and then asking questions on the subreddit where you'll have significantly more people reading along.

**Closed as completed by Airblader** 2020-05-11 16:19 UTC
Labels: enhancement

**Comment by Simerax** [comment] 2020-05-11 16:25
I just wanted to add that using focus parent does work but it requires to manually repeat the command until i'm at the topmost container. Is it possible to automate this and say focus top most element instead of just parent?

**Comment by Airblader** [comment] 2020-05-11 16:52
You can write a script using the IPC that either repeats until some condition is met or figured out the right container directly and focused it using the con_id criterion.

Alternatively if you can set it up beforehand you could use marks to move windows to a specific spot.
