### ISSUE TITLE
Optionally show all workspace buttons in the bar, even the ones on other outputs

### ISSUE THREAD

**Issue by pedrocr** [i3/i3#3773] opened 2019-08-17 20:37 UTC
## I'm submitting a…
<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Bar only shows workspaces that are on the output where the bar is being displayed.

## Desired Behavior
Optionally show all workspaces from all outputs.

## Environment
I'm actually using sway and have implemented this feature here:

https://github.com/swaywm/sway/pull/4460

I was asked to also suggest it for i3 to try and keep the two projects compatible. I find this useful when using external screens where I don't show a bar (e.g., projector) but still need to know what the workspace number is so views can be moved there easily.

**Comment by Airblader** [comment] 2019-08-17 20:44
Duplicate of #1759

**Closed by Airblader** 2019-08-17 20:44 UTC
Labels: enhancement
