### ISSUE TITLE
Focus does not follow window with directional move when focus_follows_mouse is enabled

### ISSUE THREAD

**Issue by JonnyHaystack** [i3/i3#3518] opened 2018-11-10 05:20 UTC
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Expected Behavior

I have the following bindings:
`bindsym $mod+Control+H move left`
`bindsym $mod+Control+L move right`

When I use these to move a window from e.g. workspace 1 on my laptop display to workspace 2 on my monitor, I would expect the focus to follow the window as it moves. It is the usual behaviour for focus to follow the window as you move it left and right within a workspace, so I think it's reasonable to expect this to apply when moving it across a workspace with "move left" or "move right" (or even up and down if you have that kind of monitor layout).

## Current Behavior

If in my example scenario, there is already one or more windows in workspace 2, the window focus ends up on one of them instead of the one I'm moving. This behaviour is quite annoying because I then have to pause to find out where the focus has moved to, then move it back to the window I was moving so I can continue moving it to the desired location. It's really not very intuitive.

## Reproduction Instructions
To replicate:
- 2 displays needed
- Open one window on a workspace in primary display
- Open a second window on another workspace in the secondary display
- Use "move <left|down|up|right>" to move the window on the primary display to the workspace on the secondary display
- Observe that focus has not followed the window being moved per the usual behaviour

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 4.16
</pre>

<pre>
i3 config: https://pastebin.com/mgE6BRwr
</pre>

<pre>
- Linux Distribution & Version: Ubuntu 18.04, Linux 4.15.0-38-generic
- Are you using a compositor (e.g., xcompmgr or compton): No
</pre>

I also see that this issue has been raised before in #2257 (but not #809 which is a completely separate issue), and it seems it is definitely not the intended behaviour https://github.com/i3/i3/issues/2257#issuecomment-214448093 and yet it still remains...

Many thanks,
Jonathan

**Comment by Airblader** [comment] 2018-11-10 06:43
I could reopen it, but you already identified it as a duplicate, so there's no reason to have the same issue open twice. :)

**Comment by JonnyHaystack** [comment] 2018-11-10 14:04
@Airblader That's fair, but I think if the issues could be merged in some way that would be good because I took the time to write proper reproduction instructions. Also the other issue has been lying around for years without being resolved and I'm unsure of why that's happened. I can provide logs too if you think that will help.

**Comment by orestisf1993** [comment] 2018-11-10 14:08
> Also the other issue has been lying around for years without being resolved and I'm unsure of why that's happened

Because it is not reproducible for any of us. Focus moves with the window being moved.

**Comment by orestisf1993** [comment] 2018-11-10 14:09
ohh, it only happens with focus_follows_mouse = yes?

**Comment by JonnyHaystack** [comment] 2018-11-10 14:11
@orestisf1993 quite possibly. I do use that option.

**Comment by orestisf1993** [comment] 2018-11-10 14:16
Reopening to keep it separate from #2257 in case the causes are different. I also think that the behavior with mouse_warping is a bit problematic.

**Comment by Airblader** [comment] 2018-11-10 14:19
Just to address this, I was gonna move the description to the other issue (since as you said you provided much better information, thanks!), but if we do keep this one open I won't do that now. :-)

**Comment by JonnyHaystack** [comment] 2018-11-10 14:36
> Just to address this, I was gonna move the description to the other issue (since as you said you provided much better information, thanks!), but if we do keep this one open I won't do that now. :-)

Alright, thanks :smile: it's hard to know if it's the same cause or not because we don't know what the person who created the other issue had in his config file. Hopefully after resolution that could be sorted out.

**Comment by orestisf1993** [comment] 2018-11-10 14:50
In the video in #2257 it seems that they use focus_follows_mouse. It happens when the mouse ends up above a different window because of the directional move. I am pretty sure that they are the same issue now.

**Comment by orestisf1993** [comment] 2018-11-10 15:11
My current i3 session is in a "broken state", like #2257 mentions. The difference from a new, correctly functional session is that `event_is_ignored` in https://github.com/i3/i3/blob/cf553ce31e2cd2b3898dd6f020304a3d56cc799c/src/handlers.c#L137 returns `false`.

**Comment by ersi-dnd** [comment] 2018-11-18 18:32
> EDIT: Also, for me it seems to be that it's when focus_follows_mouse and mouse_warping are both enabled. If I disable either one then it works fine, at least for as long as I tested it.

Yes. I have the same issue and it's a major problem. I want 
- the mouse pointer to move along window by window as I put focus by keybind on different tiled windows in a multi-monitor setup AND
- windows to receive focus upon mouseover.

Unfortunately this is not possible when the config says:
focus_follows_mouse yes
mouse_warping output

I think it's `mouse_warping output` that does not allow the pointer to move along window by window by keybind. There should be more options to `mouse_warping`, for example "window".

**Comment by JonnyHaystack** [comment] 2018-11-18 21:05
> > EDIT: Also, for me it seems to be that it's when focus_follows_mouse and mouse_warping are both enabled. If I disable either one then it works fine, at least for as long as I tested it.
> 
> Yes. I have the same issue and it's a major problem. I want
> 
> * the mouse pointer to move along window by window as I put focus by keybind on different tiled windows in a multi-monitor setup AND
> * windows to receive focus upon mouseover.
> 
> Unfortunately this is not possible when the config says:
> focus_follows_mouse yes
> mouse_warping output
> 
> I think it's `mouse_warping output` that does not allow the pointer to move along window by window by keybind. There should be more options to `mouse_warping`, for example "window".

I think mouse_warping output should be cancelled if you moved the window to the other output by using move up/down/left/right. Either that or focus_follows_mouse should be cancelled when the cursor is moved by mouse_warping.
It seems what's happening is that you move a window to another monitor with move <direction> and then the mouse is warped to the centre of the new monitor, and then focus_follows_mouse causes the window "underneath" the cursor's new position to be focused.

And yeah I think your idea for a mouse_warping window option is a good one.

**Comment by Airblader** [comment] 2018-11-18 21:20
Let's please not turn a bug report into a feature request. Behavior should be sensible with the existing feature set, adding new options is a topic that we'd need to discuss separately from this. :-)

**Comment by JonnyHaystack** [comment] 2018-11-18 21:43
@Airblader Yes, you're quite right sorry haha.
Let me know if there's any extra info needed for the bug fix though :ok_hand:

**Comment by JonnyHaystack** [comment] 2018-11-23 19:35
Okay so now it's happening for me even with mouse_warping off.. And in that situation it doesn't focus the window under the mouse but it focused the last focused window on the display that the window was moved from.

**Comment by MatrixManAtYrService** [comment] 2019-03-03 19:14
I use the same i3 config at home at work, and I can reproduce this problem at work only.

- At work, moving a window once across a monitor boundary causes focus to move twice in that direction, so I have to move focus back in order to keep moving the window.
- At home, moving a window once causes focus to move once--to the target window is still in focus.

Home:
```
❯ i3 --moreversion
Binary i3 version:  4.14.1 (2017-09-24) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.14.1 (2017-09-24) (pid 3596)abort…)
Loaded i3 config: /home/matt/.config/i3/config (Last modified: Tue 30 Oct 2018 08:00:44 PM MDT, 10689137 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

Work:
```
❯ i3 --moreversion                   
Binary i3 version:  4.16 (2018-11-04) © 2009 Michael Stapelberg and contributors

Running version: < 4.2-200
```

If there's anything I can do to help, let me know.

**Comment by orestisf1993** [comment] 2019-04-20 09:10
Also maybe related: #3337

**Comment by Natureshadow** [comment] 2019-06-24 10:01
I can reproduce this issue with 4.16.1.

**Comment by Ergus** [comment] 2019-07-09 07:18
Same here. I have 4.16.1 too.

**Comment by Jasha10** [comment] 2020-11-13 18:24
I can reproduce this with 4.17.1.

**Comment by bechampion** [comment] 2020-11-18 16:37
I'm just hitting this now somehow , focus changes (colored border of window moves ) but my keyboard input doesnt??
```
i3 version 4.18.2-237-gcf7dd36e (2020-10-15, branch "gaps-next") © 2009 Michael Stapelberg and contributors
```

**Comment by kjetilho** [comment] 2021-03-11 23:06
Still present in 4.19, but for me `mouse_warping none` is an acceptable workaround.  (I have not been able to force the problem to reappear so far, anyway.)

**Comment by algmyr** [comment] 2021-10-17 10:57
I drilled down a bit and it seems this part is what triggers the issue https://github.com/i3/i3/blob/ab389e1d760585e758f343221da7758f7bc2c949/src/move.c#L227-L234

In particular seems like removing either (or both) of `focused = old_ws;` or `workspace_show(ws);` makes the issue go away (and probably breaks other stuff, like the test in question).

**Comment by algmyr** [comment] 2021-10-17 11:29
Played around a bit and focusing the correct container before doing the workspace back and forth to get the correct events triggered seems to do the right thing superficially. The correct container is focused on the other side, and the workspace indicator is updated which is what the workspace switching is intending to do.
```
         con_focus(con);
         focused = old_ws; 
         workspace_show(ws); 
```
@orestisfl considering you were the one to commit the fix for this years back, do you happen to have any idea if reversing the order of operations here would break anything?

**Comment by algmyr** [comment] 2021-10-17 12:52
Made #4596 to workaround this particular issue, but thinking about the whole situation there seems to be a much more fundamental issue with `focus_follows_mouse` and i3 moving the mouse around itself. See the PR for some more thoughts.

**Closed** 2021-11-05 14:32 UTC
Labels: bug, help wanted, reproducible, 4.16
