### ISSUE TITLE
thinkpad multimedia buttons not recognized

### ISSUE THREAD

**Issue by matthiaskrgr** [i3/i3#1785] opened 2015-07-06 22:31 UTC
i3 does not recognize my thinkpad media buttons

In short, I added this to my config
```
bindsym XF86AudioRaiseVolume exec xmessage 'it works A'
bindsym XF86AudioLowerVolume exec xmessage 'it works B'

bindcode 122  exec xmessage 'it works C'
bindcode 123  exec xmessage 'it works D'
```
bug nothing happens upon pressing the buttons.

xev output:

```
KeyPress event, serial 29, synthetic NO, window 0x2200001,
    root 0xc4, subw 0x0, time 17921607, (199,510), root:(1003,530),
    state 0x0, keycode 122 (keysym 0x1008ff11, XF86AudioLowerVolume), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 32, synthetic NO, window 0x2200001,
    root 0xc4, subw 0x0, time 17921734, (199,510), root:(1003,530),
    state 0x0, keycode 122 (keysym 0x1008ff11, XF86AudioLowerVolume), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 32, synthetic NO, window 0x2200001,
    root 0xc4, subw 0x0, time 17922589, (199,510), root:(1003,530),
    state 0x0, keycode 123 (keysym 0x1008ff13, XF86AudioRaiseVolume), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 32, synthetic NO, window 0x2200001,
    root 0xc4, subw 0x0, time 17922685, (199,510), root:(1003,530),
    state 0x0, keycode 123 (keysym 0x1008ff13, XF86AudioRaiseVolume), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

xmodmap -pke : http://lpaste.net/3916315304078082048
full i3 config: http://lpaste.net/4355387581660135424
i3 log:  http://logs.i3wm.org/logs/5706163895140352.bz2
i3 -v:  i3 version 4.10.2 (2015-04-16, branch "4.10.2") © 2009-2014 Michael Stapelberg and contributors

I am kinda clueless on why i3 does not recognize the buttons. They worked on other DEs and vlc recognizes them as well, if the window in focus.

I use fedora 22 on a thinkpad T420 / linux 4.0.6

**Comment by stapelberg** [comment] 2015-07-06 22:38
Most likely, a different application is grabbing these buttons. Try killing processes until you arrive at the bare minimum. Maybe try adding a different user to start with fresh configs. Are you directly starting i3 from xsession or are you using it with some desktop environment?

**Comment by matthiaskrgr** [comment] 2015-07-06 22:39
Seems to have been PEBKAC.

The problem was simultaneously had ~/i3/config which apparently was apparently read with higher priority than ~/.config/i3/config
>.<

maybe one could display a warning in some cases?

**Comment by stapelberg** [comment] 2015-07-06 22:47
I think it’d make sense to display which config file is being used (and possibly when that file was modified) in the output of `i3 --moreversion`. Pull requests implementing that would be appreciated.

I’m going to close this ticket, though, as the root cause is resolved.

**Closed by stapelberg** 2015-07-06 22:47 UTC

**Comment by hwangcc23** [comment] 2015-07-07 16:02
I am working on it: "display which config file is being used"
