### ISSUE TITLE
Issue involving workspaces assigned to "primary" behaving strangely while enabling monitors (multimonitor)

### ISSUE THREAD

**Issue by SpecialBomb** [i3/i3#4303] opened 2021-01-02 05:46 UTC
#

## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
When turning on an output next to another and making it primary using xrandr (i.e. `xrandr --output output-2 --right-of output-1 --auto --primary`), workspaces assigned to the "primary" output will not move to the primary monitor properly. Instead, the first workspace assigned "primary" in the config file is moved over, and the rest are ignored and stay on the monitor they were originally on.

## Expected Behavior
Expected behavior is if xrandr is executed to configure a new primary monitor next to another, all workspaces assigned "primary" will move to the new primary monitor.

This is how it behaves in 4.18.3, the version I was using before updating. The way this happens is quite specific, and could actually just be some sort of bug in itself, but I depend on it for my dockable laptop workflow. Oddly, if the second output is never turned off using xrandr, no workspaces move at all. You must turn the the other output off before re-enabling it with `--auto` and making it the new primary using `--primary`. This happens in both the previous version and the current one.

## Reproduction Instructions
You must have at least two monitors/outputs. In the default configuration file, create three workspaces named 1, 2 & 3. Assign workspace 1 to one specific output (this is how it is in my current configuration, may or may not be related to the bug). Assign workspace 2 & 3 to primary. Assignment settings should be in order like so:

```
workspace 1 output "output-1"
workspace 2 output primary
workspace 3 output primary
```

Start i3. Execute `xrandr --output output-1 --primary --auto --output output-2 --off`. This will disable the second monitor, and all workspaces should be on output-1. Execute `xrandr --output output-2 --primary --auto --right-of output-1`. Use whatever position option that makes sense in your case, it probably doesn't matter. Workspace 1 should be on output-1. Workspace 2 will move to output-2, the new primary. Workspace 3 will stay on output-1 despite the workspace being assigned to the primary output.

## Environment
Before the following information, I must state my hardware, which is why I discovered this issue. I use a Lenovo thinkpad with a dock. In order to make i3 seamlessly transfer all my workspaces to my main monitor (with one staying on my laptop), I made udev scripts run xrandr with the settings I need to change my primary monitor depending on whether I'm on the dock or not. Thus, most of my workspaces are assigned to "primary". This is a very specific use case since I'm basically hotswapping monitors, which is not very expected. I am unsure if the way this all used to work in my previous version of i3 is even intentional or not.

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.19 (2020-11-15) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.19 (2020-11-15) (pid 13642)
Loaded i3 config: /home/quen/.config/i3/config (Last modified: Fri 01 Jan 2021 11:17:13 PM EST, 3613 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<summary>Config file</summary>
https://gist.github.com/SpecialBomb/228871ecef211197736cfa627e6b3a09

<pre>
Logfile URL: https://logs.i3wm.org/logs/5753578949967872.bz2
</pre>

<pre>
- Linux Distribution & Version: Void Linux x86_64 with glibc, linux kernel 5.9.16_1
- Are you using a compositor (e.g., xcompmgr or compton): I do not use a compositor
</pre>

**Comment by orestisfl** [comment] 2021-01-02 12:43
Thanks for the detailed report.

This seems to be a duplicate of https://github.com/i3/i3/issues/4261. See if the current `next` branch fixes it for you.

**Closed as completed by orestisfl** 2021-01-02 12:43 UTC
Labels: bug, 4.19

**Comment by SpecialBomb** [comment] 2021-01-03 01:39
> Thanks for the detailed report.
> 
> This seems to be a duplicate of #4261. See if the current `next` branch fixes it for you.

I'll try it out maybe. I'll have to get it compiled and such sometime.
