### ISSUE TITLE
wrong key bindings in config generated by i3-config-wizard

### ISSUE THREAD

**Issue by bard** [i3/i3#1782] opened 2015-07-03 07:55 UTC
I previously misinterpreted the issue as i3 ignoring my dvorak layout when listening for keybindings, because e.g. to kill a window I have to press `$mod+Shift+apostrophe` (apostrophe being the key that is `q` is on qwerty).

Looking at the configuration file, though, I see `kill` is indeed bound to `$mod+Shift+apostrophe`. Other actions follow the same pattern, they're bound such that the same physical keys have to be pressed that would be pressed on a qwerty.

Perhaps i3-config-wizard is generating combinations based on key codes but writing them based on key syms?

Version info:

```
Binary i3 version:  4.10.2 (2015-04-16, branch "4.10.2") © 2009-2014 Michael Stapelberg and contributors
Running i3 version: 4.10.2 (2015-04-16, branch "4.10.2") (pid 3516)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

Log: http://logs.i3wm.org/logs/5652383656837120.bz2

**Comment by stapelberg** [comment] 2015-07-03 08:03
Can you provide the output of `xmodmap -pke` please? Did you use the same layout when running `i3-config-wizard`? To clarify, generating a config which uses keysyms is the very purpose of that tool.

**Comment by bard** [comment] 2015-07-03 08:14
I understand—it's the "based on key codes but" part that would sound me wrong if that were actually the case.

The layout I'm using was the same when running `i3-config-wizard`. Output of `xmodmap -pke`: https://gist.github.com/bard/a9d7f2c29f6bce292a39

**Comment by bard** [comment] 2015-07-03 09:56
To be sure, I re-ran `i3-config-wizard` and it produced the same bindings.

**Comment by stapelberg** [comment] 2015-08-06 07:56
The tool works exactly as intended here. i3.config.keycodes contains

```
# kill focused window
bindcode $mod+Shift+24 kill
```

From your `xmodmap -pke` output:
```
keycode  24 = apostrophe quotedbl apostrophe quotedbl dead_acute dead_diaeresis dead_acute
```

It is intentional that http://i3wm.org/docs/userguide.html#_default_keybindings focuses on the key _positions_, not their labels. We want the default config to make sense with regards to positions (specifically the left/down/up/right keys).

Looking at https://en.wikipedia.org/wiki/Dvorak_Simplified_Keyboard#/media/File:KB_United_States_Dvorak.svg, binding dvorak’s apostrophe is perfectly consistent.

Closing this as working as intended.

**Closed by stapelberg** 2015-08-06 07:56 UTC
Labels: 4.10

**Comment by bard** [comment] 2015-08-06 22:10
I saw http://i3wm.org/docs/userguide.html#_default_keybindings before encountering the issue, but it didn't ring any bells. I assumed the diagram was a convenience and key bindings would work like every other application out there, i.e. `mod+letter`, not `mod+position`. Do you think it might be worth to add a note in the documentation?

However, even when aware of the above, to start using i3 a Dvorak user must make a choice among 1) memorizing unusual key bindings, such as `mod+u` for fullscreen, `mod+d` to split horizontally, `mod+.` to split vertically (which are mnemonic in qwerty: `mod+f`, `mod+h`, `mod+v`), 2) memorize positions (difficult as they are, except for direction, arbitrary), or 3) configure key bindings (ok for customizing, somewhat harsh to just begin to use something). I tried all the options in that order, each is far from optimal and I'd gladly have traded them for the more usual `mod+letter` approach. I understand it works as intended but that just shifts the source of the experience from implementation to design, it doesn't change the nature of the experience.

Anyway, configuration solved my problem a while ago and I'm a very happy i3 user. Ultimately it's your call whether there's something improvable here for the non-qwerty niche.

**Comment by stapelberg** [comment] 2015-08-07 06:38
FWIW, I think this is ultimately subjective. I don’t use QWERTY either, but memorizing positions works better for me than memorizing the key description. In fact, if you asked me where “k” is on my keyboard layout, I’d need to first simulate typing it before I could answer.

Also, the positions are not entirely arbitrary, and they don’t entirely follow QWERTY mnemonics either: the different layout are close together (with no mnemonics), dmenu/full screen/resize mode are close to the layout keys, with matching QWERTY mnemonics, focus parent is close to all of these keys but using the NEO mnemonic u for “level up”, as that function used to be called…

There’s a fourth option: just use /etc/i3/config and don’t use i3-config-wizard, effectively getting a config file with QWERTY mnemonics:

```
grep -v 'exec i3-config-wizard' /etc/i3/config > ~/.i3/config
```

I’ll add a sentence to the userguide about this.

**Comment by bard** [comment] 2015-08-11 09:38
Indeed, my fingers too know better than my brain where keys are—it makes no difference to them to hit "u" instead of "f" for "fullscreen", it's the memorizing stage that prefers the latter.

Thanks for considering adding a note!

**Comment by badrihippo** [comment] 2020-10-15 09:38
@bard did you eventually rewrite your config to be more Dvorak-friendly? I'd be interested in seeing the config file if you still have it around (and might be useful for other Dvorak typers too!).

**Comment by krisfris** [comment] 2021-05-31 08:32
I find this super confusing as a first-time i3 user. Vim works based on letters not positions so I'm used to the alternative positions of the navigation keys when using the Dvorak keyboard layout. The i3 documentation refers to keybindings by letters so for each keybinding I have to figure out where that letter would be on Qwerty. In my mind, I map actions to letters. My fingers will then automatically find the right key. This is the same as typing text or code, I think of the words and letters, not the positions of the keys.

**Comment by lee2sman** [comment] 2021-08-09 23:43
As can be read above and many other locations online, the install process for Dvorak users and I'm assuming other alternative keyboard users is very difficult to figure out since the assumptions are so strange since it requires you switch to Qwerty to use.

The process, while bizarre, is however straightforward if you read 6 or so reddit / stackoverflow posts, so I've compiled the process in one place [here](https://gist.github.com/lee2sman/716c73e1fb7d5979d98fb6ad325a3ab2).
