### ISSUE TITLE
bindsym + [floating] will disable the bindings if they are the builtin bindings for non-floating windows

### ISSUE THREAD

**Issue by c02y** [i3/i3#4613] opened 2021-10-21 00:09 UTC
## I'm submitting a…
  
  <pre>
  [x] Bug
  [ ] Feature Request
  [ ] Documentation Request
  [ ] Other (Please describe in detail)
  </pre>
  
  ## Current Behavior
  

I'm not sure this is a bug or I just use it incorrectly.  

  For example, if I set 
  ```
  bindsym Mod1+1 [floating con_id="__focused__"] resize set 40 ppt 50 ppt, move position center
  bindsym Mod1+2 [floating con_id="__focused__"] resize set 70 ppt 80 ppt, move position center
  bindsym Mod1+3 [floating con_id="__focused__"] resize set 100 ppt 98 ppt, move position center
  ```
  will resize the focused floating windows to a specific size.
  
  The `Alt+1/2/3` bindings work expected, but for example, when I use programs like qutebrowser, `Alt+1/2/3/..` (which are builtin bindings for qutebrowser) are used to switch tabs, even qutebrowser window is not floating, the `Alt+1/2/3` will become unusable for qutebrowser. 
  
  ## Expected Behavior
  
  when I use `bindsym Mod1+1 [floating con_id="__focused__"] xxx`, `Mod1+1` should only be handled by i3wm for `[floating con_id="__focused__"]` windows, otherwise, they won't be handled, but it doesn't mean they will be disabled or ignored completely for non-floating windows.
  
If this is designed like this, I'll rebind those keys then.
  
  ## Reproduction Instructions
  
  1. Add above config into i3/config file and reload
  2. Open a program such as qutebrowser which has the builtins `Alt+1/2/3` bindings
  3. Do not float it, try `Alt+1/2/3`
  
  ## Environment
  
  Output of `i3 --moreversion 2>&-`:
  <pre>
  i3 version: 
Binary i3 version:  4.20 (2021-10-19) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.20 (2021-10-19) (pid 1457)
Loaded i3 config:
  /home/chz/.config/i3/config (main) (last modified: Thu 21 Oct 2021 07:26:18 AM CST, 1985 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
  </pre>
  
  
  <details><summary>Config file</summary><pre>
Default config with the extract three bindsym lines 
  </pre>
  </details>
  
  
  <pre>
  Logfile URL: https://logs.i3wm.org/logs/5768193515716608.bz2
  </pre>
  
  
  <pre>
  - Linux Distribution & Version: Linux 5.14.13-1-MANJARO
  - Are you using a compositor (e.g., xcompmgr or compton): None
  </pre>

**Comment by Airblader** [comment] 2021-10-21 04:47
There indeed is a misunderstanding here.

```
bindsym x [criteria] command
```

This doesn't say "execute command only if criteria is true", it says "execute command for all windows matching criteria".

The criteria are not part of the `bindsym` syntax; it simply expects any i3 command as its argument. And any i3 command can be prefixed by criteria to execute the command on all matching windows.

A notion of restricting a binding to specific windows or even window states doesn't exist in i3. Closing as working as intended.

**Closed as completed by Airblader** 2021-10-21 04:47 UTC
Labels: bug, 4.20
